:sectnums!: 
[#afterword] 
= Afterword: A Personal Perspective 

My conversion to libertarianism took place over the last few years. I began as
a constitutional conservative, but my quest for intellectual consistency and a
universal principle of justice wouldn’t let me rest there.

I liken my awakening to what happened to the character Neo in the movie, _The
Matrix_.  Neo ingests the “red pill,” which chemically severs his neural
connections to the system run by intelligent machines and enables him to begin
to appreciate reality. He discovers that humans are connected neurally to a
simulated world run by the machines ‒ although humans are not aware of this ‒
and that humanity is actually being used by the machines as a physical power
source.

There is probably no better analogy than this for how we were all educated, how
we live under statism, and how a full appreciation of libertarianism can open
one’s eyes.

My adoption of the libertarian philosophy has provided me with a number of
intellectual and psychic benefits:

I am politically agnostic. I no longer care about distinguishing between,
arguing about or supporting political parties or candidates. To me they’re all
part of the problem, namely, the state. The differences between the various
parties and candidates are trivial compared with the differences between
statism and a voluntary society. I have a crisper, more consistent view about
morality and what I am for and against. Once you absorb the NAP it brings a
great moral clarity to your life. I am less preachy about the lifestyles of
strangers. As long as someone is not interfering with my body or property I
don’t have any interest in interfering with theirs (the “live and let live”
principle). I try to treat people as unique individuals and not merely as
replaceable members of categories. I am completely against war and offensive
projections of force around the world. Most importantly, I have much greater
faith in the ability of private individuals to solve complex problems facing
humanity when left free to do so. When you better understand the role of
entrepreneurial ingenuity in economic history it gives you cause for great
optimism (if we can just rid ourselves of the yoke of the state).  While I
would dearly like to see our society evolve into a stateless society, I know
that this is unlikely in my lifetime. However, being a libertarian does not
mean that I will never be satisfied unless we have a stateless society; rather,
it means that I object to every single instance of state action due to its
immorality (as well as its economic indefensibility), and will derive great
satisfaction from the elimination or thwarting of each such instance. In other
words, it’s not all or nothing that counts, it’s every single thing.

What ultimately drives me to be a libertarian? Murray Rothbard, the modern
father of libertarianism, put it best when he once wrote that a genuine
dedication to liberty “can only be grounded on a passion for justice.... And,
to have a passion for justice, one must have a theory of what justice and
injustice are. ” As I’ve tried to detail in this paper, I regard the state as
the largest and most frequent and dangerous purveyor of injustice, and
therefore playing some role in reducing this injustice is what drives me. As
Rothbard went on to note, other lofty goals, such as the abolition of poverty,
cannot be attained by man simply willing them, but rather they require a
complex set of economic factors to operate in a certain way over long periods
of time; on the other hand, injustices are deeds inflicted by one man on
another and, since they are the actions of men, their elimination is subject to
man’s instantaneous will. Per Rothbard again, “For instant justice could be
achieved if enough people so willed.” Changing wills, then, is the libertarian
mission.

If any of this seems interesting to you, I invite you to get onboard!
