[#ch-conclusion]
= Conclusion

The libertarian views the process of moving to a stateless society like riding
on a train from where we are now to where we want to be. We know that the train
must ultimately be heading in our desired direction because the very nature of
the state is morally and efficaciously untenable, and it is only a matter of
time before the state collapses on itself as it confronts reality. Sometimes
the train will be traveling faster and sometimes slower; sometimes in a more
circuitous route and sometimes more directly. The libertarian’s key tasks are
to try to accelerate the velocity and increase the directness of this train.

Along the way the libertarian is happy for the train to stop to pick up those
who might want to ride with us, such as statists of both the political left and
right who agree with the libertarian on particular issues. However, the
libertarian recognizes that such riders will likely get off well before we
reach our final destination. That’s fine too.

The libertarian is guided by a very compelling, universally applicable
principle of non-aggression, and should never be reticent to articulate this
principle when people question why he is riding on this train.

Nor should the libertarian be reticent to press the statist about which
fundamental principle underlying statism can be more compelling than being
against the initiation of force. In fact, if you were to ask a statist if he is
against the initiation of force, and if he believes that all men should live by
the same standard, you’d likely get a resounding “Yes!” It’s only when you
point out that this leaves no room for the state that the statist starts to
backtrack.

If no man is born with any natural entitlement to rule another – a euphemism
for “initiate force against another” – then the burden of proof must logically
be on the statist to justify coercion by individuals at the state against
others, and not on the libertarian to justify freedom from such coercion. Yet,
in arguments about political philosophy, statists typically invert the burden
of proof, as if coercion by individuals at the state is the natural order of
things. Libertarians ought to vigorously reject this framing of the argument.

In this respect, as libertarian historian Tom Woods has noted, the most
effective way for a libertarian to frame the argument is as follows: since
libertarianism rejects the legitimacy of the initiation of force, to be against
libertarianism is to believe in the legitimacy of the initiation of force.
Therefore, the libertarian ought to challenge the statist to articulate his
compelling arguments in favor of the initiation of force in society.
footnote:[Libertarian philosopher Hans-Hermann Hoppe has developed the concept
of “argumentation ethics” to show the illogicality of a statist using argument
to try to persuade another of the merits of coercion. It is too complex to
explain in a mere footnote but, for a taste, Hoppe shows that if a statist
takes the position in argument that one man can forcibly dictate what another
man does with his body (and, by extension, his property), then the statist is
engaging in a self-contradiction, which is a fatal flaw in any logical
argument. This is because in resorting to persuasion through argument to make
his point rather than using force, the statist is necessarily implying that his
opponent has free use of his body to stand there and engage in the debate. Put
more simply, it is self-contradictory for the statist to argue that disputes
should be resolved by force since he is not resolving the current dispute by
force but, rather, by argument!]

This paper has sought to explain that (a) there is no technical reason that a
stateless society could not function, (b) such a society would be economically
more prosperous for all, especially the least well-off, and (c) above all, the
NAP would be a moral basis by which to govern society. Hence libertarianism is
only “unrealistic” presently because the majority of individuals do not
understand or support it, but, given the huge cultural changes that have
occurred in society over time (e.g., attitudes about slavery, women, and
homosexuality), this too could change.

To be a libertarian means to open your eyes to all that is wrong with the state
and to open your mind to the fact that there is a much better alternative.
Hopefully this paper has helped.

