[preface]
= Preface

In non-technical terms, the libertarian is simply someone who is against
the use of force against peaceful people in civil society. You would
think that this would be a universally accepted idea but, as will be
discussed in greater depth in this paper, to believe in government as we
know it is to be at odds with this idea.

The vast majority of people in the world today live under some form of publicly
organized government, which hereinafter I’ll call the “state.”  
footnote:[All references to the “state” in this paper include all arms of the
state: the legislature, executive, judiciary, bureaucracy, agencies, etc. While
they each have different functions, substantively they are all funded in the
same manner, they all have the same inherent characteristics and they are all
responsible for appointing one another and/or working together. The differences
among these different arms of the state are trivial compared with the
differences between how the state acts and how private citizens act, which is
one of the key points of this paper.] Most people believe we should live under
state rule, whether they are classical liberals, communists, conservatives,
fascists, liberals, Marxists, neoconservatives, Progressives, Randians,
socialists or any other flavor, all of whom hereinafter I’ll call “statists.”
They simply differ in their views on what powers the state should possess.

Nevertheless, statists of all flavors often react quite strongly to the
suggestion by libertarians that a society without a state, operating on a
purely free market, voluntary basis, would be a more just and efficacious
society. I believe this reaction results from three categories of errors
by statists: first, they don’t fully comprehend the nature of the state;
second, they don’t fully comprehend the nature of the free market; and
third, they subscribe to certain myths about libertarianism and how a
stateless society might work. That they make these errors is not
surprising, since for the most part their education has been in
institutions where no one asks the question “What is the true nature of
and justification for the state?” and there is very little discussion
about problems with and alternatives to the state.

Given these defects in statists’ understanding of this area of political
philosophy, what I propose to do in this paper is expose some common
myths about both the state and libertarianism. Hopefully this will
facilitate a more critical view of the state and more openness to the
ideas of libertarianism.

Before going further, it’s worth noting that, in discussing how society
should be organized and how individuals should interact with one another,
there is often a distinction drawn between using “utilitarian” principles
and “moral” principles.

Utilitarianism is concerned with discerning what the correct decision
should be based on what would “maximize utility” for “society.” To pursue
this line of thinking, one has to accept that any particular human who is
charged with making a specific societal decision is able to (i)
appreciate all of the benefits and costs of each alternative course of
action to each of the individuals who compose society, (ii) quantify each
of these benefits and costs in terms of common units of utility, and then
(iii) dispassionately choose the course of action that will maximize
society’s utility, and subsequently enforce that choice.

On the other hand, morality is concerned with discerning what the correct
decision should be based on a standard of good behavior. A “standard”
means something that is universal, i.e., applies to every human. To
pursue this line of thinking, one has to first be able to define an
acceptable behavioral rule that, as a purely technical matter, could
apply to everyone without exception, consistently and continuously.
Second, one has to conclude that such behavioral rule should apply to
every human without exception. On this latter point, if we recognize that
all humans are born equal, in the sense of possessing the same
fundamental biological qualities that make them members of the same
species, then there is no objective rationale to justify regarding one
human as different from another when it comes to defining what
constitutes acceptable behavior. Every human should thus be expected to
treat others and be entitled to be treated by others according to the
same code.

As will be evident from this paper, a number of the common arguments raised by
statists are utilitarian, as opposed to moral, arguments. While I believe that
the fundamental strength of libertarianism is its underlying morality ‒ because
it is based on a technically feasible universal standard of acceptable behavior
‒ and the fundamental weakness of statism is its underlying immorality ‒
because it is based on no such standard ‒ even on a utilitarian basis I believe
libertarianism has much more to offer than statism. In any event, I will
address the relevant statist arguments from both the moral and utilitarian
perspectives, even though I believe the moral argument should suffice.
footnote:[I still believe that there is a role for utilitarian analysis, but
not the one that is usually cited. If economists believe that a particular
outcome would lead to greater benefits (however defined) than the outcome that
would result from individuals acting based on their own preferences, then these
economists should publicize their analysis and use it to try to persuade
individuals to change their decision-making processes. The real problem with
utilitarian analysis is that it is used by statists to justify
[underline]#forcing# individuals to make different decisions, instead of merely
trying to persuade them.]

Finally, there are some upfront stylistic points I should make.

**First** , since in this paper I am contrasting those who support the notion
of a state with those who don’t, I will be using “libertarian” to mean only
someone who argues for a completely stateless society (as I do), also known as
an “anarcho-capitalist,” “voluntarist,” “libertarian anarchist” or
“Rothbardian.”
footnote:[The last term refers to Murray Rothbard, who was the libertarian
historian, economist and philosopher who really ignited modern libertarianism
in the 20^th^ century.]  
There are many people who wouldn’t argue
for a stateless society but who nevertheless label themselves, or get labeled
by others, as “libertarian.” I am not referring to them in any way; in this
paper, they would be “statists.”

**Second**, I appreciate that not all statists think alike. Accordingly,
when I refer in this paper to the assumptions, beliefs and arguments of
statists, I always mean “some” statists, even though I will not bother
using the word “some.” One purpose of this paper is to lay out the
precepts of statist thinking, not the thoughts of every, or any
particular, statist.

**Third** , I have avoided citing too many specific sources in an effort to
try to create a more conversational tone.  Instead, I have included a
Reading Guide at the end which references much of the source material
that provided me with the foundations to write this paper. That said, all
errors of course are mine alone.

**Fourth** , I would encourage you to read the footnotes, which generally
contain additional substantive material or examples, as opposed to just dry
source references. Sometimes that’s where I have my most
fun! 
footnote:[Just checking that you were paying attention.]

It has brought me tremendous pleasure to research and write this paper,
and I can only hope that you as the reader derive at least a fraction of
that pleasure from reading it. If you have any questions or comments that
you would like to send me about this paper or any topics raised (or not
raised) herein, please feel free to email me at TheNAPster3226@gmail.com.

Zack Rofer 

_January 2017_

  
