:sectnums!:
[#reading-guide]
= Reading Guide

I have set out below (in publication date order) a list of the books I have
read on philosophy, economics, history and other subjects which provided me
with the intellectual foundation to write this paper.

However, these books were not my only resources. I have also learned much from
listening to podcasts recorded by, and reading articles written by, a number of
intellectuals whom I highly respect. They include (in alphabetical order)
Walter Block, Don Boudreaux, Jeff Deist, Tom DiLorenzo, Peter Van Doren, David
Friedman, Roger Garrison, Jeff Herbener, Bob Higgs, Hans-Hermann Hoppe, Jörg
Guido Hülsmann, Stephan Kinsella, Peter Klein, Ryan McMaken, Bob Murphy, James
Otteson, Lew Rockwell, Murray Rothbard, Joe Salerno, Thomas Sowell, John
Stossel, Mark Thornton, Walter Williams and Tom Woods.

centered:[* * * * *]

[%hardbreaks]
_The Law_ by Frederic Bastiat (1850)
_No Treason: The Constitution of No Authority_ by Lysander Spooner (1870)
_War is a Racket_ by General Smedley Butler (1936)
_The Road to Serfdom_ by Friedrich Hayek (1944)
_Human Action_ by Ludwig von Mises (1949)
_America’s Great Depression_ by Murray Rothbard (1963)
_Education and the State_ by E.G. West (1965)
_Education Free & Compulsory_ by Murray Rothbard (1971)
_For a New Liberty_ by Murray Rothbard (1973)
_Defending the Undefendable_ by Walter Block (1976)
_The Ethics of Liberty_ by Murray Rothbard (1982)
_Civil Rights: Rhetoric or Reality?_ by Thomas Sowell (1984)
_Public Goods and Private Communities_ by Fred Foldvary (1994)
_Separating School & State_ by Sheldon Richman (1995)
_The Economic Laws of Scientific Research_ by Terence Kealey (1996)
_Secession, State & Liberty edited_ by David Gordon (1998)
_The Rise and Decline of the State_ by Martin van Creveld (1999)
_The Costs of War edited_ by John Denson (1999)
_From Mutual Aid to the Welfare State_ by David Beito (2000)
_Democracy – The God That Failed_ by Hans-Hermann Hoppe (2001)
_The Real Lincoln_ by Thomas DiLorenzo (2002)
_Chaos Theory_ by Robert Murphy (2002)
_The Myth of National Defense edited_ by Hans-Hermann Hoppe (2003)
_The Not So Wild, Wild West_ by Terry Anderson and Peter Hill (2004)
_The Politically Incorrect Guide to American History_ by Thomas Woods (2004)
_The Economics and Ethics of Private Property_ by Hans-Hermann Hoppe (2006)
_33 Questions About American History You’re Not Supposed to Ask_ by Thomas Woods (2007)
_Anarchy and the Law edited_ by Edward Stringham (2007)
_Inclined to Liberty_ by Louis Carabini (2008)
_Hamilton’s Curse_ by Thomas DiLorenzo (2008)
_The Ethics of Money Production_ by Jorg Guido Hulsmann (2008)
_The Case for Discrimination_ by Walter Block (2010)
_More Guns, Less Crime_ by John Lott (2010)
_Great Wars & Great Leaders_ by Ralph Raico (2010)
_Nullification_ by Thomas Woods (2010)
_The Enterprise of Law_ by Bruce Benson (2011)
_The Conscience of an Anarchist_ by Gary Chartier (2011)
_Basic Economics_ by Thomas Sowell (2011)
_Intellectuals and Society_ by Thomas Sowell (2011)
_Race & Economics_ by Walter Williams (2011)
_Rollback_ by Thomas Woods (2011)
_Libertarian Anarchy_ by Gerard Casey (2012)
_Organizing Entrepreneurial Judgment_ by Nicolai Foss and Peter Klein (2012)
_The Great Fiction_ by Hans-Hermann Hoppe (2012)
_South Carolina Civilians in Sherman’s Path_ by Karen Stokes (2012)
_No, They Can’t_ by John Stossel (2012)
_Defending the Undefendable II_ by Walter Block (2013)
_War and Delusion_ by Laurie Calhoun (2013)
_The Problem of Political Authority_ by Michael Huemer (2013)
_Intellectuals and Race_ by Thomas Sowell (2013)
_Environmental Markets_ by Terry Anderson and Gary Libecap (2014)
_Toward a Libertarian Society_ by Walter Block (2014)
_Playing_ by the Rules by Tracey Brown and Michael Hanlon (2014)
_The Moral Case for Fossil Fuels_ by Alex Epstein (2014)
_The Machinery of Freedom_ by David Friedman (2014)
_Anarchy Unbound_ by Peter Leeson (2014)
_Peace, Love, & Liberty edited_ by Tom Palmer (2014)
_Out of Poverty_ by Benjamin Powell (2014)
_Northern Opposition to Mr. Lincoln’s War edited_ by D. Jonathan White (2014)
_Real Dissent_ by Thomas Woods (2014)
_Water Capitalism_ by Walter Block and Peter Nelson (2015)
_We Kill Because We Can_ by Laurie Calhoun (2015)
_Chasing the Scream_ by Johann Hari (2015)
_The Primal Prescription_ by Doug McGuff and Robert Murphy (2015)
_Choice_ by Robert Murphy (2015)
_Wealth, Poverty and Politics_ by Thomas Sowell (2015)
_Private Governance_ by Edward Stringham (2015)
_The Problem with Socialism_ by Thomas DiLorenzo (2016)
_Nature Unbound_ by Randy Simmons, Ryan Yonk and Kenneth Sim (2016)
