== Myth #7: The Free Market Creates An Inequality Problem

Statists claim that state intervention is needed to address the “inequality
problem” which arises in the free market.  This is a misguided claim both
because it is “tilting at windmills” and incorrectly attributes causation.
footnote:[The inequality discussion often swings back and forward loosely
between “income” and “wealth” inequality. However, the two concepts are quite
different. “Income” is one’s earnings in a particular period; “wealth” is the
amount of assets one owns, net of one’s debts. One could have low income in a
period but still own a lot of assets (as many elderly do); alternatively, one
could have high income in a period but own few assets of value. As a related
point, many of the wealthiest, highest profile statists often take advantage of
the terminological confusion in this area to try to appear “socially conscious”
by championing higher income tax rates to fund statist social programs; they
know full well that this is not going to materially impact them because most of
their well-being is tied up in wealth (assets), which are not caught by income
taxes, as opposed to income, which is (also, they have paid tax advisors to
organize their affairs to ensure that much of their income is sheltered from
income taxes). One wonders whether these wealthy statists would, instead,
champion high “wealth taxes” to fund social programs; after all, the success of
these programs is not a function of the specific source of their funding.]

=== Equality Is Impossible

To claim that inequality is a problem implies that if all men do not have equal
income or wealth then there is something wrong in society.

However, no two men have the same physical or intellectual attributes,
nurturing or luck, and there is a wide variety of other differences that can be
important in each man’s economic evolution (such as personal choices, culture
and geography). Accordingly, and assuming no criminal aggression by or against
any man, why should we expect any two men to end up in the same place in terms
of career skills, family, education, health, etc.? If these and other factors
impact what one earns, why should we expect any two men to end up with the same
income or wealth?  footnote:[Statists frequently make the remarkable claim that
inequality can only be due to discrimination. In other words, they assume that,
but for discrimination, every person would end up in the same economic
situation as every other person. Apart from the fact that this wouldn’t explain
inequality between two men of the same class (e.g., two white, heterosexual,
Protestant men), no allowance is made by this argument for the myriad of other
factors that influence where someone ends up in life. This whole area is very
well covered in Thomas Sowell’s book, _Wealth, Poverty and Politics_.]

In other words, inequality is society’s natural state. And, leaving aside
voluntary income and wealth transfers by those with more to those with less,
there are only two ways to change this natural state.

*First*, by physically rebalancing men’s natural attributes or their
developmental environments. Some examples would include taking one good eye
from each person with two good eyes and giving these excess good eyes to the
blind; ejecting the more advanced students from school a few years early to let
the others catch up; and pulling children out of nurturing households and
raising them in less helpful environments.

*Second*, through forcibly taking income or wealth from one person and giving
it to another.

Yet, with respect to either solution, if all men are born equal vis-à-vis each
other, surely no man possesses the right to initiate force against another
man’s body or property? Thus to ensure equality requires acting immorally.

In addition, even if one could, at some point in time, equalize all wealth for
a moment, this doesn’t solve the “Day Two” problem. On the day after
equalization, if, to satisfy their individual preferences, people were free to
trade what they have for what they want, and to build upon what they have,
inequality will immediately arise once again as each individual makes his
unique choices. Accordingly, unless we prohibit free trade and entrepreneurship
by individuals, the entire effort to achieve the prior equalization will have
to be undertaken again and again until eternity. Think of the futile cost,
bureaucracy and intrusion into people’s lives that would entail. Well, welcome
to the modern state!

=== Membership Of Income And Wealth Groups Is Dynamic

Statists define inequality by using categories. They refer to the “top 1%” or
the “bottom 10%,” and track what happens to the income or wealth of those
groups over time. However, those are meaningless statistics because they
represent groups in which the members are constantly changing.  footnote:[There
are other problems with the widely used inequality statistics. For instance,
the statistics often fail to take into account significant cash and in-kind
benefits provided to individuals by the state. Also, by only focusing on
dollars, they don’t measure the much higher level of consumables that can be
bought with these dollars today compared with in the past.]

A person’s income and wealth typically change over time. In a normal career you
would start out with low income and few assets; over time your income might
grow as you progress in your career, and you might start acquiring assets; near
the end of your career, as you retire, your income might drop significantly but
you may still have built up a substantial asset base. Along the way you might
have had some years where you received a big bonus and thus your income would
have spiked upwards, and you also might have spent some time between jobs so
your income would have spiked downwards. Some years you might come into an
inheritance or your stock portfolio or house might increase substantially in
value, so you look wealthier, and some years your assets might be worth much
less, so you look less wealthy.

Thus, at different points of time when inequality is measured, one could be in
the high income group one year but the low income group the next, and similarly
be in the high wealth group one year but the low wealth group the next. Any
particular person who might fall into the “bottom 10%” one year, perhaps early
on in his career, could be in the “middle 10%” in a few years time and may even
spend some time in the “top 10%” before falling back down again later when he
retires or has some bad luck.

Accordingly, measuring income and wealth for categories of people tells us
nothing about what is happening to actual people. For that, one must track the
ups and downs of those actual people. And it is quite logical that people will
move into and out of different income and wealth groups over their lives.
footnote:[This is illustrated in the U.S. by Internal Revenue Service (IRS)
data released in 2014 analyzing the frequency with which actual individual
taxpayers appeared in the top 400 income earner group from 1992-2010. Of the
7,600 tax returns filed over this period (400 highest earners in each year x 19
years), there were 4,024 unique, individual taxpayers, since obviously some
taxpayers made it into the top 400 in more than one year. It turns out that 85%
of these 4,024 individuals made it into the top 400 only once or twice over
that 19 year period, and only 2% (95 individuals) made it into this group 10 or
more times. Other IRS data illustrates similar mobility of specific individuals
over time through the various quintiles of income distribution.]

=== How Much Inequality Is The Problem?

When a statist claims that there is “too much inequality,” the right response
is, “Well then, how much inequality would be appropriate?” The statist cannot
answer this question because there is no answer, or at least no objectively
verifiable answer.

What the statist really means is that the level of inequality he perceives
exists is too high for his taste. Presumably with millions of different
statists there will be millions of different views on this concept. How are we
to reconcile all of these views into a target inequality amount that is
acceptable to everyone? If we can’t define an objective, how can we have a
process to achieve success?


The statist would likely fall back on the democratic process, i.e., the right
amount of inequality is whatever those who hold elected office at any point in
time tell us is acceptable. In other words, this is an entirely arbitrary
target based on the whims of our rulers.  footnote:[It’s even more arbitrary
when one considers that statists’ concerns about inequality seem to stop at
national borders artificially contrived by the state. As libertarian historian
Tom Woods has pointed out, the inequality between the richest and the poorest
in the U.S. is trivial compared with the inequality between the U.S. population
and the populations in many of the world’s poorest countries (e.g., parts of
Africa, and North Korea). If statists truly believe in the morality of forcibly
reducing inequality among humans, they should be in favor of a massive, forced
transfer of income to these poor populations from everyone in the U.S. (and
other wealthy countries), even from those in the lower income quintiles in the
U.S. who are doing much better, relatively speaking, than even the “middle
class” in these extremely poor countries.]

And of course, whatever the target is, as discussed above the only way to move
towards that target is through immoral action, i.e. , the application of force
by some men to other men.

=== How Inequality Arises In The Free Market

All of the above points aside, one of the biggest misconceptions statists
harbor about an economy is how people become wealthy in a free market. This
misconception then causes statists to perceive significant wealth as something
to condemn, which leads to the misplaced concern about income or wealth
inequality.

In a truly free market no entrepreneur can force any consumer to buy his
product. Every transaction is a voluntary exchange: the consumer voluntarily
gives up some of his money in return for the entrepreneur’s product. By
definition the consumer must value the product he receives more than the money
he gives up, otherwise why would he trade?

Similarly, no entrepreneur can force any person to work for him. Every labor
arrangement is a voluntary exchange: the worker voluntarily gives up some of
his time and effort in return for wages. By definition the worker must value
the wages he receives more highly than the time he has given up and the effort
he has made, otherwise why would he work?

This is also true for owners of natural resources and capital: they only
exchange these factors voluntarily with the entrepreneur in return for
acceptable rent and interest/dividends, respectively.

I want to digress for an instant and anticipate an objection at this point from
statists. Statists might argue that a consumer or a worker could be in very
difficult circumstances with no other attractive options, and thus really is
“forced” to buy the product or accept the job offer, as the case may be, and
accordingly these are not voluntary actions. However, this places the fault in
the wrong place. What is forcing the consumer’s or the worker’s hand is not the
entrepreneur who is offering the product or the job. Rather, it is reality that
is responsible for the consumer’s or the worker’s tough situation: it could be
bad luck, bad prior decisions, bad education, etc. The consumer or the worker
can always decide not to purchase the product or accept the job offer; he would
weigh up his predicament and decide whether continuing to look for a different
product or job is preferable to buying this product or accepting this job
offer.

Moreover, the one party to which the consumer or the worker should be thankful
is the entrepreneur who is offering the product or the job. At least this
entrepreneur is giving the consumer or the worker a way to improve his
situation relative to where things currently stand. Consider all of the other
individuals in the economy who are not offering any product to the consumer or
any job to the worker. Surely they are not as noble as this entrepreneur when
it comes to this consumer or this worker? Yet the statist’s ire (and call for
state action) is often levied at this entrepreneur for “overcharging” the
consumer or “underpaying” the worker.  
footnote:[The statist who claims that the entrepreneur is taking advantage of
this consumer or worker by pricing the product “too high” or offering wages
that are “too low” (as if there is some objectively ascertainable correct price
or wage, which is a whole other fallacy) simply illustrates a poor
understanding of how the free market operates. An entrepreneur who prices his
goods above competitive goods or proposes underpaying a worker relative to what
competitors are offering will see his competitors lure away the customer or the
worker, as the case may be.]
footnote:[With respect to the worker whom the statist believes is “underpaid,”
as Austrian economist Don Boudreaux has noted, worker compensation is only half
of the living standards equation, the other half being the cost of living. If
statists want to improve the worker’s situation, why don’t they campaign for
economy-wide low price ceilings on all goods which would allow the worker to
buy more with his income, instead of campaigning for action by the state to
raise the worker’s wages? That would be a way ostensibly to improve the
worker’s living standards without targeting the one party ‒ the employer ‒ who
is actually providing benefits to the worker. The reason this is not done is
because (a) people instinctively know that price ceilings create shortages of
goods, although for some reason these same people don’t see that price floors,
like the minimum wage, create surpluses of workers, thereby taking some
bargaining power away from the least productive workers, and (b) the employer
is a more convenient target to attack and many statists harbor the Marxist
belief that all employers oppress all workers. This is despite the fact that,
in the U.S., about 95% of workers are paid more than the minimum wage; wouldn’t
true oppressors only pay exactly what the state demanded and not a penny more?
Boudreaux has also suggested that if statists really believe they can just
“will” higher pay for workers through legislation without any adverse side
effects, why not just ban part-time work? If everyone had to work full-time,
they’d all get paid so much more...]

In any event, to return to the main topic, now consider how an entrepreneur
runs his business in the free market.  He engages in voluntary trades with the
owners of productive factors – workers, owners of natural resources and capital
suppliers – to acquire use of these factors. He then organizes these factors in
a process to produce goods for which consumers will voluntarily pay the
entrepreneur if the goods satisfy their wants. If the entrepreneur can purchase
and organize the productive factors at a cost lower than the price at which
consumers are willing to buy his product, he makes a profit.  footnote:[Of
course this is a gross simplification of the complexity and risk in the
entrepreneurial process. An entrepreneur must compete with others for
productive factors and the consumers’ money, and he must keep up with new
technologies and other changes in the overall environment in which he operates.
If he stops innovating and satisfying consumers he will eventually go out of
business.]

Is it wrong for the entrepreneur to seek a profit? As noted earlier in this
paper, since no human is self-sufficient, every human must produce what he can
and trade it for the product of others who are able to satisfy those of his
needs that he cannot satisfy by himself. A worker sells his time and effort for
wages and uses those wages to buy what he cannot produce for himself; a land
owner sells possession of his land for rent and uses that rent to buy what he
cannot produce for himself; a capital supplier lends or invests his capital for
interest or dividends, respectively, and uses that interest or those dividends
to buy what he cannot produce for himself. Similarly, an entrepreneur employs
his expertise for profits, and uses those profits to buy what he cannot produce
for himself.

How does an entrepreneur in the free market become wealthy? He can only become
wealthy if he can consistently satisfy the demands of workers, natural resource
owners, capital suppliers and consumers and, while doing so, make a profit. If
we freeze the cost structure to make the key point, the only way an
entrepreneur can become wealthy is if he consistently delivers to a large
number of consumers a product for which they are voluntarily willing to part
with their money. In other words, only by satisfying other humans’ wants can he
become wealthy.

Why is this worthy of any disdain? The entrepreneur is in the business of
organizing resources to satisfy human wants, and if he does a great job he
becomes wealthy. No free market advocate argues that the entrepreneur is a “do
gooder”; he is in business to make a profit, but the fact is that in a
voluntary economy he can only make a profit if he makes his customers happy.
Conversely, those who cannot make their customers happy lose money and do not
end up as wealthy, perhaps even living in relative poverty.

This is how inequality of wealth arises in the free market: those who have done
a better job for customers end up with more wealth than those who have done a
poorer job.

With one exception discussed below, the history of entrepreneurs attaining
great wealth is the history of those who have best satisfied consumers’ wants
on a large scale. They have brought new products at affordable prices to the
mass market, raising the living standards of many individuals in the economy.
footnote:[In this respect the wealthy perform a valuable testing function for
society. When innovations are first developed they are relatively expensive to
produce, but the entrepreneur needs some way to test his innovations in the
consumer market.  Wealthy consumers, since they can afford expensive products,
constitute the “test laboratory” for entrepreneurs to try out their
innovations. Those innovations that pass this test then become the focus of
entrepreneurs’ efforts to bring down production costs to create mass market
appeal.]

When one looks at a wealthy entrepreneur one only sees his wealth – meaning the
assets that define his living standard ‒ but that fails to appreciate that his
ability to acquire these assets was bestowed upon him voluntarily by the many
customers whose lives or businesses were bettered by purchasing his products.
Through the sale of his products on the market in no sense has the entrepreneur
“taken” anything away from those who have less – he has exchanged his products
for customers’ money – and therefore he does not deserve to be forcibly
required by the state to “give it back” through taxation or other means.

The critical point to appreciate is that “wealth” is not something that
descends from heaven and simply cries out for distribution among the
population. Too often statists just assume that wealth has always been there
and will always be there, and the only point for discussion is how to
distribute it. Statists would do better to consider how wealth is actually
generated. The default for most of human existence has been absolute poverty
and, if no entrepreneur got up in the morning to produce goods in demand,
poverty is where we’d all be headed. In other words, wealth doesn’t just exist,
it has to be created by entrepreneurs in a complex process fraught with risk,
and requires these entrepreneurs to have the freedom to organize their
activities to produce goods desired by consumers, and to be able to keep any
resulting profits as the reward for taking the risk to create such goods.
footnote:[The statist view here is at least partially a consequence of
subscribing to Keynesian economics, which pays no attention to differences in
entrepreneurial activity but simply looks at the economy as a mass of uniform
firms all doing the same thing.]

Anything such as the state which impinges on entrepreneurial freedom and
incentives, and thus the creation of wealth, can only suppress human well-being
since it means fewer quality goods at affordable prices to satisfy human wants.

=== Focus on Absolute, Not Relative, Poverty

In focusing on inequality statists are wrongly concerned with relative poverty;
as noted above, there will always be those who are more and those who are less
wealthy when individuals have different skills and luck in life.  Moreover,
relative poverty data tells us very little about someone’s living standards. If
A earns $4 million a year and B earns $500,000 a year, the statist concerned
with inequality would complain that A is earning eight times what B is earning
(8x!); yet B is not exactly destitute. Now assume that five years later A earns
$10 million a year and B earns $1 million a year; the statist focused on
inequality would complain that things are measurably worse because inequality
has widened, since now A is earning 10 times what B is earning (which is
clearly a sign of the coming Armageddon).

Thus it is more important to focus on the living standards of the least
well-off, or absolute poverty. Living standards are a function of the quantity,
quality and price of products available which satisfy consumers’ needs.
Absolute poverty has declined – that is, living standards of the least well-off
have increased – dramatically thanks to entrepreneurial activity; the poorest
individuals in the U.S. live better than European royalty lived a couple of
centuries ago, due to the fabulous, plentiful and affordable innovations
produced by entrepreneurs in search of profits.  footnote:[However, even
relative poverty has been reduced by entrepreneurial activity. For want of a
better term, “stuff” inequality has declined the most in the countries with the
least state intervention (which is another way of saying the most free
entrepreneurial activity). For instance, a couple of hundred years ago in
England the poor traveled barefoot while the rich traveled fully clothed and in
horse-drawn carriages; today the poor travel fully clothed in modest cars and
the rich travel fully clothed in fancy cars. In addition, inequality as
measured by the widely used Gini coefficient is much less dramatic in the
countries with less state intervention than in those with more.]

=== How Inequality Can Arise With A State

There is, however, a form of wealthy entrepreneur who is deserving of our disdain. He cannot exist in a free
market but he is quite common in the statist economy.

This is the crony capitalist: the entrepreneur who gets assistance from the
state in generating his wealth, also known as the “political entrepreneur” (as
opposed to the “market entrepreneur,” who operates without state assistance).
Such assistance can be in the form of monopoly or monopoly-like privileges
(through state licensing), R&D subsidies, special tax privileges, protective
tariffs, newly created money, etc.  footnote:[Statists lament the fabulous
wealth of those in financial services (“Wall Street”), but that is mostly a
function of state privilege. The state is a central planning monopolist in the
direct and indirect creation of new money, which is price inflationary when it
finally works its way through the economy, but the state directs much of the
new money to the financial sector first.  Those in this sector therefore get to
buy products with the new money before all the newly created money has filtered
into the rest of the economy, and thus before price inflation sets in, which is
highly beneficial to these early recipients. On the other hand, the average
citizen, who is the last to get the new money, has had to buy higher-priced
goods in the meantime with his prior income. In this way, state privilege
widens inequality.]


Since every action by the state is coercive, any of these forms of assistance
means the state has either coercively taken resources from another person and
bestowed them on the political entrepreneur, or has coercively restricted the
political entrepreneur’s actual or potential competitors from competing as
vigorously as they might.  As noted earlier, such political entrepreneurs are
able to obtain this assistance through intensive lobbying of the state, and in
effect are paying to rent the state’s coercive powers.

It is somewhat obvious to note, but statists often overlook, the fact that if
there were no state there would be no coercive powers to rent, and thus no
political entrepreneurship. Statists prefer to believe that crony capitalism is
a problem caused by businesses, not the state, but of course there are two
parties to every instance of crony capitalism. This is an issue which flows
naturally from the very existence of the state, and a proper survey of economic
history will reveal that this is an issue as old as the state itself. As long
as the state exists, each business’s calculus will be “If I don’t reap the
benefits of the state’s coercive powers, my competitors will.”

Efforts to regulate crony capitalism out of existence have always failed, and
will always fail, because they attack the symptom, not the cause.

[centered]#* * * * *#

The implication of the statist myth that the free market creates an inequality
problem is that the state is able to provide an appropriate solution. However,
all that happens when the state coercively imposes a “solution” in this area is
that we shift from inequality of income/wealth to inequality of power. That is,
those at the state who would construct this “solution” would be wielding
significant power over ordinary citizens, and either their personal biases or
incompetence will prevail, or special interests will lobby state personnel
aggressively to rent the state’s coercive powers to influence the alleged
solution.

Either way, while the outcome might (temporarily) reflect less inequality of
income/wealth, it will definitely reflect an enormous inequality of power. Who
is to say that this is a reasonable trade-off?

And since such a solution would rely on one man coercing another, we know it
cannot be a moral solution.
