== Austrian Economics

Technically speaking, economics as a science is supposed to be “value-free,”
meaning it doesn’t seek to prescribe what economic policies a society should or
should not adopt; rather, it simply outlines what the consequences would be of
adopting specific policies. On the other hand, political philosophy is
prescriptive and thus does seek to suggest a set of principles on which society
should be based. So, for example, economics would explain that an increase in
the minimum wage will cause unemployment for workers whose productivity is
lower than the new wage level and a higher wage for certain other workers, and
leave things at that. It would be up to political philosophy to argue whether,
given this outcome, an increase in the minimum wage should or should not be
adopted.

Libertarians favor a school of economics dating from the late 19^th^ century
known as “Austrian economics” (since the early founders were all from Austria).
Austrian economic analysis explains that intervention by the central planners
at the state can only hamper the ability of entrepreneurs to maximally satisfy
consumers’ preferences.  footnote:[Technically someone could subscribe to
Austrian economics but still be a statist, as that person could agree with the
conclusion from Austrian economic analysis but believe that there are higher
priorities than maximizing the satisfaction of consumer preferences.]

Austrian economics differs substantially from Keynesian economics which, as
noted earlier, is the statist’s preferred school of economic thought.
footnote:[Some statists claim to be monetarists (the so-called “Chicago school”
of economics), but monetarism is so close to Keynesianism compared with
Austrian economics that monetarists may as well be Keynesians for all practical
purposes.] Keynesian economists are famous for classifying into uniform
categories millions of uniquely different individuals, and things comprised of
countless different components, all of whom or which are continuously changing,
such as “consumers,” “labor,” ”the economy,” “the environment,” “the financial
sector,” “the money supply” or “exports,” and then theorizing how these
allegedly uniform groups or things act, or interact with one another, and how
the state can forcibly improve such actions or interactions. To lend faux
scientific credibility to their analyses, Keynesians try to reduce human
activity to a series of mathematical formulae which, through their intricate
econometric models, are used to predict with utopian accuracy how an economy or
these groups will respond to state action; when reality doesn’t conform to
these models, Keynesians question reality, not their models. If the economy is
not in equilibrium the Keynesian regards this as a problem. To Keynesians, the
state has the central role in the economy, and the purpose of economics is to
prescribe what the state should do to get the economy “back” into equilibrium.

Unlike Keynesian economics, Austrian economics doesn’t use aggregate
mathematical models to quantitatively or temporally predict economy-wide
outcomes. This is because these outcomes cannot be modeled, since the economy
is simply the aggregate of millions of unique consumers and entrepreneurs
interacting continuously based on their ever-changing subjective preferences
and subjective assessments of the future. Rather, Austrian economics is focused
on using the logic of purposeful human action and the concept of subjectivism
to examine cause and effect at the level of the individual consumer and
entrepreneur. Instead of looking at all firms as uniform actors and the economy
as a single entity, Austrian economics takes into account differential impacts
at different stages of the consumption and production cycles. Austrian
economists focus on the market process as opposed to the market equilibrium,
and are not troubled by the fact that the economy is in a perpetual state of
disequilibrium because everything is constantly changing; this is the
inevitable outcome of purposeful human action amid uncertainty.

The purpose of Austrian economics is not to explain how to guide the economy to
a utopian equilibrium, but to describe how humans will react to changing
circumstances and to inform us about the less than obvious trade-offs involved
when humans make economic decisions. In this respect, Austrian economics
employs the concept ‒ first articulated by 19^th^ century French economist
Frédéric Bastiat ‒ to focus not just on what is seen but on what is unseen when
state interventions occur in the economy.

Austrian economics is also much simpler and more intuitive to understand than
Keynesian economics. Austrian economists like to say that Keynesians have
“physics envy,” since they are fixated on defining everything via a fancy
model. In contrast, Austrian economists are well read in history and philosophy
and seek to understand the reality of purposeful human action, not the fantasy
world of mathematical models.

There are other substantial differences between Austrian and Keynesian
economics, in areas such as money, heterogeneity of capital, savings and
investment, anti-trust, entrepreneurship and the business cycle, just to name a
few. A full comparison of the two economic schools is beyond the scope of this
paper; suffice to say that it is difficult to fully appreciate the economic
benefits of libertarianism over statism without a good understanding of
non-fiction (i.e., Austrian) economics.  footnote:[For a detailed comparison of
Keynesian and Austrian economics, the http://libertyclassroom.com online
educational series produced by libertarian historian Tom Woods includes a
course entitled “What’s Wrong With Textbook Economics” taught by Professor Jeff
Herbener. In that course Herbener takes one of the standard Keynesian
textbooks, _Economics_ (written by Paul Samuelson and William Nordhaus), and
provides a chapter-by-chapter Austrian critique. Alternatively, for an
excellent introduction to Austrian economics I can strongly recommend Robert
Murphy’s book, _Choice_.]

