== Economics 101

To better understand the difference between the free market and a statist economy, we must first understand
economic activity.

=== Entrepreneurial Activity

As noted above, the purpose of an economy is to allocate productive resources –
natural resources, labor and capital goods – to maximize the satisfaction of
human wants. No one can produce all of his own needs and thus humans must
trade; a person produces what he can and trades this product with others who
are producing what he wants but cannot produce for himself. However, productive
resources are scarce relative to human wants.  Thus choices have to be made in
organizing these scarce resources to try to satisfy those wants that are ranked
most highly by each person. The key question is, how can we know which wants
are ranked most highly so that we can then try to organize resources
accordingly?

Those who organize these scarce resources are society’s entrepreneurs. Their
function is to try to anticipate human wants, bid for and organize the
necessary scarce resources to create goods to satisfy those wants, and then
price these goods appropriately and deliver them to consumers.  footnote:[This
is a bit of a simplification of the structure of production. There are
entrepreneurs who produce intermediate goods to satisfy the demands of other
entrepreneurs who are closer to the end consumer. However, ultimately it is the
demands of the end consumer that drive the whole production chain.]

Some entrepreneurs will be successful and thus will make profits when
sufficient customers voluntarily pay enough for these entrepreneurs’ goods to
more than cover their costs of acquiring resources. Other entrepreneurs will be
unsuccessful and thus will make losses if there are insufficient such
customers.

The key point, however, is that entrepreneurs cannot force their products on
consumers; in a truly free market the consumer is king and he votes with his
dollars every minute of every day. Those entrepreneurs who make profits will be
able to purchase further resources, and those who make losses will have to
yield resources, which is beneficial for society as it means resources are
flowing to those entrepreneurs who are best satisfying actual wants. Since
society is more prosperous the more human wants are being satisfied, profits
are not something we should disdain but, rather, something we should embrace.
The lure of making profits is what draws entrepreneurs to take risk with their
capital and time to try to find a way to satisfy customers, and losses are a
way to discipline entrepreneurs who make mistakes in this process.

An entrepreneur’s task is very difficult. The knowledge of what his customers
want ‒ in terms of price, quality, location, etc. ‒ is not available in any
central database, and there are millions of customers in the economy, each
with his own specific wants. Entrepreneurs therefore take their cues from
signals given by their customers: if a customer is voluntarily willing to pay
for a good at the price proposed by the entrepreneur then the entrepreneur
knows he is satisfying a want; if a customer is not willing to transact then
the entrepreneur knows he is not satisfying a want. The entrepreneur tries to
anticipate customer demand but keeps experimenting every day, as there are
continuous changes in demand, competition, and the availability, quality and
pricing of resources.

=== The Impact Of The State

Now consider the nature of the state. The state comprises a small group of
people who have enormous power in the economy through their ability to
coercively tax, subsidize and regulate other people. Taxation is the forcible
taking of money from those who possess it, and who would otherwise have spent
these funds in accordance with their individual wants. A subsidy is the
transfer of the money seized through taxation to those individuals in the
economy whom those at the state believe should have this money instead.
Regulations coerce individuals to do or refrain from doing things with their
bodies and personal property as those at the state decide, instead of as
decided by these individuals themselves. Accordingly, through legislation,
those at the state can forcibly redirect resources, funds and efforts in the
economy as they see fit.

However, those at the state cannot possibly gather the relevant knowledge that
entrepreneurs can gather in terms of individuals’ wants, competition and the
availability, quality and pricing of resources. This is because state personnel
are not in the “flow” of signals given to entrepreneurs every minute of every
day by customers, competitors and resource owners.

Moreover, as noted earlier in this paper, unlike entrepreneurs those at the
state do not risk their own capital when they act, and thus they do not have
the appropriate profit incentives to get things right nor the same discipline –
personal financial loss – to try to avoid making mistakes.

In fact, those at the state have very different incentives than satisfying
individual consumers’ wants in the economy. Given the awesome coercive powers
they exercise, state personnel are intensively lobbied by special interest
groups (e.g., businesses, unions, industries, environmental groups, etc.) to
exercise these powers in favor of these groups. In return, these groups offer
state personnel such things as electoral support, “freebies” or future private
sector positions (this is called “crony capitalism”).  footnote:[It’s not
necessary to attribute any bad intentions to state personnel to support this
conclusion. All humans react to irresistible incentives within their chosen
careers. What’s important when comparing the free market to statism is to
recognize all relevant incentives at play, and consider the impact of these
different incentives.]

Such groups seek tax privileges, subsidies, protection from competition, etc. ,
all of which are to the detriment of consumers because they drive up the price
of goods, restrict their availability and/or stifle innovation. Consumers are
never as organized as special interest groups because consumers are a larger
and more diverse group with fewer individual dollars at stake than is the case
for special interest groups; accordingly, consumers cannot compete in the
lobbying game.  footnote:[This is known as “concentrated benefits and diffuse
costs.” For example, successfully lobbying for a particular regulation may
yield a particular firm $100 million in incremental revenues from consumers,
and thus there is a real benefit to the firm in engaging in aggressive
lobbying. If these benefits are extracted from five million relevant consumers,
that’s only $20 per consumer. Thus no consumer will have any reason to spend
time and money to look into this particular matter nor to try to counteract
it.]

Another important contrast to make between the state and the free market is how
they reconcile different interests. In the free market, if one consumer prefers
Coke and another prefers Pepsi, both consumers’ wishes can be accommodated:
Coke will produce and sell to the first consumer and Pepsi will produce and
sell to the second consumer. However, with the state, only one of these two
consumers can be accommodated at a time because the state forces a
“one-size-fits-all” policy on the population. If one consumer prefers policy X
that is campaigned for by party A, and another prefers policy Y that is
campaigned for by party B, whichever party wins in the election will dictate
which consumer will be satisfied and which consumer will lose out. To use a
Coke/Pepsi analogy, under statism we would all vote on Coke or Pepsi, and if
Coke gets the most votes then Pepsi would be outlawed and everyone who wanted
to drink soda would have to be satisfied with Coke.

For all of these reasons, the state can be said to comprise a relatively small
group of people using coercion to reconfigure the economy contrary to how it
would be configured if people and resources could flow naturally to maximally
satisfy individuals’ wants. Hence, by definition, prosperity for an economy is
reduced by state intervention.

Of course this is all very dynamic. The tendency of each individual in the
economy – consumer and entrepreneur – is to adjust to each state intervention
in the direction of their actual preferences. Thus, following an intervention,
consumers and entrepreneurs will try to get resources flowing the way they
would naturally flow but now subject to the constraints of the new state
intervention and/or any adverse consequences. This is because individuals’
wants cannot be changed by those at the state; the state can only impact the
ability and priority of the economy to satisfy these wants (this is like water
always trying to find the cracks in a rock).  footnote:[In the extreme cases
where the state actually outlaws a product consumers want, all that happens is
that a “black market” develops and transactions move “underground” at higher
prices and with less oversight than would otherwise have been the case, e.g.,
narcotics today, and alcohol during Prohibition. In fact, “black market” is
really the statist’s pejorative phrase for a free market that has been
outlawed.]

Once those at the state realize how the private sector has adjusted to try to
satisfy actual preferences, they feel compelled to implement more interventions
to try again to re-direct resources in the way they want. Similarly, once those
at the state observe the adverse consequences resulting from their prior
interventions (although they rarely confess to appreciating the link), they
feel compelled to implement more interventions to try to address those
consequences. Then the private sector adjusts again and/or more adverse
consequences arise, and then the state intervenes again.

This is how problems arise in the modern economy. Statists don’t like the
choices consumers and entrepreneurs are making, so they exclaim “The free
market has failed!” and then the state intervenes. This causes new artificial
problems and then statists exclaim again “The free market has failed!” and
argue for more intervention.

It would not be an exaggeration to claim that all enduring (as opposed to
temporary) economic problems in modern society are demonstrably traceable back
to state intervention. Relative to a free market there are fewer goods
available and those that are available are more expensive; there are fewer jobs
available; the purchasing power of money and the benefit from traditional
savings are lower; capital accumulation is lower leading to less innovation and
lower sustainable economic growth; and we have economy-wide business cycles,
and the more the state intervenes the more frequent these cycles and the
greater their intensity (high to low).  footnote:[That these economic problems
are directly attributable to the state can only be fully appreciated with a
good understanding of free market economics, known as “Austrian economics,”
which will be discussed briefly below.]


The state is also responsible for broader social problems: the state creates
intra-societal conflict because different interests aggressively compete to
rent the state’s coercive powers to use against others; and there is more
inter- societal conflict because of state-initiated or state-provoked war.

Statists only look at the symptoms of a perceived economic problem and conclude
the free market has failed.  They don’t dig deeper to understand the root
causes or consider the logical fallacy behind their conclusion. By its nature,
the free market – as defined above – can only naturally act to try to maximize
the satisfaction of human wants. On the other hand, as discussed above, the
state can never be as efficient towards this end as the free market.

To be clear, free market advocates do not claim that the free market is a
perfect solution. It cannot be perfect because the combination of human
imperfection and scarce resources means we can never satisfy all human wants
simultaneously. Rather, free market advocates claim that if the objective is to
maximize the satisfaction of human wants, the free market is more effective
than state intervention. The free market, through the continuous
experimentation of millions of entrepreneurs, represents not one but countless
possible solutions to the problem of allocating scarce resources to satisfy
human wants. On the other hand, the state represents only one possible
solution. Thus we should not think of the comparison as the free market vs. the
state but, rather, as the comparison of many experimenters vs. one.

To think of this another way, if an entrepreneur in the free market fails to
adequately provide a solution to consumers’ wants, other entrepreneurs tend to
enter the market and try to arbitrage away the imperfection (meaning improve
upon this entrepreneur’s shortcomings). However, when the state fails to
adequately provide a solution to consumers’ wants, because the state is a
coercive monopoly there is no one who can legally try to arbitrage away the
state’s imperfection.

Finally, in addition to these utilitarian observations, it bears repeating
that, due to the absence of coercion, the free market is also the only moral
solution.
