== What Is The “Free Market”?

=== Why Is This Relevant?

One might ask why I regard the free market, which appears to be merely an
economic concept, to be relevant to a discussion of the state, which at first
blush could be conceived of as a purely a political concept.

To survive and flourish, humans have wants that must be satisfied, e.g., food,
shelter, clothing, health care, education, leisure, etc. The only way to
satisfy these wants is to take naturally occurring resources, mix them with
labor, capital equipment and managerial skill, and produce the appropriate
goods. However, there are never enough resources to satisfy all human wants
simultaneously. Thus society’s central dilemma is how to allocate scarce
productive resources to maximize the satisfaction of human wants; this is an
economic question. Humans must purposefully organize themselves and interact
with one another in society to perform this productive function, and human
organization as a society is ultimately a political question. Thus politics and
economics are integral to each other.

While there are many different spectrums that could be used to analyze human
organization, the one that is most critical to understand is the liberty
spectrum: at one end, the principle is one of voluntary human interaction,
where liberty is the prevailing norm; at the other end, human interaction is
coerced, where liberty yields to force.

Since the state, through its passage and enforcement of legislation, is a
coercive entity, it belongs at one end of the spectrum. The absence of a state,
allowing all human interaction to be voluntary, is at the other of the
spectrum.  It is when economic decisions are made within this latter setting
that I use the term “the free market.” footnote:[In libertarian terms this is
called “anarcho-capitalism.” The reference to “anarchy” denotes the absence of
a coercive state, not the absence of order; the two are very different things,
as will be discussed later in this paper.]

=== We Don’t Have A “Free Market”

What statists fail to comprehend is that when libertarians talk about the “free
market” they mean the complete absence of the state (at least in terms of
impacting any economic decisions). Accordingly, in any society in which a state
exists there cannot be a “free market.”

Hence while statists like to point to perceived problems in any contemporary
economy as evidence of the shortcomings of the “free market,” the libertarian
response is that, since there is a state, there is no “free market,” and thus
the problems must instead be caused by one of three other factors: human error;
scarcity of resources; or state intervention.

No political system can eliminate human error or the scarcity of resources.
They are natural features of our world, although (as will be discussed later in
this paper) the presence of a state can exacerbate these two factors. On the
other hand, state intervention is entirely of man’s own making and (as will
also be discussed later in this paper) is usually the cause of most of modern
society’s enduring problems.

When a perceived problem in the economy arises, statists always argue that the
state needs to intervene because “The free market has failed.” Leaving aside
the fact that, by definition, if there is a state to intervene then there is
not a “free market,” the statist claim raises the question, “failed” in what
sense? The free market is nothing more than the aggregate of the daily
interactions of millions of entrepreneurs and customers each transacting
voluntarily in accordance with their preferences. The free market cannot “fail”
or “succeed,” it can only operate.  However, since each transaction in the free
market is voluntarily entered into by two parties, by definition both parties
must be expect to be satisfied with the outcome, and thus each transaction must
be “a success” ex ante.  footnote:[For instance, if A pays $500 to B for his
television, prior to the trade A must value the television more than his $500,
and B must value the $500 more than his television, otherwise, why would they
transact? Only voluntary transactions can be “win- win,” since they satisfy the
double coincidence of wants.]

The reality is that what statists mean when they say “The free market has
failed” is that the millions of voluntarily transacting entrepreneurs and
customers have failed to transact in the way these statists want them to act.
However, what gives statists the right to prioritize their view on how
entrepreneurs and customers “should” act, and to advocate for coercive state
intervention to enforce these priorities?
