== Myth #4: The State And Its Personnel Deserve Our Support

=== Double Standard

Before tackling this myth, it is worth noting that not only do statists hold
state personnel in high esteem, they are incredibly tolerant of their errors.
Private sector personnel are held to a much higher standard.

For instance, national defense is widely acknowledged by statists as one of the
core functions of the state. The U.S. federal government confiscates hundreds
of billions of taxpayers’ dollars per year to spend on national defense, and
maintains military bases, ships and spy networks both in the U.S. and around
the globe. Yet when the U.S. homeland was attacked in 2001 ‒ when the state
failed in its core function, despite all of its massive expenditures and
manpower ‒ the state and its key leaders soared in popularity as people rallied
behind the federal government in general and the president in particular. So
too when the Japanese navy attacked the U.S.  naval base at Pearl Harbor in
1941.

Imagine, however, if you had hired a private security firm to protect your home
and family, and a criminal attacked the house, killing members of your family.
Do you think that if you were asked about this security firm the next day you
would express incredible pride at having contracted with this firm and pledge
to support it going forward, no matter what the cost? I would posit that, after
working through your grieving period, the first thing you would do is find
another security firm, since this one clearly failed at its core mission.

More generally, the state is legendary for highly documented and deplorable
inefficiency, service standards and corruption, yet statists refuse to hold
those at the state to the same exacting standards to which they hold those in
the private sector. In the private sector, if people buy a product with the
slightest defect, at a minimum they demand a discount, an exchange or a refund,
but they may also decide not to buy from that vendor ever again.  Yet with
government, even when there are gross defects in service, people just shrug and
say “What else can you expect?” and vainly hope that at the next election in a
few years time they can vote in someone better.  footnote:[As libertarian
economist and philosopher Walter Block has noted, there are over 30,000 deaths
each year on state-managed roads. Imagine if there were this many deaths on
private properties, such as in malls, parking lots or department stores. There
would be public outrage, a loss of confidence in the managers of these
properties and calls to do something about it. Yet there is virtual silence
from the public about the state’s appalling road management.]

Statists argue that the state should regulate every industry, yet whenever a
problem arises in a highly regulated industry ‒ such as financial services,
health care/insurance or education ‒ this is seen as a failure of the industry,
not of the state; in fact, statists then argue, simplistically, that the
problem was that there was insufficient regulation. It never seems to occur to
statists to ask whether the problem is inherent in the notion of the state
itself as a regulator, and whether there are better alternatives.

If statists believe that the state is the answer to what they perceive as
“failure of the market,” then why do they not believe that the market is the
answer to the failure of the state?

For a different take on the notion of a double standard, consider that many
statists are comfortable with the fact that states tend to prohibit private
citizens from owning and carrying firearms, yet the state’s personnel are
allowed and, in some cases, required, to carry firearms. This doesn’t strike
many statists as a double standard but, by any definition of that phrase, it
surely must be. If all men are born equal, with the same right to provide for
their own defense, how can this double standard be morally justified?
footnote:[Perhaps by one of the Tooth Fairy Theories?]

Now let’s consider some reasons why the state and its personnel do not deserve
our support.

=== Public Service?!

As one steps back and considers what it is that state personnel actually do –
force other people to do things they don’t want to do – one wonders why state
personnel are accorded so much respect, and why “public service” is so
venerated.

The phrase “public service” is itself a misnomer. The politician is not
“serving” the public; he is ordering the public around, including ordering them
( via taxes) to pay his salary and purchase his products under the threat of
involuntary incarceration. Contrast this with those in the private sector, who
actually do serve the public by offering up products for purchase and only
getting paid if customers see sufficient value in what is offered up to
voluntarily part with their money.

It is somewhat surreal that one person would hold in any esteem another person
who chooses to forcibly take property from others and tell them what they can
and cannot do with their bodies and property, threatening them with punishment
if they don’t comply. Such a person in any other context (e.g., the Mafia)
would receive our severe opprobrium. Yet statists actually laud state personnel
on the basis that they are doing wonderful things for others in society.
footnote:[Not to mention (but I will) the fact that since those at the state
can prohibit peaceful individuals from doing relatively mundane things with
their person and property, such as opening a business, renovating a house,
etc., state personnel can and do extort favors from private individuals in
return for not enforcing these prohibitions.]

To pick one example, namely, welfare, why is it laudable and compassionate for
A (the state worker) to force B to send his money to C? If A wants to help C he
could give of his own resources or he could try to convince others of the merit
of voluntarily giving of theirs. Either of those activities would be worthy of
great respect. But threatening B with incarceration if he doesn’t send money to
C is worthy only of scorn. This “ends justify the means” approach is not only
immoral ‒ in the sense that it admits that some men are entitled to coerce
others ‒ it is also very easily abused. Who is to say that A will properly
define whether C is in genuine need according to some objective standard, as
opposed to a standard that benefits A’s career prospects?




=== The State Is An Imposed Monopoly

Statists will constantly warn about the dangers of monopolies, as they
correctly understand that a monopoly leads to higher prices, lower quality and
less innovation because the absence of a competitive threat means the
monopolist does not have the incentive to do better.

Yet statists don’t stop to consider that, while all of this is demonstrably
true, the only actual monopoly that exists is the state, which they support.
The state effectively prohibits any competition for the services it provides,
such as regulation, policing, defense, courts, etc.  footnote:[Strictly
speaking there are private sector security firms and arbitration tribunals
operating in parallel with the state’s police and courts, respectively.
However, taxpayers have to pay for the state’s provision of these services even
if they choose to use private sector alternatives. Thus the total cost to a
taxpayer of using these alternatives is significantly higher, making for an
uneven playing field (and only the well-off can afford to use the generally
better private sector alternatives). The state also coercively limits the
activities of private sector security firms.]

In addition, through taxation and compulsory fees, the state tells you what you
will pay for its services.

In contrast, there can be no monopoly in a truly free market because (a) new
entrants are always free to enter if the incumbent’s pricing, quality or
offerings aren’t properly satisfying consumers, and (b) consumers can simply
stop buying from the incumbent, thereby denying it the cash flow it needs to
survive.

However, the state can prohibit competition from new entrants through coercive
regulatory legislation, and through coercive tax legislation can force
taxpayers to pay for its services (or those of its designated supplier) even if
taxpayers don’t want to consume these services.

Thus the only sustainable monopolies that have ever existed have been either
the state itself, or businesses which receive an exclusive license (and perhaps
also subsidies) from the state to operate in a particular territory. Only with
the state’s coercive powers to prevent competition and fund an incumbent can
there really be a monopoly.

As monopoly theory suggests, over time the pricing for state services
(taxation) has always increased, and quality of service has deteriorated (or,
at best, remained substandard). The most that generally happens when a state is
revealed to be underperforming in provision of a service is that the problem is
diagnosed as underfunding, and thus pricing (taxation) increases to try to
remedy the problem! Little serious intellectual inquiry is made into the
question of whether monopoly provision of the service is the actual problem.
Unlike in the private sector, when the state underperforms, a consumer cannot
take his money elsewhere.

One wonders why a statist who is able to understand the problems with
monopolies would support the large and only possible monopoly that is the
state.

=== Lack Of Proper Incentives And Knowledge

The above discussion explains one of the shortcomings of the state in terms of
its institutional monopoly status.  However, since institutions cannot act, but
only people can act, the real inquiry should be into the incentives and
knowledge of the individuals who constitute the state, and whether these
factors should cause us to be supportive of these personnel. There are several
points to make in this regard.

*First*, in the private sector a vendor has to convince each individual
customer each time he wants to sell his product to that customer that he is
providing sufficient value for the price to be charged. However, for a
politician to get elected, he does not have to convince every constituent of
the value he will provide each time he interacts with that constituent. All the
politician has to do is convince a majority of those who turn up to vote, and
he only has to do that once every election cycle. Thus, by definition, he is
either non-responsive or, at best, only minimally responsive to the needs of
many of his constituents.

*Second*, consider that the principal benefit the individual at the state is
able to offer those who support him is the opportunity to rent the state’s
coercive powers. In other words, he can offer to a special interest group that
he will fight to pass, reject, preserve, strengthen, weaken, enforce or refuse
to enforce legislation that will (i) enhance this group’s position, or weaken
or prohibit competitors (through regulations), or (ii) forcibly transfer
resources from others to this group (through taxation and subsidies).

As a result, state personnel are lobbied intensively by special interest
groups, and the highest bidders tend to win the right to rent the state’s
coercive powers.  footnote:[Of course those statists who subscribe to one of
the Tooth Fairy Theories will object to this characterization, but that
rejection practically indicts itself.  What do the bidders typically offer?
Campaign contributions, “get out the vote” assistance, special favors for
friends and family, or the promise of a private sector career after leaving the
state, to name a few examples.]

*Third*, once in office, unlike in the private sector state personnel do not
have to convince their “customers” to pay them for their services. Through
taxes and other legislation state personnel can force their “customers” to pay
their salaries regardless of how they perform. Thus there is no incentive to
continuously offer something of value.

In fact, the problem is even deeper. In contrast to the strong alignment in the
private sector that exists between the interests of vendors and customers –
whereby vendors have personal financial upside from satisfying customers’
actual preferences and risk personal financial loss for failure to deliver –
state personnel have neither the upside nor the risk of loss. Thus, unless one
subscribes to one of the Tooth Fairy Theories, state personnel’s incentives are
entirely misaligned with the notion of delivering value to the broader
population.

*Fourth*, for private sector entrepreneurs to discover what customers really
want takes trial and error in producing different products, making quick
adjustments to competition, and obtaining continuous market feedback through
customers voluntarily electing to buy or abstain from buying on a daily basis.
On the other hand, at the state, only one product is offered at a time, it
takes years to make adjustments, there is no competition, and there is no
continuous market feedback as “customers” have no choice but to buy from this
monopolist. Thus those at the state, even if they had the best of intentions,
are effectively running blind when it comes to satisfying individuals’
preferences.  footnote:[Statists may respond that state personnel sometimes do
get regular feedback from polls. However, polls group individuals into
artificial categories rather than treating them as individuals, so they don’t
reveal individual preferences. Also, polls suffer from sample size and bias
issues.  Most importantly, however, individual preferences are only revealed
through purchase decisions, not answering surveys; the former has a real
financial cost to the action, whereas the latter is costless to the
respondent.]

image::{s-img}[{s-width}, align='center']

The question we need to ask when faced with human
imperfection – whether lack of knowledge, incompetence or corruption – is
whether it is better to have this imperfection decentralized or centralized?

If someone in the private sector is unknowledgeable, incompetent or corrupt,
only those few who interact directly with that person will suffer loss, and the
market quite quickly will ostracize that person (people will stop dealing with
him) so overall losses will be minimized. However, if someone is
unknowledgeable, incompetent or corrupt in the state sector, millions can
suffer because the imperfection is centralized and coercively enforced against
many.

Further, citizens cannot simply and quickly cease relying on this supplier,
because the state prohibits competition in the services it provides. Thus such
imperfection not only impacts millions, but also tends to endure for much
longer than in the private sector.

=== The State Receives Immunity

As if to rub salt into the wound, the state asserts that both it and its agents
should have immunity from suit for causing damage to those in the private
sector, unless the state waives such immunity. There are different types of
formal immunity standards (e.g., “sovereign immunity,” “state immunity,”
“qualified immunity,” etc.), as well as informal immunity (where the state
“circles the wagons” around one of its personnel when information comes out
about his misdeeds). However, the essence of all of these concepts is that,
whereas everyone else in society is held to one standard of liability for
causing damage to others, the state and its agents live by a different
standard.  And this different standard is forcibly imposed on society by the
state.

It is logically indefensible to claim that some men are entitled to live by a
different standard. Further, why should we respect or support any man who
forcibly asserts that he lives by a different standard?

In addition, this type of immunity creates a moral hazard: why should we expect
the state’s agents to exercise the same degree of care as we expect of others
if these agents cannot be held similarly liable? If you know you can get away
with more, your standards will drop.

This is most dramatically (but not solely) illustrated by the many situations
where police personnel use excessive force, causing unnecessary death and
injury to private citizens and destruction of their property, and yet private
citizens rarely have effective recourse against those personnel.
footnote:[Another contributing factor to the police using excessive force in
the U.S. is the fact that the police are increasingly recruiting or being
trained by former soldiers who previously prosecuted the state’s brutal “War on
Terror," and are also using surplus military equipment from that conflict.
Treating civilians like enemy combatants and the streets like battlefields,
with the aid of military equipment and tactics, can only lead to bringing the
brutality of war to our towns and villages.] Similarly with the horrific death,
injury and destruction caused by state personnel in initiating and carrying out
war activities around the globe.  footnote:[Note that these activities not only
cause death, injury and destruction to the state’s own citizens but also to
foreigners, and there is no cogent, logical principle which argues that death,
injury or destruction is excusable if the victim of a state’s violence is not
currently under that state’s territorial control; that victim is still another
human being.]

But there are other, more subtle, examples of destructive state actions without
liability: the state’s delay in approving new medical drugs or denial of such
approval, causing suffering and death to those who might have benefited from
access to the drugs; the state’s refusal to grant a license or delay in
granting such license to an individual to pursue his chosen occupation, causing
him to suffer economically; and the state’s setting of a minimum wage, thereby
prohibiting an individual with low skills from earning a living from an
employer at the wage of his choosing.

Even where immunity may not be complete legal protection for state personnel,
there is practical protection afforded by the forum in which these issues are
resolved: the only courts to which the state will submit in a dispute with a
citizen are the state’s own courts! In other words, the state arrogates to
itself the monopoly on deciding if it or its personnel should be liable to
private citizens. In what other area of life would we accept that the party
with which we are in a dispute can decide if it is liable?

To appreciate the implications of this issue, consider that, in the U.S.,
courts have held that the police’s “duty to protect” is only owed “to the
public at large” and not to any particular citizen. In these cases, the police
were being sued by victims for negligently failing to provide reasonable
protection against specific violent crimes, and the state’s courts found the
police not liable.

Thus not only do the police benefit from immunity when acting with excessive
force, they also benefit from immunity when negligently not acting at all! And
we are supposed to support the confiscation of our incomes to pay for the
state’s protection from violent crime?

Finally, even if monetary liability were imposed for destructive action by an
individual at the state, who would pay for this? Likely not the state agent
concerned, but rather the state. However, from where does the state get the
funds to compensate this private citizen? From taxing private citizens,
potentially including the private citizen who suffered the original loss!
