== Myth #6: The State Dispenses Criminal Justice

=== The Injustice Of It All

The whole area of criminal law is a very odd feature of statist society. Under
a just system, the law would recognize that only someone who suffers harm – in
the sense of damage to his person or legitimately acquired property (which I’ll
define later in this paper) – would have the right to take action against the
aggressor. Yet the statist criminal legal system fails this logic on a number
of accounts.

*First*, the system allows the state to take action against an aggressor even
though the state is not the victim. In fact, the state can never be a victim of
aggression against person or legitimately acquired property, because (a) “the
state” is not a person, and (b) any property the state controls has, by
definition, been acquired illegitimately, in that the state has used coercive
means to acquire it (i.e., by using either tax or regulatory legislation).

*Second*, under this system, state personnel, and not the victim, decide on
whether and how to pursue the aggressor and what penalties he should suffer.

*Third*, most “crimes” are defined by legislation simply as behavior which the
individuals at the state do not approve of, even though such behavior does not
cause any actual damage to any individual or his legitimately acquired
property. In other words, the state’s criminal legal system as a just means to
redress personal loss is mostly a fiction.

=== The History

How did we get here? Statists like to fantasize that there is some deep
philosophical or efficiency reason that has driven the state to become the
alleged guardian of everyone’s interests and to act against criminals “for the
common good.” However, that’s not what actually happened.

Hundreds of years ago there were no “crimes,” only claims brought by victims
against aggressors for personal wrongs. The claims were detected, investigated
and resolved locally, and mostly peacefully, according to community customs in
locally convened tribunals.

However, at some point when monarchs wanted to raise revenue to help finance
their lifestyles and their wars, and to more closely control society and reward
different interests who could help in that regard (such as local powerbrokers),
they realized that there could be tremendous profits from running a “justice”
system. Accordingly, a wrong committed by A against B or B’s property was
defined as a “disturbance of the king’s peace,” and at first such actions were
guided, and then later compelled, to be brought before the king’s courts.
Subsequently, “the Crown” took over detection and prosecution of these actions.
In these cases, ”the Crown” was able to: charge fees; fine A and seize his
property if he were found guilty; and fine B and seize his property for false
accusation if A were acquitted.

As monarchs extended their activities to include forcibly taxing their subjects
it became a crime not to pay one’s taxes, and thus the first victimless “crime”
was born. In other words, it became a “crime” for one man to try to prevent
another man from forcibly seizing part of his income, thereby negating the
timeless principle of being entitled to defend one’s property from theft. Other
victimless “crimes” were also created which were based on the principle of
failing to obey the king’s orders. This led to the creation of vast
bureaucracies to try to detect and then prosecute such heinous acts by
subjects.

Once monarchs gave way to the modern state, the state simply assumed the same
role.  footnote:[To bolster the aura around the supposed infallibility of, and
the supreme justice imposed by, the state’s court system, note how intimidating
the set up is, almost as if there are some divine aspects to it. The judge
wears a fearsome black robe, is seated higher than everyone else, may be
supported by armed guards, and must be addressed using honorific terms
(otherwise contempt charges may be brought against the miscreant). This is of a
piece with other ridiculously childish aspects of the state, such as the aura
and forced respect created around the presidency, the legislature and the
military. Respect and honor should be earned, not imposed, but the pomp and
ceremony is important for the state’s illusion of superiority.]

=== The Growth And Dangers Of Victimless “Crimes”

Worse, however, is that the modern state has now created thousands of
regulations the violation of which amount to “crimes,” and the vast majority of
these have no actual victims in the traditional sense, namely, an individual
suffering damage to his person or legitimately acquired property. There is an
obvious unfairness here in that no citizen can realistically be aware of all or
even most of these regulations, and therefore it is very easy for citizens to
commit legislated “crimes” without even knowing it. Before the advent of these
victimless “crimes” – when a “wrong” was merely defined as causing damage to
someone’s person or property – citizens could easily understand what was
expected of them.

And to enforce these thousands of regulations, the state has established vast
armed bureaucracies.  footnote:[For instance, according to a U.S. Department of
Justice report from June 2012, just at the federal government alone in 2008
there were 40 federal agencies with over 120,000 officers authorized to carry
firearms and make arrests. Unusual examples include the Environmental
Protection Agency, the Federal Reserve, the Fish and Wildlife Service, the
Bureau of Land Management, the Library of Congress, the National Oceanic and
the Atmospheric Administration, the National Institute of Health, the General
Services Administration, the Department of Education, the Department of
Agriculture, the Department of Housing and Urban Development, the Veterans
Health Administration, the Internal Revenue Service and the Park Service.]

Each year many thousands of lives are ruined, many permanently, when the state
arrests and tries it citizens, fines them, seizes their property and/or
incarcerates them based on these regulatory but victimless “crimes.” Examples
include tax evasion, insider trading and other securities law violations,
health & safety regulation violations, campaign finance regulation violations,
traffic violations, environmental regulation violations, prostitution,
occupational licensing violations, use of illegal narcotics, firearm possession
and immigration violations.  footnote:[According to the latest data from the
U.S. Bureau of Justice Statistics, approximately one-third of the federal and
state prison population in the U.S. (that is, approximately 520,000 prisoners)
had been incarcerated for these types of non-violent, victimless “crimes.” Note
that these numbers exclude another 700,000+ prisoners held in local jails and
over 4.7 million individuals on probation and parole, for which “category of
offense” data is not available, although undoubtedly a large number of these
individuals were also incarcerated for non-violent, victimless “crimes.”]

=== Marginalizing The Victim’s Interests

There are some other disturbing features of modern criminal “justice” systems.
Even where a real wrong occurs, in the sense that there is a victim who has
suffered personal injury or property damage, the victim’s interests are
marginalized by the state’s system. This happens in several ways.

*First*, in most modern states citizens have been disarmed by the state’s gun
control regulations and are vigorously prosecuted should they violate these
possession regulations. The theory is that the state’s police will protect
citizens so citizens don’t need to possess firearms to protect themselves. Yet
in the vast majority of violent crimes only the victim is present when the
crime is committed, not the state’s police, and thus the victim has been
deprived of the most effective method of self-defense.  footnote:[To bolster
its argument the state typically claims that reducing private gun ownership
will itself reduce violent crime, but that claim is demonstrably false: see
John Lott’s book, More Guns, Less Crime. The aggressor rarely pays attention to
gun control regulations, or uses other means to conduct his violence, such as
vehicles, knives, clubs, superior strength, explosives, etc. So the only effect
of gun control regulations is to disarm the law-abiding victims.]

Gun control regulations are also immoral. By what right can A tell B that only
A can possess a firearm, and forcibly prohibit B from doing the same? B is
entitled (as is A) to spend his income as he sees fit and to possess the means
to defend himself from attack. Obviously B is not entitled to use his firearm
to initiate aggression against others (nor is A), just as he’s not entitled to
use any other object, or his body, to do the same. Nor is B entitled to act
contrary to C’s instructions when on C’s private property, so C could
legitimately enforce a possession restriction on his property (if B disagreed,
his choice is not to enter C’s property). However, the state’s gun control
regulations often apply everywhere, and prohibit possession, not improper use.
But there are already laws against murder, robbery, rape, etc.

*Second*, the police serve the political class, and thus the police’s
priorities mostly reflect the political class’s priorities. Once the political
class sets a priority, that centralized order is what counts, instead of taking
into account each individual citizen’s desired preferences. Since policing is a
scarce resource, every hour spent by the police on task X means an hour less
available for task Y.

So, for instance, if the political class wants to raise more revenues, the
police will prioritize enforcement of tax laws, moving traffic violations, etc.
If the political class wants to evangelize, the police will prioritize
enforcement of laws against prostitution, narcotics, etc. If the political
class is feeling the pressure from the environmental lobby, the police will
prioritize enforcement of environmental regulations. If the political class is
feeling pressure from the anti-gun lobby, the police will prioritize disarming
citizens who possess unregulated firearms (but have committed no violence with
them). The time, personnel and money spent on these victimless “crimes” come at
the expense of resources that could be devoted to crimes with victims.

Alternatively, if the political class is feeling pressure from a particular
racial group, the police will reduce their presence in that group’s
neighborhoods and will reduce arrests of that group’s members, even if those
neighborhoods and members are responsible for significant violent crime.

The same political priority point also applies to prosecutors within the
state’s court system. Prosecutors too are a scarce resource, and thus focusing
more on one prosecution priority means focusing less on others.

These priorities might be quite at odds with what individual citizens want from
their police and prosecutors, and what they would choose to purchase if they
could individually purchase private security and enforcement services.
However, because the state produces a “one-size-fits-all,” politically directed
enforcement system, citizens have little individual choice.

*Third*, the criminal prosecutorial system is designed around the state, not
the victim. The prosecutor has no alignment with or responsibility to the
victim.

In a private law case the victim voluntarily chooses his attorney, the attorney
contractually must act in accordance with the victim’s instructions, and the
attorney has the motivation to do the best he can for the victim. This
motivation exists because how the attorney performs will impact his reputation
and thus his ability to attract future clients, who will also voluntarily
choose their attorney, and his compensation may be linked to how well he does
for the victim.

On the other hand, the prosecutor has no contractual relationship with the
victim, the victim is mandated to place his grievance against the aggressor in
the hands of whichever prosecutor the state assigns, and the prosecutor is not
motivated financially to act in the victim’s interests. Instead, the prosecutor
is motivated by whatever statistics the state decides it wants to use to
measure performance. For instance, if “wins” is important, the prosecutor may
drop the hard cases and only pursue the easy ones; if “case closure” is
important, the prosecutor may drop the long cases and only pursue those that
can be resolved quickly; if battling a particular type of “crime” is high on
the state’s agenda, the prosecutor will prioritize those cases and ignore
others.

The victim also has no ability to direct the prosecutor’s actions. If the
prosecutor drops a case against the victim’s wishes, the victim cannot “retain”
another prosecutor, as the prosecutor only serves the state, not the victim. If
the prosecutor enters into a plea bargain with the aggressor (because he wants
the aggressor to help him in a different case, or the case is going to take too
long, etc.), the victim cannot prevent that. If the prosecutor seeks a
punishment that is not in accordance with the victim’s wishes, the victim has
no ability to veto that. If the prosecutor does a poor job, the victim has no
claim against him for breach of contract, since the victim is not his client.
footnote:[If the victim sued the prosecutor for negligence, the prosecutor
would likely benefit from the immunity principle discussed earlier in this
paper, and of course the victim would have to sue the state prosecutor in
the state’s own courts!]

In short, the connection between the victim and the aggressor is completely
severed, and the state is actually treated as the victim vis-à-vis the
aggressor.  footnote:[Moreover, in some areas the state may actually prohibit
private civil action by the victim against the aggressor. Even where both
actions may be run in parallel, findings in the criminal case could impact the
outcome of the civil case, but the victim has no real input into or control
over the criminal case.]

*Fourth*, the victim can end up paying multiple times without his consent. He
suffers the loss from the aggressor’s crime and then, if he is a taxpayer, via
taxes he is also forced to pay for the cost of prosecuting the aggressor and,
if the aggressor is convicted, for the cost of incarcerating him in a state
prison!

=== Intimidation By The State

Another questionable aspect of the state’s criminal legal system is that the
state uses its legislated, victimless “crimes” as a “stick” to force citizens
to act in accordance with the whims of those at the state.

For instance, in the U.S., in circumstances where those in the federal
government are not able to implement their preferred policies directly, they
have made use of their control of the banking system – since it is a
(victimless) “crime” to operate a bank without a license – to indirectly get to
the same result. Thus the federal government has been known to tell banks that
they may not provide financial services to businesses which engage in
activities (also victimless) of which those at the federal government do not
approve, such as selling narcotics or firearms, engaging in payday lending, and
operating Internet gambling or escort services. The inability for these
businesses to use the banking system is a huge impediment and is akin to
preventing them from operating.

Similarly, the state makes it a (victimless) “crime” for certain companies to
merge without the state’s approval.  The state has been known to refuse to
consent to mergers unless one or both companies do something else the state
wants them to do.

Or consider that the state makes it a (victimless) “crime” for a citizen to
donate more than a specified amount of his own money to other citizens running
for political office. These campaign finance regulations are a wonderful weapon
for incumbents to use against challengers. The incumbents can use their office
and the resources of the state to get their message out, but for challengers
their main avenue is to purchase media time, which requires funds. When the
state limits the amount of money challengers can raise and spend, it favors
those already holding office.

To make a somewhat obvious point (by now), all of these victimless “crime”
regulations are immoral, in that they amount to one man forcibly telling
another what he may do with his body or private property when the second man is
not initiating aggression against anyone. Thus those at the state are using
immoral regulations to achieve their desired ends. This is a criminal “justice”
system?

=== Prioritizing Crimes Against The State

The final point to make about the perversity of the state criminal legal system
is to note how the state takes much more seriously “crimes against the state”
than crimes against its citizens.

For instance, the murder of a key figure at the state is even given a special
term – “assassination” – and it’s hard to describe how many resources the state
devotes to preventing assassinations and the lengths to which it will go to
find perpetrators. Compare this with the resources the state devotes to
preventing and solving murders of ordinary citizens. Those at the state
unilaterally elevate the importance of their own lives over the importance of
the lives of those who both fund the state and are supposed to be protected by
it.

Accordingly, through taxes, the ordinary citizen is forcibly required to fund
the special protection of individuals at the state, and is not permitted to
retain this income for his own protection or for the protection of individuals
of his choosing. Moreover, although the state taxes the ordinary citizen with
the promise of protecting him from violence, the state makes this a secondary
priority for the use of this citizen’s income, behind protection of individuals
at the state.  footnote:[And note that the state uses the ordinary citizen’s
income to fund its possession of large amounts of firearms and ammunition to
protect individuals at the state, while at the same time substantially limiting
the ordinary citizen’s ability to use the same firearms and ammunition to
protect himself.]

Related to the above point, assaulting a police officer is treated very
differently from assaulting an average citizen.  For instance, in the U.S.,
most state legislation elevates the category of crime from “assault” to
“aggravated assault” if the victim is a police officer. Fines and sentences are
often greater for this type of assault as compared with assaulting a regular
citizen. Further, some of the normal defenses to an allegation of assault are
often not available if the assault was directed at a police officer.
footnote:[This concept is even more egregious when paired with the immunity
concept described earlier in this paper: the police get the benefit of immunity
when they do something wrong, and when they are wronged their aggressors suffer
greater penalties.]

Yet if all men are born equal, how can one defend the concept that the penalty
for initiating aggression against A should be different from the exact same
action directed at B?

Or consider how vigorously the state pursues its citizens who fail to pay their
taxes compared with the action the state takes when one citizen complains
another has failed to pay a debt due.  footnote:[Obviously I’m not suggesting
taxes are a “debt due” to the state, since taxes are forcibly confiscated by
the state as opposed to arising from a voluntary loan contract.] Non-payment of
taxes is a “crime,” whereas failure to pay a private debt is generally not.
Further, the state has a veritable army of tax inspectors and armed tax
enforcers to go after tax avoiders.  footnote:[In the U.S., quite apart from
the Internal Revenue Service’s enforcement arm there are other examples, such
as the New York state government’s “strike force” to combat the heinous crime
of trying to avoid payment of state taxes on cigarettes.]

In addition, to try to prevent non-payment of taxes the state also establishes
many ancillary reporting and disclosure regulations, violations of which are
also “crimes.” These include requiring use of a tracking identification number
by taxpayers, requiring self-reporting of taxable income and of assets held
overseas, and forcing banks to monitor and report on customers’ cash movements
and sources. Sometimes the state even enlists foreigners to become its tax
collectors, by requiring foreign banks to report on the overseas holdings of
citizens and by bringing economic pressure to bear on “tax havens.”
footnote:[“Tax havens” are simply countries that have the temerity to charge
lower tax rates than states like the U.S. might prefer.  They represent tax
rate competition to higher taxing states, as they attract taxpayers
(individuals and firms) who might choose to relocate to reduce the theft
engaged in by their current states. And if there is one thing a state dislikes,
it is competition.  ]

All of this is a far cry from how the state protects private creditors from
non-payment by debtors.

Finally, consider how vigorously the state pursues those who disclose state
information compared with how the state protects disclosure of private
information. Again, the former is a “crime” (with its own word: “espionage”),
whereas this is not generally true of the latter. The U.S. federal government
has often used the threat of indictment under the Espionage Act to try to
silence “whistleblowers” who want to publicly disclose state information and
activities. Also, note how worldwide dragnets are established to try to snare
those who have the audacity to disclose things the state would rather keep
secret, e.g., the pursuit of Julian Assange and Edward Snowden.

Private citizens just cannot expect the same resources to be devoted to
protecting their information.  footnote:[There is some irony to this entire
point anyway. In the U.S., the largest danger to the ordinary citizen’s privacy
is actually the U.S. federal government, which spends billions of citizens’
confiscated tax dollars each year intercepting citizens’ telephone calls,
emails and Web browsing, and monitoring their physical movements.]

