== Myth #1: The State Is A Moral Actor

Every action the state takes is coercive; legislation is passed to compel
changes in behavior. Tax legislation is passed to confiscate the income of
peacefully acting individuals in excess of what they would otherwise
voluntarily give to the state. Regulatory legislation is passed to force
peacefully acting individuals to take or refrain from taking actions with their
bodies or private property contrary to how they would otherwise act. Failure to
comply with legislation, and with the armed agents of the state who seek to
enforce such legislation, results in being locked up in a brutal cage (known as
“prison”) for a number of years as decided by the state. It may also result in
the state confiscating some or all of your private property. If you physically
resist the state’s agents on the grounds of self-defense of your person or
property, these well-armed agents may physically injure you or, in the worst
case, kill you.

It is impossible to deny that legislation is coercive: if it is not coercive,
how does one explain the violent penalties for non-compliance; if it only
represents what everyone would do anyway, why is it passed at all?

Accordingly, the reality is that the state comprises a group of individuals who
create and enforce coercive rules about how other, peacefully acting
individuals must act with their bodies and private property. No other
individuals in society claim legitimacy, or would be recognized by statists as
having legitimacy, in doing these things.

This is indeed an awesome power to have over the lives of others. However, it
entirely contradicts the notion ‒ and therefore implies that statists do not
believe ‒ that all men are created equal and therefore should live by the same
behavioral standard in terms of how they conduct themselves vis-à-vis others.
To statists, some men are entitled to forcibly dictate to others what they may
do with their bodies and private property. Statists are unable to articulate
where this entitlement comes from, because there is no good answer. No man is
born with any natural entitlement to rule another; he can only gain such power
through the other’s explicit consent, and subject to the terms thereof.

Thus, absent such consent (which I will deal with below), statists necessarily
believe that there are two codes of acceptable behavior for human beings: one
code applies to regular citizens; the other code applies only to those
individuals at the state. The latter code permits individuals at the state to
engage in actions that, if performed by regular citizens, would be regarded as
wholly illegitimate, if not moral atrocities. This means that statism
recognizes no universal standard of acceptable behavior for man, and thus
statism cannot be based on any notion of morality.

To illustrate this point, imagine a street with 10 residents. One resident, X,
kicks open Y’s door and demands that Y hand over 30% of his income or else he
will lock Y in a cage in his basement for five years. Every person would agree
that X has no right to do this. What Y earns from employing his labor or
capital is his to keep, transfer, gift, etc., but it is none of X’s business. Y
may voluntarily decide to give X 30% of his income, but he might also decide
not to do so. No one on that street has the right to take this coercive action
against anyone else. Now, what if six of the residents get together and tell X
that he is allowed to do this? Does that change the legitimacy of X’s action?
If no individual had this power on his own to begin with, how can he delegate
it to X, even as part of a group?

Yet this is precisely what statists accept when they claim that a majority of
voters can empower an individual at the state to levy a 30% income tax.
Statists may respond that the money confiscated from Y will be used to help Z,
who is needy (by someone’s arbitrary definition), and that this is therefore a
just cause. However, what the statists are really saying is that the other
people on the street have the right to decide whether to give Z a priority
right to Y’s income!

If these others feel so strongly about helping Z, they are free to do so
voluntarily on their own from their own resources footnote:[Interestingly,
most statists who want to help others with their own money would still prefer
to hand this money over to the state (in the form of taxes) to disburse to the
intended recipients (as transfer payments), instead of finding worthy
recipients (or charities) and giving it directly. Why a statist would choose to
funnel his money through the state – which has bloated administrative overhead,
and comprises individuals with incentives to use the money for their own
purposes rather than the intended recipients’ purposes – is a question
rarely asked, much less answered.]. Alternatively, they may try to convince Y of
the merits of helping Z. However, to simply arrogate to themselves (through X)
the power to forcibly take Y’s income has no moral legitimacy.
footnote:[Statists look aghast at Nazi Germany’s legislation passed in the
1930s to make “legal” the plunder of its Jewish population’s property. Yet why
is this different from any tax legislation? The German government was
originally democratically elected, and these rules were passed by its
legislature. The legislation permitted the state to confiscate the private
property of its citizens, which is what the income tax does. Perhaps the
statist would argue that it was unfair that this legislation only applied to a
segment of the population, yet this is little different from progressive rates
of taxation and tax exemptions, which impact different segments of the
population differently. Perhaps the statist would be more inclined to support
such plunder legislation if it had applied to everyone, which is what statists
in fact do support!]

Or take a second example. A wants to work for B. B offers to pay A a wage of
$6.00 per hour, and A accepts this offer. Yet C comes along and says that A is
not allowed to work for B unless B pays A $7.00 per hour, and that if, contrary
to C’s edict, A does work for B at $6.00 per hour then C will lock up B in a
cage in his basement for a year.  By what principle does C have the right to
interfere in the private arrangement between A and B? By what principle can C
prohibit A from working where he chooses, and prohibit B from spending his
funds as he chooses?  Does this situation change if D, E and F all tell C that
he is allowed to do this? If none of D, E or F had this power themselves to
begin with, how can they individually or collectively delegate such power to C?

Yet this is precisely what statists accept when they claim that a majority of
voters can empower an individual at the state to legislate a minimum wage rate.
Statists may respond that they just want to help A earn more money and that
this is therefore a just cause. Leaving aside whether the policy would actually
achieve that objective (B may just rescind his offer to A, or never make it in
the first place, if he is compelled to pay more than he wants to pay), what
statists are really saying is that D, E and F have the right to tell A that he
cannot work for B, and to tell B that he cannot employ A, unless A earns what
they have decided he should earn.

If D, E and F feel so strongly about helping A, they are free to do several
things: offer to employ A at $7.00 per hour themselves; offer to supplement A’s
income by $1.00 per hour out of their own pockets; or try to convince B of the
merits of paying A more. However, to simply arrogate to themselves (through C)
the power to forcibly prohibit the private arrangement between A and B has no
moral legitimacy.  footnote:[It has no consistency either. If statists believe
that no one should work for an amount below what the individuals at the state
deem a “living wage,” how can they support charity work and volunteers? Heaven
forbid, volunteers are working for nothing!  Ah, the statist retorts, but they
are willingly choosing to use their time to help others. So now the minimum
wage principle devolves into statists not being happy about how people are
choosing to use their time: apparently those who choose to use their time to
earn below the minimum wage are making an unapproved choice. Huh?]



