== Myth #5: Democracy Is Good, Better, Best

While statists assume that democratic states represent progress relative to the
monarchies that existed previously, libertarian philosopher Hans-Hermann Hoppe
has advanced the credible thesis that democracy may actually be a step
backward.  footnote:[Hoppe is not suggesting that a monarchical state is
acceptable, only that it exhibits characteristics which make it preferable to a
democratic state. Note that Hoppe’s thesis has been challenged in at least one
academic article: see Jacek Sierpinski’s work, “A Critique of Hans-Hermann
Hoppe’s Thesis on Lesser Harmfulness of Monarchy than Democracy,” _Res Publica
Revista de Historia de las Ideas Politicas_ , Vol. 19 Num. 2 (2016): 521-559.]

=== Key Characteristics Of A Monarchy

According to Hoppe, under pre-parliamentary, bloodline monarchies the monarch
regarded the interest he and his family held in “his” people and society’s
resources as a long-term interest. As such, the monarch viewed society as a
capital asset, the value of which should be preserved for future generations of
his family. This was essentially a system of “privately owned government.”

Therefore, such a monarch tended to avoid doing things that would profit him in
the short term but create long- term damage: the quantity of resources
expropriated from the population would be somewhat limited, as the monarch
wanted “his” society to be as productive as possible; only those who, in the
monarch’s view, could add value to society would be permitted to immigrate, and
value-destroying elements would be expelled; and wars would be conducted
privately and on a limited basis between a monarch and his hired army and the
enemy’s monarch and his hired army – private citizens were understood not to be
involved – with neither side wanting to destroy the capital value of its own
society or the society it might end up winning.

Moreover, everyone in society knew that only a few people could participate in
and benefit from the monarchy, namely, blood relatives. Thus there were very
clear class distinctions, with the ruled accepting that, while they had
numerical superiority, they would never be in power. From the monarch’s
perspective this created a constraint on how much expropriation he would engage
in, as too much might lead to an uprising from the ruled class, which would put
the value of “his” society at risk.


=== Differentiating Characteristics Of A Democracy 


According to Hoppe, the advent of democracies footnote:[In using the term
“democracy” here I am using it loosely to describe any non-hereditary
political system in which the broad population elects government officials in
periodic elections, where such officials are drawn from the general populace
and serve for limited terms. Technically, however, “democracy” refers to a
specific political system in which there is _unlimited_ majority
rule. Contrast this, for instance, to the U.S., which is not technically a
democracy but rather a constitutional federated republic, because in the U.S.,
in order to protect the minority and individuals, the majority is
_theoretically limited_ by a fundamental written law (the
Constitution) and the system’s structure (different horizontal and vertical
branches of government).  However, for all purposes going forward I will treat
the U.S. as a democracy since the key point is to distinguish it from
monarchies.] changed many aspects of societal governance.

*First*, politicians do not see society as “theirs,” and thus do not take a
long-term, capital-asset-preservation view.  Rather, they act as temporary
caretakers, doing whatever they can in the short term to get elected or to
increase the powers they can rent out for personal gain, regardless of the
long-term impact on society. A good analogy for the difference between a
monarch and a democratic politician is the landlord and the renter: who is apt
to take better care of the property? Politicians simply do not bear the real
costs of their actions.

*Second*, in a democracy the population believes, falsely, that they are ruling
themselves (the supposed democratic principle of “self-government”), and that
they each have the opportunity to get elected or influence the elected to get a
piece of the action (i.e., there is a blurring of class distinctions). Thus
there is a much greater acceptance of ever increasing expropriation and control
by the state. People either believe that such activities are legitimate
because, as “self-rulers,” they are only “doing it to themselves,” or else they
believe that they too can ascend to or influence the halls of power and take
advantage of the state’s coercive powers.

Accordingly, Hoppe posits that since the advent of the democratic state –
“publicly owned government” – we have seen much more short-term, reckless
thinking by the rulers in society and the disappearance of any real limits on
the growth and exercise of the state’s power. As such, the state is now larger
than it has ever been and politicians perceive fewer and fewer limits on their
powers amid the (perceived) acquiescence of their citizenry.

=== State Violence, Democracy-Style

Whether or not one accepts all aspects of Hoppe’s thesis, what is incontestable
is the development of the large scale, reckless physical violence initiated by
modern, democratically elected governments both domestically and externally.

Contrary to popular thought, democracy is no bulwark against abuse at the hands
of one’s own state. It is not just dictatorships that have waged war on their
own subjects.  footnote:[Although it should not be overlooked that
dictatorships are states too, and in fact dictators sometimes come to power
through elections or, once in office, hold elections as a means to justify
remaining in power. While one may be skeptical about elections in dictatorships
‒ due to claims of voter fraud, intimidation and suppression, and limitations
on opposing candidates ‒ those issues are regularly cited as issues in
democracies too! In any event, when we include dictatorships, the number of
unarmed citizens killed by their own state totals over one hundred million in
just the 20^th^ century alone.]

Consider, for instance, President Lincoln’s waging of war against the people of
the Confederate states in the mid-19^th^ century, the democratically elected
German government footnote:[While Germany was a totalitarian state by the time
the German government invaded Poland in 1939 at the beginning of World War II,
Hitler and his Nazi Party colleagues were duly elected into office in 1933 as
in any other democracy, and, while the Nazi Party did not initially hold a
majority of seats in the Reichstag (parliament), Hitler was appointed by
President Hindenburg as Chancellor to head a ruling coalition. Subsequently
Hitler was given emergency powers by Hindenburg according to the Weimar
Constitution, and the Nazi Party then won a majority in a general election (in
which the Socialist and Communist Parties were banned and their voters
intimidated). Hitler’s Enabling Law, which gave him vast power, was passed
through a vote by the Reichstag, although members of the Reichstag who would
presumably have voted against this law were not allowed into the Reichstag
building. This is when Hitler began his totalitarian takeover of Germany and
the vestiges of democracy began to disappear.] turning on German Jews in the
1930s, the British Empire’s atrocities committed in the early to mid-20^th^
century against its colonial subjects in Africa (Kenya and South Africa), Asia
(India and Malay) and the Middle East (Iraq and Yemen), and the modern U.S.
government’s violence against its own citizens in the so-called “War on Drugs”
(following on from a similar form of persecution in the early 20^th^ century
during Prohibition).  footnote:[The “War on Drugs,” like Prohibition, should
really be called the “War on People Who Believe They Own Their Own Bodies.”]

There are also plenty of instances of democracies initiating war on other
nations which have not attacked them.

As just a few examples, consider: the government of Great Britain going to war
against Germany in 1914 after the German government had attacked Belgium; the
governments of France and Great Britain going to war against Germany in 1939
after the German government had attacked Poland; the U.S. government going to
war against Germany in World Wars I and II (Germany had not attacked the
U.S.); and the U.S. government taking offensive action in many other states
including Korea, Cuba, Vietnam, Grenada, Bosnia and Kosovo, Somalia,
Afghanistan, Iraq, Libya and Syria.  footnote:[Note that in many of these
conflicts the U.S.  government was joined by the governments of other
democracies.] In fact, the list of aggressive activities initiated by the
government of the U.S., the world’s largest democracy, is significantly longer
when you consider that, in addition to the overt wars fought by the U.S.
government in instances where the U.S. had not been attacked, the U.S.
government has waged aggressive covert action in all areas of the world for
most of the 20^th^ and 21^st^ centuries. It has done this through its
intelligence agencies and other proxies interfering in the domestic activities
of other states (including other democracies), the use of foreign aid to
certain nations tied to such nations behaving as instructed by the U.S.
government and, most recently, the use of unmanned attack drones.
footnote:[For a chilling and thought-provoking discussion of drone aggression
waged by the U.S. government in recent times, see Laurie Calhoun’s book, _We
Kill Because We Can_.]

In addition, the way in which war is conducted has also changed for the worse
in parallel with the rise of the democratic state. Perhaps because for so long
democratic states have ingested the (fallacious) concept of “self- rule”, when
it comes to conflict and war democratic states conflate all citizens on earth
with their respective governments (this is especially incongruous when it comes
to dictatorships, given that the civilian populations in dictatorships have
less “say” over their rulers than in democracies). Accordingly, when democratic
states go to war, instead of combat being confined to the rulers and their
military forces, all citizens and all property are regarded as fair game in
what has become known as “total war.”

For instance, President Lincoln’s generals conducted a brutal form of “total
war” against the non-combatant residents of some of the Confederate U.S. states
(before turning to the native American Indians), which was a tactic repeated
some years later under Presidents McKinley and Roosevelt against the Filipinos
in the Philippine- American War. During World War I the British government’s
blockade of food deliveries to Germany led to mass starvation among the
civilian German population. During World War II the Allied militaries’ bombing
of German cities and the U.S. military’s bombing of Japanese cities made no
distinction between those who had declared and were fighting the war and the
private citizen. When the U.S. military dropped two atomic bombs on Japan in
1945, killing, maiming and poisoning close to two hundred thousand civilians,
it did not distinguish between the citizens of Japan and their rulers and
military. During the Gulf War in 1991 the U.S. military intentionally bombed
Iraq’s water treatment plants, thereby depriving the Iraqi civilian population
of clean drinking water. The U.S. military and its allies, many of them
democracies, have inflicted substantial “collateral damage” – the modern
euphemism for the incidental (but foreseeable) killing or maiming of private
citizens and destruction of their property – in many of their aggressive
actions in Asia and the Middle East over the past half-century. And so the 20^th^
and 21^st^ centuries go.  footnote:[Note that it’s not only in violent war that
civilians are targeted by democratic states; when such states levy “economic
war” against another state, such as through trade sanctions, the explicit
purpose is to economically hurt the other state’s civilian population as a
means of pressuring its government. (Of course the democratic state also hurts
its own civilian population by levying such sanctions, since these sanctions
prohibit its own civilians from freely trading with the civilians of the other
state.)]

To digress slightly, but importantly, it is too easy to overlook the essence of
offensive war actions. These actions involve state personnel sending armed
forces or unmanned attack drones overseas to kill or maim other men and
sometimes also their families (intentionally or negligently), and to destroy
their property, very often in the home territory of these other men. The
aggressor’s armed forces are specifically instructed to initiate these acts of
brutality and destruction against men they have never met and who have not
initiated violence against these armed forces when they were at home (or
against the civilian populations these armed forces are alleged to be
protecting). And when these other men fight back to defend their families and
property from the foreign aggressors, or seek to exact retribution either in
their home territory or by traveling to the territory of the aggressing state,
the state labels these other men “violent animals” who need to be subdued by
force or eliminated!

Yet many statists not only support these aggressive endeavors, they also revere
the civilian leaders and members of the military who actively participate in
these atrocities. Imagine if these same armed forces carried out these actions
against domestic citizens; would statists support that?  footnote:[For an
example in a democracy suggesting that this issue might not trouble statists,
consider that in the U.S. between 1861 and 1865 President Lincoln’s generals
waged war on the citizens of the Confederate states, which actions many
statists still support to this day. Of course one could also argue that, since
this war followed the Confederate states’ secession from the U.S., this war was
actually waged against a foreign nation’s citizens. In which case the statist
could rest easy, morally speaking!] If not, what is the moral principle that
says it is acceptable to engage in these atrocities against other humans so
long as they are outside the state’s artificially drawn borders? It seems as if
once the individuals at the state declare “We are at war with [name your
enemy],” the statist’s definition of “moral atrocity” is substantially relaxed
and the brutality of war is legitimized. Alchemy!  footnote:[For a very
insightful articulation of the delusions that accompany modern warfare, see
Laurie Calhoun’s book, _War and Delusion_]

The statist will often retort that prior to the advent of the state there was
widespread violence among individuals, families, clans and tribes. There’s
plenty of historical evidence to the contrary, namely, that these societal
units quickly developed peaceful means of dispute resolution as they recognized
how costly violence was. However, even if the claim were true, such violence
was on a very different scale from today’s wars. Non-state violence was limited
because it was personal; those engaging in the violence bore the full cost of
their actions and thus there were natural constraints. Contrast this to the
massive scale of violence now waged globally by nation-states, including
democracies, resulting from the fact that those ordering this violence don’t
bear the direct costs of their decisions.

If this is our choice, give me pre-nation-state clan violence any time!

The private citizen cannot escape the war-mongering decisions of his rulers,
yet he pays a heavy price for these decisions: death, injury and mental anguish
when conscripted to fight the state’s wars or when those attacked by the state
engage in or threaten retribution against the state’s citizens (sometimes
labeled “blowback”); loss of liberties at home as the state tries to prevent
blowback; deterioration in culture as it becomes increasingly centered on
military and security matters; and economic impoverishment (through direct loss
of property, increased confiscation of income to pay for war, reorientation of
societal production away from satisfying consumers’ wants in favor of tools of
death and destruction, and consumption of society’s capital base). Whether the
private citizen has voted for or against a ruler, or has not voted at all, he
incurs the costs of the state’s violence.  footnote:[For an excellent
discussion of what war does to a population, see the book edited by John
Denson, _The Costs of War_.]

The conflation of the state’s subjects with the state itself is actually an
important tool used by state personnel in the context of war. State personnel
(and their supporters) always couch their statements in the first person
plural: “We” are at war; “We” have been attacked overseas; “We” need to take
action; “We” need to look after “our boys.”

Yet there is no “we”; there is only “they.” The average peaceful citizen does
not engage in violent action overseas against other humans or station himself
there to try to interfere with another society. It is obnoxious for state
personnel to claim “we” are doing these things. They are doing these things
without any direction or consent from the peaceful citizen. They start these
wars, they forcibly take our income to finance them, and then they have the
temerity to say “We’re all in this together.” And it is only they who benefit
from war: the politicians who gain prestige and power from conquering and
occupying new lands, the state agencies which maintain or grow their budgets
when there is war (or the threat thereof), the banks which finance war, the
vendors of military equipment (and their supply chains) which profit from
supplying war materials, and the favored businesses which gain from new or
cheaper access to conquered resources or enhanced protection of their existing
or future foreign investments.  footnote:[Note that not only do the rulers (and
their cronies) benefit from war and not bear any of its costs, but the most
senior members of the state also receive significant personal protection
against any blowback – paid for by the confiscated income of private citizens –
in the form of massive amounts of armed protection wherever they go (while
denying private citizens the right to be armed for their own protection) and
underground bunkers to which to flee if there is an actual or threatened
attack.]

Statists wrap all of this violence in the national flag and collective
patriotism, because in this way they can try to convince the average citizen
that these violent activities overseas are honorable and necessary ‒ to protect
our “national pride” and “the principles we stand for,” whatever those phrases
mean ‒ so there will be less objection to pursuing and funding war and
“supporting the military.”

Statists have been remarkably successful in constructing this delusion. The
average citizen is highly deferential to and sympathetic toward military
personnel: applauding them in public, providing special ways to honor them
(particularly at sporting events), weeping at their reunions with their
families, going out of his way to find them civilian jobs, and dutifully
accepting the state’s claim that we must additionally finance their physical
and mental recovery (in addition to their historic compensation forcibly
extracted from taxpayers). But these military personnel voluntarily chose to go
into the morally suspect killing and destruction business!  footnote:[One might
have more sympathy for those in the armed forces who are conscripted by the
state to fight its wars. Even then, the real honor should be reserved for those
who flee to avoid carrying out the state’s violence.]

Moreover, 99.9% of the time these military personnel are not actually defending
the average citizen from any imminent threat to that citizen’s life or
property. Before the state’s armed forces kill or maim each individual regarded
as “the enemy” or destroy his property – and most often this target is
thousands of miles away from the citizen allegedly being protected – the state
doesn’t bother to first adduce and present evidence of an actual or a
threatened wrongful act by that person, nor subject that evidence to any
reasonable standard of proof or scrutiny by an independent arbiter. Statists
just assume that this person’s guilt is proven by the fact that he was targeted
by the state, and that the state’s violent actions were an appropriate
punishment.  footnote:[Probably the most startling example of this in recent
times is the fact that, as disclosed in 2012, during his presidency President
Obama regularly presided over a “kill list,” whereby he ordered the murder by
drone strike of designated individuals overseas, including Americans, none of
whom had been tried and found guilty of any crime. While many of these strikes
also murdered individuals not on the list, according to one report in The New
York Times the president had a formula for minimizing the official count of
mistaken casualties that “ in effect counts all military-age males in a strike
zone as combatants... unless there is explicit intelligence posthumously
proving them innocent.” This is quite a perverse reversal of the usual burden
of proof required in capital crimes. Yet, more than four years on, this
shocking activity is no longer a central discussion point in the U.S.; it
appears that the vast majority of the population doesn’t know about, doesn’t
care about or, in the case of foreign policy hawks, actively supports, this
exercise of state power.] And the state’s honored military personnel eagerly go
along with this travesty.

What type of society have we become where we regard proactive killing and
destruction as one of the most venerated forms of human endeavor?

To illustrate this delusion further, consider private security guards who are
hired to protect people and their property. They don’t go in search of other
humans to kill or property to destroy, but only react to real situations that
endanger their clients or their clients’ property. They don’t get paid by
coercively extracting money from their clients, but have to offer sufficient
value for their clients to voluntarily hire them. Do we see a national
outpouring of emotion and collective financial support for these private sector
individuals, who are actually protecting life and property against imminent
threats?

Apparently honor is reserved only for those state personnel who proactively
kill foreigners and destroy their property, and who get paid through
confiscation of taxpayers’ income.

image::{s-img}[{s-width}, align='center']

Winston Churchill is reputed to have once noted “It has been said that
democracy is the worst form of government except all the others that have been
tried.” For the above reasons, I would challenge Churchill’s implied
conclusion.

I would also note that he clearly never considered a truly voluntary, stateless
society as a governance option, which I’ll explore in greater depth later in
this paper.


