== Myth #2: The State Acts By Consent

The statist will often respond that the state is not in fact coercive because
everyone consents to its activities.  What the statist can only mean, however,
is that he consents to the state’s activities; he cannot speak for anyone else.
The mere fact that I am writing this paper indicates that at least one person
does not consent to the state’s activities (and there are many more like me).
footnote:[Lest there be any confusion, for the remainder of this paper I will
use “coercive” to mean using or threatening force against those who don’t agree
with the state’s existence or actions. Obviously the state is not seen as
coercive by those who accept the state’s legitimacy in any particular instance
under discussion.]

If the response is “Well, the majority of people consent” then what the statist
is suggesting is that we live by mob rule. This obviously doesn’t address the
moral problems raised above but simply restates them in a different way.
footnote:[As the saying goes, under this way of thinking it would be reasonable
for two wolves and a sheep to vote on what’s for lunch.]

Some statists will try to argue that, notwithstanding my making explicit that I
do not consent to the state, by my actions I am implicitly consenting, which of
course makes one wonder what “consent” really means.  It’s worth exploring some
of the common arguments of statists in this regard.

=== The Constitution

One argument used in the U.S. is that the Constitution, which established the
federal government, binds everyone because it’s the supreme law of the land.
footnote:[The argument would be similar within a U.S. state with respect to
that state’s constitution.] Sometimes this is embellished by saying that it was
passed by super-majorities in each of the ratifying states, so it’s really
binding. This argument has a number of flaws.

*First*, no one alive today was part of the original consent. In no other part
of our lives do we admit to being legally bound by what our predecessors have
done, and nor would we assume we can bind our descendants. No court would
uphold this as a valid point of contract law.  footnote:[As libertarian
attorney Stephan Kinsella has put it, it’s as if statists are saying that only
the first generation had the freedom to make a choice, but no future generation
does.]

*Second*, if anyone today is deemed to have consented to the Constitution, they
would only have agreed to be bound by what was written in the document, and
today’s federal government operates well beyond those words.  Statists like to
say that the Constitution is a “living document” that adjusts over time, but in
what other contract is that a valid argument anyone would accept?

For instance, imagine if the Underwriting Department of the bank that holds
your fixed rate mortgage contacted you to advise that the mortgage contract is
a “living document” and, since times have changed and the bank needs to boost
its revenues, your monthly payment is going to increase. Would any person
accept this as a valid action?  The statist’s argument that the Constitution’s
“expansion” is valid because it has been effected through Supreme Court
decision doesn’t hold water either, since the Supreme Court is merely another
organ of the state. It would be like your objecting to the mortgage bank’s
proposed action and taking the dispute to the bank’s Customer Service Center
for resolution. Good luck with that.

=== Voting

Another argument that statists make to claim that we are consenting to the
state is that we get the opportunity to vote for our representatives in each
election. This argument has a number of components that deserve scrutiny.

*First*, voting is a false choice: you are choosing between being coerced by
politician A or politician B. There is no choice not to be coerced.

*Second*, whether you vote for politician A or against politician A, or you
don’t vote at all, if politician A is elected then he gets to coerce you. In
what way is that a valid choice? In every other area of our lives we make real
decisions between competing products, and we may choose not to purchase
anything in any particular instance, but no vendor can force you to buy his
product.

*Third*, what does it mean to be “represented by” a politician? He does not
know you, you do not know him, neither person signs a document agreeing to the
specific terms of representation, he cannot be held to account or fired by you
if he breaches those terms and, by virtue of representing thousands of very
different people in your district, he is bound to act in conflict with the
desires of many of the people he represents with everything he does.
footnote:[In the U.S. (although this is likely true elsewhere too), as
populations have grown substantially the increase in the number of elected
representatives has not kept pace, thereby increasing the number of people
“represented” by each elected official well beyond what might have been
considered reasonable originally. For instance, the Constitution specifies a
minimum House of Representatives district size of 30,000; today, the average is
over 730,000 (put another way, were the House of Representatives to operate at
that original ratio there would need to be over 10,000 members). This severely
further diminishes any notion of “representation” of any individual voter’s
interests by his elected member of Congress.] In all other areas of our lives
where we hire a representative, e.g. a lawyer, both parties first contact each
other and discuss the arrangement and know the specific terms and duties of
that arrangement, you can fire your representative at any time if he breaches
these terms, and he cannot act against your interests in favor of another
client without getting both parties’ explicit consent.

*Fourth* , to exactly which terms does a voter consent when he casts his vote?
The platform that the politician campaigned on two weeks ago, last week or this
week, the new ideas the politician pursues after the election, the ideas he
later discards, etc.? The fact is, neither the voter nor the politician could
articulate the terms to which the voter is consenting.

=== Living Here

Yet another argument statists make is that, if you live here, then you must
implicitly consent to the system. Let’s explore this one a little further.

*First*, since this argument is one of implicit consent, surely raising your
hand and explicitly saying “I want to secede from the state” should trump the
implicit consent? It also implies that the consent is irrevocable, i.e.,
apparently you can never withdraw consent. Do we accept these propositions for
any other major decision in our lives?

*Second*, when is this consent actually given: at birth? In no other situation
are newborns deemed to have sufficient capacity to give such consent. If not at
birth, what is the actual indicator later in one’s life that one has consented
to the state? For all other major decisions in our lives – such as buying a
house or a car – we evidence our consent by signing a contract which lays out
the very specific terms of that agreement. Yet for the most important decision
– whether we will allow unspecified other men to take from us whatever they
choose, and to tell us what we can and cannot do with our bodies and property –
we are deemed to have given consent simply by not moving away?

This logic can be easily turned on the statist. When the statist complains
about murder in his society, we could ask why the statist doesn’t move to a
place without murder and, by the statist’s own logic, if the statist stays then
he must be consenting to murder!

*Third*, to what are you consenting by living here: everything the state does
now or may do in the future? Who gives that blanket consent anywhere else in
their lives?


*Fourth*, claiming legitimacy as a ruler in a territory is not the same thing
as actually having legitimacy. If I put up signs in the neighborhood saying
that I am in charge and anyone who stays is deemed to consent, who would agree
that staying indicates agreement to my authority? I can’t point to my own
declaration of legitimacy as the source of my legitimacy; that would be
circular reasoning.

*Fifth*, to negate this supposed consent, to where could you move within a
territory if every square inch is claimed by the state to be under its control?
If beyond your home state, how can you move when other states control passage
across their artificial national borders, and the only places not controlled by
states are (parts of) the oceans and possibly Antarctica? The exit costs are
simply too high to make staying a genuine indication of implicit consent.
footnote:[To renounce U.S. citizenship is not easy, fast or cheap. One must
fill out a number of forms, participate in several interviews with the state,
pay a fee of over $2,000, obtain a certificate of renunciation, and pay an
“expatriation tax” on one’s entire wealth. The relevant legislation also
requires publication of one’s name in the Federal Register, meant to “shame”
those who expatriate, and expatriates can be barred from entering the U.S. if
the state determines that they expatriated to avoid U.S. tax legislation
(generally the main reason for most!).]

A derivative of this statist line of reasoning is that, if you can reasonably
move to another state, statists argue “Well, choosing to stay here indicates
you have chosen this state over another state.” However, this is a false
choice. Imagine if someone credibly threatened you with incarceration but gave
you the choice of cage A or cage B; if you choose cage A, that only indicates a
preference for cage A over cage B, but it doesn’t indicate consent to
incarceration itself.

*Sixth* , why should you have to move? Why shouldn’t the coercive state move
out (either physically, or metaphorically by leaving you alone footnote:[One
way to effect this governance separation would be through secession, which I
discuss in more detail later in this paper.])?  Of the two parties ‒ you and
the state ‒ it is the state that is forcibly asserting authority. Why should it
get to stay? Those around you who explicitly want to live under the state’s
rule can continue to do so, but why should their actions bind you?

If you’re born into a neighborhood in which the Mafia requires payments from
you to “protect” you, and where the understanding is that if you don’t make
these payments the Mafia will lock or beat you up, if you continue to live
there are you deemed to be consenting to this protection racket?  footnote:[The
astute reader will note that the state is no different from the Mafia in this
respect.] Maybe you just want to live in the place with which you are most
familiar.

If a child gets threatened in the lunch cafeteria by the school bully every
day, does the child’s continued use of the cafeteria evidence his consent?
Maybe he just wants to eat his lunch in peace and is hoping the bully will
cease, or be forced to cease, his bullying.

The statist’s argument that if you don’t leave you are deemed to consent to the
state’s actions is subject to the same refutation as the mugger demanding “Your
money or your life”: just as you have the right both to your money and your
life, so too you have the right both to enjoy your private property and not be
coerced by the individuals at the state.

=== Using State Services

“Ah,” the statist says, “but if you use the local roads, fire department and
garbage services then you must be deemed to consent.” There are several
problems with this argument.

*First*, this argument misses the point that you have no choice in the matter.
Since the state has arrogated to itself the responsibility of providing roads,
fire departments, garbage disposal, etc. , and prohibits competing suppliers,
you don’t have the option to purchase these services from other suppliers (or
not to purchase them at all).

*Second*, the argument also overlooks the fact these services are supplied
using money forcibly confiscated from taxpayers in the first place. How can one
party do something wrongful, and then claim that action as the foundation for
evidencing implicit consent from the wronged party?

If the Mafia were to build local roads from protection money extorted from
local businesses, and then claim that everyone using the roads is thereby
deemed to consent to the Mafia’s ongoing operations, even (some) statists would
reject that argument. Why is it different because the state does this?
footnote:[It would be a circular response for a statist to retort “Because the
Mafia is criminal but the state is legitimate.” We are here asking why the
state is legitimate when it does exactly what the Mafia does.]

*Third*, if a thief steals your television it is not wrong to try to take it
back. In other words, if the state confiscates your income via taxes, it is not
wrong to try to take back some of this stolen loot by using the state-provided
services that were funded with your confiscated income. The alternative is to
be looted and get no benefit from what was forcibly taken from you!

*Fourth*, even if one were to concede that if you use a state-provided benefit
this implies you have “consented,” at most this can only imply consent to the
provision of the specific benefit in question. Why should it also imply consent
to the whole state infrastructure and every single act performed by the state?

[centered]#* * * * *#

When faced with the above arguments, statists often fall back to the question
“Well, how would anything get done if we didn’t have a state?” That is a
reasonable question to ask, but it is not a valid argument for the state’s
legitimacy or anyone’s implicit consent to the state. Rather, that question is
a utilitarian one, and there are significant bodies of intellectual writing and
historical evidence that suggest potential answers (which will be discussed
later in this paper). What the statist is implicitly saying, however, is that
if he can’t imagine how things would get done in a voluntary society, the
default response must be to use coercion.

Asking about the state’s legitimacy is a moral question. Just because the
statist cannot conceive of how things might get done without a state doesn’t
lend moral legitimacy to the state. As libertarian attorney Stephan Kinsella
has noted, imagine being in the Soviet Union before it collapsed and debating
the morality of communism: if someone were to ask “Well, who would produce the
toothpaste if the state didn’t, and how many varieties would there be?” and the
answer given was “We don’t yet know,” would that be the end of the argument,
thereby providing the moral foundation for communism?
