== Myth #3: The State Acts For The “Common Good”

Statists believe that individuals at the state act for the “common good of
society.” footnote:[Other renditions include for the “general welfare” or the
“public good.”] This phrase is thrown about loosely without a lot of thought.

=== Who Can Define The “Common Good”?

In the U.S. there are over 315 million people. A “society” is not a discrete
creature whose objectives can be defined; it is nothing more than many
individuals living in proximity to one another. Each person has a unique
personality and unique skills, life objectives, perceptions and needs. What he
wants out of life is known only to him and his wants may change continuously.
No one other than this person can really understand his perspective.

If this is all true, then the obvious questions to ask are: what is the “common
good of society” and who can possibly discern this? Even if we used the most
powerful super-computer in the world, it would be logically impossible for this
device to sketch out what is the “common good” and to keep this current with
changing perspectives of millions of people. Does anyone really believe there
is a linear programming solution that can find a set of objectives that
satisfies everyone’s unique desires at once, and that can update itself
continuously as those desires change? And yet we don’t even rely on such a
machine; according to statists, the individuals in government are omnisciently
able to define the “common good.”

In fact, what statists are really saying is that they are willing to let the
few munificent beings at the state define what those beings regard as the
“common good,” and then force a change in behavior among the rest of us to fall
into line with that definition. However, what about those of us who don’t agree
with this definition or with this process of creating the definition?

In addition, one needs to believe in one of the Tooth Fairy Theories to believe
that the “common good” will be defined by those at the state as what is good
for the population at large instead of what is good for those at the state.

=== Do Elections Help?

One statist response may be that voters are not simply letting politicians
define the “common good” by themselves, since through the electoral process
politicians are elected with their constituents’ definitions in hand.  However,
which politician’s campaign platform maps precisely with every unique
constituent’s personal definition of the “common good” (this is even harder to
answer when one considers those who voted against this politician and those who
did not vote at all), and which politician once elected acts faithfully to his
campaign platform?

Further, each politician is only one member of this group of “common good”
definers, and it’s not even clear that this group of beings can agree among
themselves. The state comprises individuals from different parts of the
political spectrum from different geographical areas in different branches of
government, all disagreeing with one another all the time.

Even if we fantasize that this group of beings at the state could agree on a
definition of the “common good,” they never actually set out what their
conclusions are at the finish of each election so we can decide if we agree and
subsequently track if they are acting in accordance with that definition.

In addition, the composition of this group changes with each election. Does
this mean that each newly elected group coincidentally arrives at the exact
same definition of the “common good” as the previous group or, if not, does
this mean that the definition changes with each election? If the latter, does
this map well with each voter’s changing perspectives, meaning that each voter
coincidentally changes what he wants out of life only each election date and
not in the interim?  footnote:[To the statist who responds that it is
impractical to have continuously changing definitions of the “common good,” and
that once an election cycle is the best we can hope for, I would respond that
this is precisely an argument for the stateless society.  In that society, each
individual can continuously change and acquire his preferences at his own pace,
regardless of what others want, without coercing others into his regime nor
being coerced by others into theirs. Just because the statist cannot imagine a
better system doesn’t mean such a system cannot exist.]

=== “Majority Good,” Not “Common Good”

If, at the finish of each election, the elected group of politicians did
articulate its definition of the “common good,” what happens if one citizen
disagrees with this definition? Doesn’t a single person disagreeing with the
state’s definition of the “common good” mean that, by definition, it is not the
“common good,” since it is not satisfying everyone’s objectives at once?

To the statist, however, this is not a problem, for the statist is willing to
accept “majority rule” as the philosophy behind defining the “common good.”
However, this is a logical contradiction: what is being defined is not the
“common good” but the “majority good” (and, as noted above, really not even
that).  footnote:[In addition, as explained by the “public choice theory” part
of economics, it’s not even clear that the majority view prevails in political
deliberations. The sequence in which proposals are put up for debate and vote,
and the framing of those proposals, impact the actual outcome, which does not
necessarily match the alleged preferences of the majority. The individuals who
control the proposal process have a huge impact.]

Yet if all men are regarded as equal in terms of how they may conduct
themselves vis-à-vis others, then it must be morally wrong for two men to force
a third to accept that what is good for them is good for him too, whether he
likes it or not.
