== Myth #13: The “Hobbesian Fear”

Probably the most common reason a statist will cite for the need for the state
is what is known as the “Hobbesian fear.” This refers to the concept that,
without a state, everyone will be at constant war with everyone else because
this is man’s nature.  footnote:[This is a loose rendition of the principle
articulated by the English philosopher, Thomas Hobbes, in his 17^th^ century
book, _Leviathan_. Hobbes is often credited with creating the thought process
behind the modern state.]

Under this line of thinking the only way to prevent this constant state of war
is to have a strong state, which is defined as an entity with a legal monopoly
on the use of violence in a given geographical territory. This state would use
force to prevent citizens initiating aggression against each other (as well as
to protect them from foreign aggressors). To keep the peace, the state would be
the only entity entitled to adjudicate disputes in its territory, including
those in which the state itself is a party to the dispute. In order to fund its
operations, the state would be able to levy taxes on its citizens.

At this point a number of rather obvious objections to this line of thinking
should be jumping out of the page.

*First* , it’s important to recall that “the state” is not an entity that can
actually act by itself; only individuals can act.  Thus “the state” is just a
codeword for a select group of individuals.

Re-framed that way, what the Hobbesian argument is actually saying is that in
order to prevent A from initiating or threatening aggression against B or his
property, and vice versa , S is required to “keep the peace.” However, what is
it that S is actually doing? Assuming either A or B has not explicitly
consented to this arrangement (as to which see the discussion earlier in this
paper), S is forcibly expropriating some of the income of A and B (in the form
of taxes) and forcibly telling A and B how they may live their lives and what
they may do with their property (in the form of regulations). In other words, S
is himself initiating or threatening aggression against A and B and their
respective property.

This creates a self-contradiction: the property protector is actually a
property expropriator and violator. S might be bringing safety and security
between A and B footnote:[Although this assumption is dubious given that, as
discussed earlier in this paper, A and B will now lobby S aggressively to rent
his coercive powers in their favor.], but the cost of this is S doing to A and
B what they are no longer allowed to do themselves. Thus we’ve simply
substituted one Hobbesian danger for another.

That S does to A and B what S is supposed to be preventing A and B from doing
to each other in the Hobbesian world is best illustrated by how the state acts
against its own citizens when it is engaged in hostilities with other nations,
ostensibly protecting its citizens against external threats.  footnote:[Never
mind that most of these threats, if real, are caused by the state’s prior
interventions overseas or, if not, are self- serving, falsely portrayed
“crises.”]

For instance, in the U.S. the state has always used war to expand abuses
against its own citizens: enslaving citizens through conscription to fight its
wars (during the so-called “Civil War” footnote:[This is a misnamed conflict. A
“civil war” is when rival factions are fighting to seize control of the
country’s government, which was not the case in this conflict; rather, the
federal government went to war against the seceding southern states. More
factually appropriate names include the “War of Northern Aggression,” the
“Second War of Secession” (the first being the American Revolutionary War) and
the “War to Prevent Southern Independence.”] , World Wars I and II, the Korean
War and the Vietnam War); outlawing criticism of the state and its key
personnel, including censoring or closing down the press (through the 18^th^
century Alien and Sedition Acts; by President Lincoln and his supporters during
the “Civil War”; and again by the federal government in World Wars I and II);
harassing, incarcerating, plundering, torturing and executing people supporting
or merely suspected of supporting the enemy (by President Lincoln and his
supporters during the “Civil War”; the internment of those with Japanese
backgrounds during World War II; the harassment of those suspected to be
Communists during the Cold War; and, as part of the “War on Terror,” using
drones to execute Americans deemed by the president to be appropriate targets);
covertly tapping into private network communications under the pretext of
needing to ferret out the enemy within (most recently with the PATRIOT Act
powers and National Security Agency eavesdropping) footnote:[Statists will
often respond that “If you’re not doing anything wrong, why do you care if the
state monitors your private communications?” The problem is that “wrong” is
defined by statists as an action or omission that the state arbitrarily defines
as illegal at any point in time, as opposed to an actual act of violence
against someone’s person or property. Thus the state can use these intercepted
communications to take direct action against someone for a victimless,
regulatory “crime” (or, more broadly, to pressure someone to act or refrain
from acting by threatening to disclose legitimate but nevertheless private or
personally embarrassing information or activities).] ; and increasing the
forced confiscation of its citizens’ income to pay for these hostilities
through higher taxation.  footnote:[Taxation can be levied in one of three
forms: direct, current taxation (the least politically feasible); deferred
taxation through present borrowing (requiring future taxes to repay the debt);
or implicit taxation through inflating the money supply (the most politically
feasible since it is the least discernible, which is why states jealously guard
their monopoly on money printing).]

Note that the alleged “external threat” identified by the state as a pretext
for its actions can sometimes simply be an inanimate object, such as in the
“War on Drugs.” Many of the state’s abuses listed above are now regular state
actions in this faux war. The state’s police are now highly militarized and
engage daily in many violent raids on its citizens’ properties in search of the
nefarious illegal narcotic, leading to death, injury and property destruction.
footnote:[Even some of the glorified American Founding Fathers were guilty of
this type of thing. In 1807 President Jefferson implemented an international
trade embargo on private U.S. citizens in response to British aggression; his
successor, President Madison, then implemented some legislation to strengthen
enforcement, allowing the military to raid U.S. merchants and seize goods on
the mere suspicion they were intended for export.]

In addition, the state’s police track citizens’ movements footnote:[In early
2015 the U.S. government’s program of capturing citizens’ license plates to
track their movements around the country came to light. Ostensibly this
database was first established as part of the “War on Drugs” but, as is often
the case, it is now being shared broadly among various law enforcement arms for
other reasons.] , seize their property, and generally ruin their lives for
countless other victimless “crimes” which do not involve any act of violence by
its citizens against each other.  These “crimes” are merely violations of
arbitrary state-created regulations whereby the state tells its citizens how
they may live their lives and use their bodies and property.

The power to control the population is a powerful drug for individuals at the
state, but they need to keep coming up with new pretexts to keep “selling” this
to the population. This is why the state is forever creating hysteria over
“crises” where they can roll out “experts” to show that the probability of
death, destruction and/or misery without state action is many times larger than
it really is. Consider how the state has used the swine ‘flu, Y2K, the
occasional mass shooting, 9/11, global warming/climate change, inequality,
racism, Ebola and, most recently, ISIS, to try to justify significant action by
the state to forcibly interfere in citizens’ lives.

So, given all of this, I say thank heavens for S! Where would A and B be
without him?

*Second*, in what other area of life does it make sense for one man to allow a
second to adjudicate disputes between the two of them, and for the second to
tell the first how much it will cost him for this alleged benefit?  The fact
is, no man in his right mind would explicitly agree to this type of
arrangement.

*Third*, the argument claims that the “true nature” of man is to war with his
fellow man instead of first looking for a way to peacefully resolve disputes.
However, S is just as human as A and B. Thus if the “true nature” of A and B is
to be at each other’s throats, that must also be true of S. Why then does it
make sense for S to rule A and B?  footnoteref:[unless,Unless one believes in one of the
Tooth Fairy Theories.]


*Fourth*, we ought to question the assumption that man’s “true nature” is to
war with or otherwise aggress against his fellow man. It is clear from everyday
life that the vast majority of people do not commit violent crimes against
their fellow men or their property even when there is little to no risk of
getting caught. It is not the fear of punishment but an innate sense of right
and wrong that produces this outcome.  footnote:[Conversely, most people will
do good things even if they aren’t forced to do so, such as leaving tips,
giving to charity, helping a neighbor, etc.]

Moreover, if the Hobbesian assumption were true, mankind would have died out
long ago; the fact that it hasn’t, even when there were no states, shows that
man is capable of devising non-violent means to resolve disputes.

The fact is that most of the large scale violence in human history has involved
one man as head of a state (whether a king or a president) requiring other men
to wage his wars for him; most men do not want to actually get into a physical
altercation themselves with other men. Absent forcing other men to do his
bidding and bear the cost, man has long reasoned that it is personally safer
and cheaper to avoid violence in disputes and to establish norms to settle them
peacefully.

As much as we are troubled by individual violent crime, it still constitutes a
very small percentage of human activity. State-caused violence – external war
or internal repression – is a much larger source of death in the world than
individual crime because the individuals in charge of the state don’t have to
get involved in the actual violence or directly bear its cost.

*Fifth*, if we need a state to prevent the initiation of aggression among
citizens, shouldn’t we also require a state to prevent the initiation of
aggression among states? Those at the state are human too and thus aren’t they
also highly prone to initiate aggression against other humans in other states
if there is no world government?footnoteref:[unless] In other words,
if the “Hobbesian fear” argument is true, how can there ever be more than one
state in the world?

Yet if you ask anyone who is part of the state if they too should be governed
by a higher power the argument is a resolute “no.” They point to the concept of
state sovereignty: internationally, all states are equal, none can rule over
another, and all actions between states are generally worked out by consensual
agreement. Yet remember, these states are just collections of humans. In other
words, those at the state believe they are equal with, and can work things out
peacefully with, their fellow statesmen, but they don’t believe their own
citizens can work things out peacefully among themselves.

If these individuals at the state regard themselves as having sovereignty
vis-à-vis other statesmen, meaning the full right and power to govern
themselves without any interference from these other men, then why can’t all
individuals within a state be similarly regarded? Is there something magical
about a geographical area known as a “nation-state” such that within this area
there is no individual sovereignty but as between different geographical areas
there is?

*Sixth*, if the “Hobbesian fear” is truly the justification for the state’s
legitimacy, then the state should be strictly limited to two activities,
namely, preventing violence against its citizens and resolving disputes;
essentially, police, courts and national defense. Yet the modern state
undertakes hundreds of activities costing billions of dollars per year that
have nothing to do with “keeping the peace.” Perversely, many of these
activities involve outlawing non-violent activities by citizens (regulatory
“crimes”). Thus the state has grown well beyond its alleged Hobbesian
rationale, rendering this argument even less credible.
