== Myth #10: We Need The State To Provide “Public Goods”

=== The Theory

Another fallacious belief purportedly justifying the state is the notion of
so-called “public goods.” footnote:[I will use the phrase “public good” in
quotation marks to indicate that, when one considers it logically and using
credible economics, this is not a separate category of economic good.] 
As the theory goes, private firms wouldn’t produce these goods for one of two
reasons.

*First*, because of the so-called “free rider” problem, namely, private firms
wouldn’t be able to prevent people from benefiting from these goods without
paying for them. Commonly cited examples of these goods include lighthouses,
national defense and police.

*Second*, because these goods are just too difficult for the private sector to
handle: they require complex arrangements or huge amounts of capital, and
profits would be too hard to generate or would be too distant in the future.
Examples of these goods include roads, schools, money, courts, railroads, power
and scientific R&D.

Actually, for many of these goods the statist argument goes further: not only
must the state produce these goods, but it must do so as a monopoly, i.e., it
must prohibit others from trying to produce competitive goods.

It’s hard to know where to start in refuting the many fallacies bound up in
these assumptions.

=== History To The Contrary

Probably the easiest place to start is to review history. Every single good
that statists now claim is a “public good,” and thus must be produced by the
state or else it would not be produced at all, has at one time or another been
produced privately until the state forcibly intervened. In addition, in
different parts of the world many of these goods are still produced privately.
In other words, the private sector has not found providing these goods to be
too complex, too capital intensive or too distantly profitable.

For instance, lighthouses were originally provided by the private sector before
the state took them over. Similarly, originally roads were privately built, and
there are still many private roads in gated communities, strip malls, office
parks and private cities. Schooling was originally private until the state
intervened, and private schools still exist and are growing globally (even in
the poorest slums in the Third World). Originally policing was private, and
there are now more private security guards than state police in the U.S.; in
addition, when private citizens are free to carry personal firearms they are
more effective at preventing crimes against themselves than the police are.
footnote:[As noted earlier in this paper, when a violent crime occurs we can
only guarantee that there are two people present: the aggressor and the victim.
The police are hardly ever there. Thus armed potential victims are much more
successful at preventing such crimes than the police can ever be.  The supposed
argument is that there are some goods that no private firm would supply at all
or that wouldn’t be supplied in sufficient quantities by the private sector,
but which are beneficial to society, and so the state must forcibly direct
resources towards the production of these goods and provide these goods
itself.] Law and courts originally developed from the ground up before states
took them over, and private mediation and arbitration are growing as forms of
dispute resolution. The first successful railroad in the U.S. was privately
built, and there are privately run railroads globally. Money was historically
developed privately before being taken over by the state for its own ends. Walt
Disney World is an entirely privately constructed and privately run “village”
with its own security, roads, immigration rules, etc.

=== Why Insist On A Monopoly?

Even statists accept that monopolies are bad because they lead to higher prices
and less innovation compared to when there is competition. If so, then why
would the statist argue that the state must monopolize the production of a
“public good”; what would be the harm in allowing genuine competition? If the
statist is correct, namely, that the private sector would not produce such a
good, then the statist should not be concerned if the state doesn’t outlaw
competition.

Note, however, that what I am advocating is real competition, where consumers
can opt out of paying for the state’s “public good” and instead purchase only
the competitive private good. There is no real competition if the state
forcibly extracts payment from all consumers for its “public good” in the form
of taxes, but allows competitive suppliers to also produce the same type of
good. This puts these suppliers at a tremendous disadvantage, since it raises
the effective price to consumers of the private good because the consumer has
to pay for the state’s “public good” via taxes and then also for the supplier’s
good.  footnote:[The classic example of this is education. While the state
notionally allows private schools to exist, the consumer who wants to send his
child to a private school has to pay twice: once through his local property
taxes for the public schools and then again for the private school tuition.]

In addition, as noted earlier in this paper the state is not concerned with
profitability because it can force taxpayers to fund its losses. Thus the
explicit prices of state-provided “public goods” are typically set well below
the prices of competitive private goods. This makes the state a formidable
competitor to private sector suppliers.  footnote:[Typically the explicit price
for “public goods” is zero, but of course to calculate the true economic price
one must factor in the taxes paid to fund such goods.]

All of this generally means that private sector goods which compete with the
state’s provision of “public goods” are well out of the reach of the less
well-off. Only the wealthier citizens can afford to purchase competitive
private sector goods (which tend to be of much higher quality), while the less
well-off are left to consume the state- provided (lower quality) goods.

=== The “Free Rider” Concept

The most fundamental point relating to “public goods,” however, is that
statists cannot convincingly answer the question “Which goods are ‘public
goods’ and which are not?” Often times the statist’s response is to look around
at which goods the state produces today and cite those goods. However, that is
circular reasoning. The question is asking for the principles underlying
exactly which goods should be produced by the state and which should not; just
because the state is currently producing a good doesn’t provide any principled
argument for the necessity or morality of its production by the state.

As noted above, the statist’s most common justification for “public goods” is
the so-called “free rider” problem.  However, there are both moral and
practical issues with using this as a workable principle.

In terms of the moral issue, what the statist is saying is this: I want this
good but you can benefit from it even if you don’t pay for it, so I’m going to
force you to pay for it. The libertarian and moral counter-argument is this: I
don’t want this good and so why should I be forced to pay for it just because
you want it and can’t figure out how to exclude me? If A wants something and B
doesn’t, morally why should A have the right to force B to pay for it? B is not
asking for this “free” benefit to be bestowed upon him. Isn’t it A’s problem if
he can’t figure out how to exclude B from the benefit?

It is more likely that (statist) A is really saying this: I want this good but
can’t afford it myself, so I’m going to enlist the state’s help in forcing
others to contribute so I can get what I want.

In practical terms, the “free rider” principle is capable of expanding the
range of “public goods” to absurd levels.

If a company provides a significant number of jobs in a local community, this
provides certain benefits to that community which flow from lower unemployment
(lower crime, greater vibrancy, etc.), yet the community is not reimbursing
that company for these benefits. Shouldn’t the “free riding” community be
obliged to pay for these benefits? If a person works on his front garden
extensively to make it beautiful, this certainly provides benefits to his
neighbors in terms of beautifying the street, yet his neighbors are not paying
for this. Shouldn’t they be obliged to contribute to the upkeep of his garden,
lest they “free ride”? If a person wears deodorant, this certainly provides
benefits to those commuters who are jammed up against this person on the train,
yet they are not paying for his deodorant. Shouldn’t these “free riders” be
required to pay? If a person pays a dog trainer to teach his dog how to behave
in public, those who come across this dog are certainly benefiting from that
training, but they are “free riding” on this person’s investment; shouldn’t
they be required to contribute? If a person installs smoke detectors in his
house to provide early warnings about fire, this certainly provides benefits to
those neighbors whose houses are close to his house (if a fire is contained
early it won’t spread to the neighbors’ houses), yet they are not paying for
these smoke detectors. Shouldn’t these “free riding” neighbors be required to
pay?

The point is, so-called “free riding” is everywhere. Yet statists conveniently
only choose to use this as a justification for the state’s provision of “public
goods” if the product is something they really want but can’t afford to
purchase for themselves and don’t think they can persuade others to voluntarily
pay for too.

=== The Statist Economist’s View

More technically, statist economists use fancier terms to try to create a
definition of and justification for “public goods.” They claim that “public
goods” are those which are both “non-rivalrous” and “non-excludable.”

_Non-Rivalrous_. The term “non-rivalrous” means one person’s consumption of the
good does not interfere with another person’s consumption of the good, so the
additional cost to the producer of allowing an additional consumer is perceived
to be zero. The statist economist points out that since (as he sees it) it
doesn’t cost the producer to serve an additional consumer, the producer should
be required to supply at full capacity without charging, because if he doesn’t
then society won’t be supplied with “enough” of the good (according to the
statist economist’s estimation). Since private producers would object to this
business model, the implication is that the state must be the producer of this
good (assuming the good is also non-excludable).  footnote:[Of course the idea
of the state not charging for any good is illusory. The state charges through
taxation but the charge is levied on all taxpayers as opposed to only those
individuals who consume the good.]


A classic example given is the less-than-full cinema. If the movie is going to
be shown at 80% capacity, the perceived marginal cost of admitting one more
patron is zero. However, this is problematic for a few reasons.

*First*, it is not true that admitting one more patron has no impact. The next
patron may be noisy, tall, smelly or too large to comfortably fit into just his
seat, and thus may adversely impact the other patrons’ experience.

*Second*, the next patron requires additional effort by the cinema in terms of
clean-up afterwards (this patron may contribute additional trash), and at some
point additional ticketing staff and security may be required as the number of
patrons grows.

*Third*, this principle is logically extendable to other situations which
illustrate the principle’s absurdity. For instance, if someone’s living room is
not filled to capacity should the house owner be expected to admit a small
group of strangers who want to have a discussion inside a comfortable space?
Would this justify the state taking over all houses that are not used to
capacity?

Other examples often cited include roads and the Internet. However, these
overlook that each person’s use of a road or the physical bandwidth of the
Internet “pipes” impacts others’ usage by “clogging up” the resource (as anyone
who has waited for a Web video to buffer can attest), and each person’s usage
also increases the “wear & tear” on, and therefore the maintenance costs of,
the equipment.

_Non-Excludable_. The term “non-excludable” is the fancy term for a good that
is subject to the aforementioned “free rider” issue. It means that the supplier
of a good cannot exclude any particular consumer from benefiting, even if the
consumer does not pay for the good, and thus, faced with this issue, private
producers wouldn’t produce the good at all as there would be no viable business
model. Therefore the state must be the producer (assuming the good is also
non-rivalrous).

The classic example given is the lighthouse. Once the light is shining out on
the water all ships out there can benefit from this, so how would the
lighthouse owner be able to charge for his service?

The problem with this line of thinking is that it is speaks of no logical
principle but, rather, simply a lack of ingenuity on the part of the statist
economist. Just because the economist cannot conceive of how to make a business
out of this service doesn’t mean that entrepreneurs could not come up with a
solution. In fact, historically lighthouses were privately owned. Ships and
their insurers voluntarily paid to ensure this service was provided because the
cost was very cheap compared with the potential loss of a ship and/or its cargo
due to a collision with another ship or rocks.

Consider also what happened with analog radio. While originally it was not
thought possible to exclude listeners from radio programming, radio station
entrepreneurs figured out a way to create a viable business model by charging
advertisers who wanted access to the radio station’s listener base.
footnote:[With advances in technology today, presumably digital radio signals
could be encrypted and thus listeners could be excludable, similar to how
satellite radio works.]

The critical point to note about goods that are supposedly “non-excludable” is
that, for the private sector to provide such a good, it is not necessary that
an entrepreneur can charge everyone who benefits. All that matters is that the
entrepreneur can produce the good at a lower cost than the revenue he can
generate. That’s where entrepreneurial ingenuity trumps the limitations of the
statist economist’s imagination.

The other key point to note is that statist economists overlook the fact that
the benefit of many of these allegedly “non-excludable” goods can be tied to
living in or visiting/using a particular territory (either physical territory
or intangible “territory,” such as the abovementioned radio programming). This
has two principal implications.

*First*, since people can be excluded from any territory, the benefits of such
goods are, in fact, excludable.

*Second*, if the provider of the goods in question also owns the territory,
then he can build the cost of providing such goods into the territory use fee
that he charges residents or visitors, on the basis that provision of these
goods enhances the quality of living in or visiting his territory.

So, for instance, a developer of a residential community could establish roads,
security, parks, etc. and then price the provision of these goods into the sale
price of individual plots of land and residents’ annual maintenance dues.  The
owner of a road could supply streetlights as a service to those who pay his
toll fee, which would incorporate the cost of providing such lighting. In the
case of the lighthouse example, since each ship ultimately calls into a port
and it is to the port’s benefit to provide its customers with light to make the
approach to the port easier, the port owner could easily build the cost of
providing the lighthouse into docking fees charged to ships.  footnote:[Or, if
libertarian thinking catches on and oceans are able to be privately owned, the
ocean owner could incorporate the lighthouse fee into the price of a permit to
sail in his waters.]


_Combining The Two Concepts_. As noted earlier, the statist economist only
classifies as a “public good” something which is both non-rivalrous and
non-excludable.

The classic example of what a statist economist would call a true “public good”
is national defense. However, even this can be shown to be a false assumption.

National defense is not “non-rivalrous.” “National defense” is a concept not a
product. Real resources are required to create a defense product, and thus the
question arises as to how much defense do we want and in what form?

Do we just want to protect the coastal states or the interior too? If we choose
the interior too then we need to spend more money than if we just protected the
coastal states, so the marginal cost of producing that extra defensive
capability is not zero. Do we want to protect citizens who are abroad or just
those who are in the homeland? If the former then we need to spend more money
than if we just pursued the latter. Do we want to offer citizens protection in
the air, in the sea or just on the ground? Each of those decisions entails
different costs.  Looked at another way, if a fixed set of protective resources
is deployed to cover a larger area or population, this will detract from the
quality of protection that would otherwise be provided to a smaller area or
group of citizens.

Neither is national defense “non-excludable.” It only appears so given the way
individuals at the state, in their infinite wisdom, have decided to provide
this good.

National defense is ultimately about protecting lives and property from damage.
Each individual and each piece of property could either be included in the
protection umbrella or not; private security agencies do this all the time, as
do insurers. Property, life and health insurers could offer their policyholders
compensation against destruction, death or injury from attack. If you bought
such a policy then you would get compensated if you suffered this type of loss,
and if you didn’t you wouldn’t. The insurers would then invest in defensive
capabilities to protect their policyholders, since done efficiently this would
be cheaper than making large payouts. As technology improves, the exclusion of
non-payers could become more precise.

A good illustration of this was provided by the operation of Israel’s Iron Dome
defensive missile system during the 2014 conflict with the Hamas group based in
the Gaza Strip. When Hamas fired a rocket into Israeli air space, Iron Dome
would calculate where the rocket would land and if it would do damage to houses
or people. If the calculations showed the rocket would be landing harmlessly,
Iron Dome would not fire off an intercepting missile; if the calculations
showed Israelis were at risk, Iron Dome would intercept and destroy the rocket.
One could imagine insurers offering this precision protection only to their
policyholders footnote:[In a similar vein, one could imagine a private
company’s “SEAL team” that would rescue only paying customers if they were
taken hostage overseas.]


The “non-excludable” argument is also belied by the fact that adjacent nations
have their own defensive capabilities. If it were true that national defense is
“non-excludable,” then neither Canada nor Mexico would bother having defensive
capabilities as they could just “free ride” on the coattails of the
capabilities of the U.S.  Similarly, it would make no sense for some states in
the European Union to have their own capabilities since they are all in close
proximity to other states on whose capabilities they could “free ride.”

Finally, to the extent there is some perceived “free riding,” the statist
economist overlooks the remedy of ostracization. Adjacent territories tend to
have significant commercial and personal interaction. If the citizens of one
territory had invested in defensive protection that might also benefit the
citizens of an adjacent territory, but the citizens of the adjacent territory
refuse to contribute to the cost of this protection, if it were very important
to them the citizens of the paying territory could threaten to reduce trade and
other interaction with the citizens of the non-paying territory. In this way
there would be some exclusion of benefits; not of the defensive protection, but
of other goods of equivalent value.  footnote:[To digress slightly, there is
also a self-contradictory element to arguing that national defense must be
provided by the state.  As noted above, “national defense” is essentially about
protecting human bodies and property from external aggression. Yet when the
state provides national defense, what does it do? It forcibly confiscates
property from individuals to fund its activities, and it may even forcibly
conscript individuals to serve in the armed forces. In both of these activities
the state itself, as the purported guardian against aggression, is forcibly
aggressing against bodies and property!]

=== How Much Must Be Supplied?

More broadly there are two fundamental problems with the concept of a “public
good” as a justification for state action. There is a practical problem and a
moral problem.

*First*, the practical problem. The “public goods” argument implies that there
is in fact a set, socially optimal amount of the good that must be produced.
The theory runs that if, in the state’s estimation, the private sector would
produce less than this level, then the state must step in. However, statists
never ask, much less answer, how one can derive this “socially optimal
production level” and who has the omniscience to do this?

In the private sector the “socially optimal production level” is pursued by
individual entrepreneurs trying to anticipate individual consumer preferences
based on pricing signals given to them in the market by individual consumers
and the owners of factors of production. As noted earlier in this paper, those
entrepreneurs who anticipate correctly and please voluntarily paying consumers
will make profits, and thus will be able to bid for more scarce resources, and
those who fail to do this will tend to go out of business, and thus will yield
scarce resources. Note that this “socially optimal production level”
continuously changes with consumer preferences and resource availability, so
entrepreneurs must continuously adjust.

Practically speaking, it is impossible for individuals at the state or their
economists to make a credible theoretical calculation in advance, or to adjust
on the fly, regarding the “socially optimal production level” of any “public
good.” State personnel cannot know consumers’ changing preferences since they
cannot know what is inside each consumer’s head, and nor does the state, as a
coercive monopoly, get any actionable, market feedback from consumers since
consumers are not making voluntary purchases of state-provided “public goods.”


In addition, if state personnel get the production quantity or quality wrong as
regards what consumers actually want, the state does not go out of business,
but rather continues to divert scarce resources into producing these goods away
from goods that consumers actually want.

Accordingly, in justifying the state provision of “public goods” the state can
only rely on models produced by intellectuals entirely divorced from the real
world.

Further, even if the state could know each individual’s preferences, how on
earth could it reconcile them into one production decision (this is analogous
to the “common good” issue discussed earlier)? Society is not a single consumer
but rather the aggregation of many individuals, and while the private sector
can satisfy all individuals concurrently through competing products, the state
(at best) can only satisfy a subset of individuals who are in favor of the
single production decision made by the state.

*Second*, the moral problem. Any time the state produces a “public good” it is
charging every single taxpayer whether that taxpayer wants that good or not.
Taxpayers do not have the opportunity to opt-out. By what right can the
individuals at the state tell each citizen that he must pay for those goods
that state personnel decide they want to produce? This means that state
personnel have a claim over the income of individuals superior to the claim of
those individuals themselves!

_Basic Science_. The typical statist claim that basic science is a “public
good” illustrates both of the above issues.  The statist believes that basic
science is a “public good” because it involves significant sums of money,
doesn’t always have a commercial payoff – either because not everything works
out or the benefits may occur too distantly in the future – and all of society
can benefit from scientific advances. Apparently these are reasons why the
private sector ‒ both entrepreneurs and philanthropists ‒ will not fund
“sufficient” basic science, and thus the state must step in to do this by
coercively diverting taxpayers’ money.

Just on its face the given reasons are not compelling: there are plenty of
projects that involve significant sums of money which get funded by the private
sector (e.g., constructing skyscrapers, and billion dollar purchases of
promising technology companies); the private sector is comfortable spending
money on uncertain outcomes, both in terms of quantity and time (e.g., the
development of new blockbuster drugs); and society always benefits from
advances in technology created by the private sector (which is why people are
willing to voluntarily purchase products that incorporate these advances).

However, there are deeper arguments against basic science being a “public
good.” Below I’ll focus on the core principled arguments and leave aside the
empirical evidence, of which there is plenty, that (a) the private sector has
historically funded enormous amounts of basic science and still does, and (b)
the majority of advances in technology have come not from basic R&D but from
applied R&D conducted by commercial enterprises under pressure to innovate to
beat out competition.  footnote:[This is all very well documented in Terence
Kealey’s book, _The Economic Laws of Scientific Research_.]

How can the statist know that the private sector wouldn’t fund “sufficient”
basic R&D? That implies that there is some objective definition of “basic R&D,”
some objectively identifiable minimum required amount, and some ability to
foresee what the private sector would and wouldn’t fund. From where does the
statist derive this minimum required dollar amount? Can the statist even
specify this amount, much less defend it? Can the statist specify which types
of basic R&D require which minimum amounts? No!

If the statist cannot credibly specify how much basic R&D is required, nor in
which areas, how can we know whether the state is even carrying out its stated
task sufficiently? Essentially it becomes an arbitrary “gut” calculation: the
definition of “sufficient” is the opinion of whoever is in power at any one
point in time.

This is not to say that any single person in the private sector knows the
answers either, but (a) the private sector is not coercively taking anyone’s
income when it hazards a guess, (b) the private sector is taking multiple
guesses at any one point in time since many people are simultaneously
personally funding their divergent ideas about basic R&D, and (c) those in the
private sector pay a personal financial penalty for guessing wrong and stand to
make a personal financial gain if they guess right, and thus the incentives are
much more aligned with guessing correctly over time.

The statist’s usual retort is to point to some beneficial development he
believes only came about through the state funding the basic research. However,
just because the state coercively diverted resources out of the private sector
towards state-identified research priorities doesn’t mean that this is
efficient or moral.  footnote:[More often than not the actual history of
development of such a good is contrary to what the statist would hope or was
taught. Often times the private sector was already funding or developing the
good anyway or the actual breakthrough came from private sector work. As noted
earlier regarding the Internet, for example, typically the state crowds out
private sector efforts and we are left with a sub-optimal state-backed
effort by default.]

There is nothing special about basic R&D spending. Like any other investment
that occurs in the economy, basic R&D spending just represents the allocation
of scarce resources towards an objective. Thus the same core principles apply
to basic R&D as to any use of resources in the economy. If the state funds this
good then it is engaging in central planning. It is diverting resources that
would have been used otherwise by the private sector, which has better
incentives than the state to use scarce resources efficiently and can better
take account of dispersed knowledge and preferences in the economy than can the
central planners with their “one-size-fits-all,” coercive approach.

It also means that the state is forcibly diverting resources away from
individuals in the economy who might have preferred to use their resources in a
different way. Some people might indeed be glad that the state diverted
resources to help develop a particular good, but not everyone might have seen
this as their top priority. No one was given a choice.

As noted earlier in this paper, statists don’t appear to fully appreciate the
notion of trade-offs. Given scarce resources it’s not the case that we can
spend on basic R&D without a cost; we have to give up something to devote
resources in that direction. So even saying “We should spend more on cancer
research” is not a reasonable proposition. We have to ask “Using resources
taken from what other activity?” To stay focused on R&D trade-offs in medicine,
spending more on cancer research might mean spending less on AIDS research.
footnote:[Of course the trade-offs are much broader than this. Spending more on
cancer research might mean spending less on food, shelter, clothing, education,
etc. We can’t know exactly what we are giving up, only that we are giving up
something.] How do we know that this priority reflects the preferences of each
individual whose money was confiscated by the state in this endeavor? The
individuals at the state cannot efficiently or morally make these decisions, as
they are making “either/or” decisions for everyone at once without knowing
their actual preferences.

State personnel react to political causes, which they can easily perceive and
benefit from, not to consumer preferences, to which they are blind. For
instance, whereas combating Ebola in Africa might become a hot political cause
leading to the state diverting resources into this area as politicians respond
to special interest pressure or polls, it could be the case that there is
actually very little voluntary demand for an Ebola vaccine and much more demand
for a malaria vaccine (malaria kills far more Africans than Ebola). These
actual consumer preferences would be thwarted by such state intervention.

In fact, given the incentives for those at the state to respond to the most
aggressive lobbying by those seeking to rent the state’s coercive powers, it’s
usually a very safe bet that the process by which basic R&D funding was created
was highly political. The politicization of this decision could manifest itself
in matters such as the choice of field to research, the specific scientists or
institutions involved, the geographic location of the research, the privileged
beneficiaries of the research, and the definition of the objectives and
benchmarks.

Consider the vast amount of societal resources diverted by the state to defense
companies in the U.S., some of which is spent on military R&D. Each year
billions of dollars are drawn out of the portion of the economy that serves
actual consumer preferences and are plowed into researching and developing
products the main purpose of which is to kill humans or destroy property. These
products are then used aggressively around the globe by the U.S. government in
activities having nothing to do with defending U.S. citizens against actual
threats to the homeland. That hardly satisfies consumer preferences.

Or consider the whole NASA space program. This was ramped up in the 1960s as
part of a testosterone-laced competition with the Soviet Union to waste the
most money in outer space, which in some way was supposed to express “national
pride” (as defined by the state). Neither the Soviet Union nor the U.S. has
ever derived any substantial, non-military benefits from their respective space
programs, yet we are continually told by the state that it is critical we forgo
our actual consumer preferences to fund this R&D. More likely the defense,
aerospace, electronics and communications industries have lobbied hard to
promote state spending in these areas on products they manufacture, the main
purpose of which is to allow the state to flex its muscles globally. Which
consumer preferences does this satisfy?

As a final example, consider how AIDS became a high profile political cause in
the 1980s, which meant that dollars were politically diverted into AIDS
research when in fact it might have made more sense to allow these dollars to
flow into other deserving areas. Taxpayers were never given the choice.

The last point to make about the basic science area is that, in addition to the
state’s R&D funding process being driven by politics, it also tends to be
driven by scientists who are not risking their own capital and thus who are not
concerned with any particular return on the funds invested; remember, these
funds represent scarce resources diverted from other uses in the economy. If
scientists want to “dream big” about breaking new frontiers without worrying
about returns, they and their supporters should “dream big” with their own
funds and not those forcibly taken from others. Let these scientists engage
with philanthropies or with private sector firms which don’t contract with the
state, and thereby raise the money to pursue their dreams from the voluntary
sector.
