== Myth #9: The State Is An Improvement On The Free Market

=== Inappropriate Benchmarking

The public has become conditioned to believe that if a market is not perfectly
competitive then it is broken, and this calls for state intervention.

The state, aided by its intellectuals, has convinced the population that
“perfect competition” should be the benchmark against which all private sector
entrepreneurial activity is to be graded. However, as defined, “perfect
competition” is never attainable, anywhere. It requires all firms in an
industry to have the same products, cost structures, information, market
shares, etc., so all they do is produce as automatons and sell to uniformly
demanding consumers. Just to state this is to explain why this is an
unrealistic view of human action. It takes no account of the realities of
individual subjective preferences, nor of continuous changes in consumer
preferences, resource availability and pricing, technology, entrepreneurial
insights and errors, etc.

More generally, however, this approach is misguided because it uses a
comparison between reality and perfection as the criterion by which to decide
whether the state should intervene; this is a common mistake made by statists.
There can only be one answer if that is the question asked. The more reasonable
question to ask is, which is better, reality without state intervention or
reality with state intervention?  footnote:[I’ve addressed this earlier in this
paper under the section dealing with the realities of the free market.]

=== Failure To “Keep Score”

Moreover, if the comparison between reality and perfection is the criterion
statists use to decide whether the state should intervene, this suggests that
statists see the state as the agent of perfection. Yet statists never go back
and ask whether state intervention has ever led to the nirvana for which they
were hoping, i.e., the standard to which they hold the private sector.

As discussed earlier in this paper, statists hold the state to a much lower
standard than they hold the private sector. Not only is the private sector
blamed when it doesn’t achieve outcomes statists (unrealistically) believe
should be attained, the private sector is also blamed when it reacts to state
intervention. In other words, the private sector can only do wrong. On the
other hand, statists never hold the state to any meaningful benchmark –
certainly not the perfection benchmark to which they hold the private sector –
so in their eyes it can never do wrong.  footnote:[Part of the reason statists
believe the state is an agent for good and the private sector an agent for bad
is that statists are suspicious of the profit motive, which the state does not
pursue but the private sector does. This suspicion simply reflects a woeful
understanding of (i) how profits are generated in the free market; (ii) how the
profit motive ensures resources get most efficiently allocated within society;
and (iii) the different and suspect incentives of those in the state sector.]

If the state hasn’t achieved its objectives with a particular program, the
usual answer given is that the state is not large enough, i.e., the solution is
that we need more regulation and/or taxes. Yet no state program ‒ every one of
which starts out with absurdly lofty objectives such as “We’re going to
eradicate poverty” or “We’re going to ensure everyone has health insurance” ‒
has ever been declared successful such that it can be shut down. With that
track record you would think statists would conclude that the state is awful at
estimating problems or awful at solving them, or both.

As noted earlier in this paper, if the state is the statist’s solution to
“market failure,” why isn’t the market the statist’s solution to state failure?

The most the statist will ever admit is that, in some areas, the state needs to
be reformed. However, statists never ponder that perhaps the state is
inherently incapable of being reformed given that its personnel are able to
exercise unrestrained coercive powers and have incentives and knowledge
misaligned with maximizing the satisfaction of wants among the population. When
the statist says “We need to reform government” what the statist is saying is
that we should plead with those exercising power “Please sir, make yourself
better. Only exercise your power omnisciently and magnanimously.” The state
metaphorically must chuckle at this plea.

Yet in the private sector no such pleading is necessary. If consumers don’t
like what a firm is producing they put it or its relevant product out of
business by abandoning it; witness, for instance, the respective fates of the
Ford Edsel, Wang Computing, New Coke and Blockbuster Video.

Yet there is no way to effectively abandon the products produced by the state,
no matter how bad they are.

=== Incorrect Analysis Of Causation

The public has also been trained by the state to look at imperfection in the
world and blame the “free market” (which, as previously explained, doesn’t even
exist, so the fault is misdirected), and then to believe that only the state
can make things better. There are two fundamental points to make about this
conclusion.

*First*, as previously discussed, the world is imperfect because of human
imperfection and scarcity of resources.  Neither issue is the fault of the free
market and nor can the state solve either issue. It is difficult to comprehend
why the statist would believe that the imperfect human beings running the state
can be a better solution to the imperfect human beings involved in the private
sector.  footnote:[Assuming one does not subscribe to one of the Tooth Fairy
Theories.] And it is equally hard to comprehend how entrepreneurs organizing
scarce resources to meet consumer preferences, with the risk of going out of
business if they get it wrong and the upside of personal profit if they get it
right, can be bested by central planners at the state who neither have the
necessary knowledge of consumer preferences nor the incentives of
entrepreneurs.

*Second*, and not surprisingly, statists have been taught a version of history
which credits the state with most positive developments in the human condition
and blames the private sector for all negative aspects. Statists then take this
mistaken view of history and apply it to all current problems, so the only
possible result can be a call for state intervention. However, this shows a
poor appreciation of economic principles and history.

*_Sweatshops_*. To give a classic example, statists will bemoan the operation of
sweatshops in poor countries and regard this as a problem with the free market.
footnote:[Similarly, statists regard the sweatshop labor that was an early
feature of the Industrial Revolution as an example of the dangers of the free
market.] They reflect on their better personal situation and demand that we
somehow stop sweatshop labor elsewhere in the world because “I wouldn’t want to
live that way.” This ignores a number of key facts.

*First*, sweatshop labor is a feature only of poor countries and, these days,
countries tend to be poor mostly because of heavy state intervention. Most poor
countries suffer from central planning of the economy, regulations that make it
unattractive for foreign capital to be invested locally (e.g., high taxes,
exchange controls, complex bureaucracies that firms are required to navigate,
etc.), and dismal health care, education and banking sectors due to significant
state control.

*Second*, generally sweatshop labor is not forced labor (if it were then the
statist’s concern would be valid). The companies employing these workers are
not using armed personnel to round up the workers each morning and march them
to the factory floor; these workers are voluntarily choosing to work in the
factories. This means that, as bad as the working conditions might be, they
must be better than the alternatives these workers face, otherwise why would
the workers turn up each morning?

*Third*, these workers’ families live in abject poverty and face a miserable
existence. The traditional alternative for these workers is to engage in
backbreaking and dangerous agricultural labor on the family farm to eke out a
subsistence, or, failing that, to turn to prostitution, begging or violent
crime to generate income.

Thus when statists insist that sweatshop labor be made illegal or that the
employers be boycotted out of business, they are likely pushing these workers
into these less than savory alternatives; in this light, factory work is a
relative “luxury” for these families. From statists’ unique vantage point
thousands of miles away, and based on their own existence and values, they are
seeking to impose their view on what is the “better” choice for these workers
without appreciating the actual alternatives that reality (or state
intervention) has served up to these families.

*Fourth*, as noted earlier in this paper, basic economics teaches that the
upper bound on what employers will pay workers is based on their productivity
level (why would an employer pay a worker $2.00 per hour when the worker can
only add $1.00 per hour of value?), and the lower bound on compensation is
based on competition, as employers must compete for workers and so cannot
underpay them relative to their alternatives. The usual reason sweatshop
workers are paid so little is that their upper bound is quite low because they
are lowly productive. The reason for this is twofold: they aren’t well trained,
and there is insufficient capital available locally to make them more highly
productive.

In the free market, as foreign entrepreneurs begin to invest in the local
economy, given its cheap labor, they make more capital available (through
machines, processes, training, etc.) to make these workers more productive and
thus able to command higher wages. Provided there is free competition for these
workers, employers will compete to hire and retain the more productive workers
through some combination of higher wages and better working conditions. That is
the only sustainable way for wages and working conditions to gradually improve
(even though statists believe that these things can improve simply by the state
commanding that this be so).

Statists will often retort that the state should accelerate this process by
forcing employers to pay higher wages and offer better working conditions more
quickly than things would naturally evolve.  footnote:[This is often pursued by
statists in a First World country lobbying their government to impose trade
restrictions on exports from these Third World countries unless these countries
bring their labor standards up to those demanded by these activists. It can
also be pursued via private citizen boycotts which, while misguided (for the
reasons to be discussed), at least don’t involve state-imposed coercive
restrictions on free trade.] This is labeled a “moral imperative” to improve
these workers’ lives. However, there are a few problems with this line of
thinking.


*First*, statists ignore the fact that sweatshop wages are often significantly
above poverty-level income in these regions, and even compare well with average
incomes, making sweatshop employment a step up the local career ladder for
those who take these jobs. Rather than bemoaning these opportunities for these
workers, we should be supporting them if we care about allowing these workers
to pull themselves up out of poverty.

In fact, history shows that sweatshops are an important positive development
for the poorest in emerging economies as they evolve from subsistence
agriculture to the living standards we enjoy in the First World today: this was
true in England during the Industrial Revolution, then subsequently in the
U.S., and then more recently in the “East Asian Tigers” of Hong Kong,
Singapore, South Korea and Taiwan.  footnote:[Even more promising is the fact
that each of these evolutions was faster than the prior one due to the
increasingly rapid pace of global trade and capital flows.] The same can be
expected in the sweatshop economies of Central America and other parts of Asia
if they are allowed to run their natural course too.

*Second*, those at the state cannot possibly appreciate the economics of each
employer nor each employer’s market. Statists incorrectly assume that just
because a business has an existing profit margin the entrepreneur will
voluntarily absorb higher costs imposed on him by the state. Yet all economic
decisions are made at the margin.

The entrepreneur has choices as to what to do with the firm’s capital, which
production processes to use, where to locate, what mix of labor and capital to
use, etc., and he will have a view on what is an adequate return for the risk
he is taking. If labor costs (cash wages, benefits or working conditions) are
forcibly increased at the margin, the entrepreneur will adjust to counteract
that increase to try to preserve his profits. For instance, if cash wages are
forced up by legislation, the entrepreneur may reduce working conditions or
benefits such as free meals, air conditioning running time or vacation days;
more generally, he may substitute machines for labor or he may relocate to a
cheaper region (in either case having the effect of reducing the cash income of
the workers who desperately need it). An entrepreneur who was contemplating
opening up in the region may reconsider his decision in light of the higher
costs, thereby adversely impacting those poor workers in this region whom the
entrepreneur might have hired.  footnote:[That said, it’s worth pointing out
that often times if there is one large employer in a region that employer may
actually support the state imposing these higher costs on all employers, since
this increases the entry costs for, and thus reduces the number of, potential
new competitors (another instance of crony capitalism). The incumbent may
figure that this dampening of competition is worth the additional labor costs
(or he may already be offering these higher wages or better benefits or working
conditions to his employees, so the new regulations won’t really impact him).
The incumbent may actually help write the regulations to ensure they are tough
enough to keep competitors out but not so tough that the incumbent would have
to change what he does. This is also why large employers support minimum wage
laws; often they are already paying their employees more so the law only
impacts would-be competition.]

As noted earlier in this paper, the only sustainable ways to improve a worker’s
plight are to improve the two factors that bound the compensation a firm will
pay him: at the lower bound, facilitate increased competition for workers by
reducing the costs for new firms to enter the market and for existing firms to
remain in the market (mainly by reducing or eliminating taxes and regulations);
at the upper bound, facilitate increased worker productivity by reducing
restrictions on physical and human capital investment (mainly by reducing
restrictions on education, capital flows, taxes on capital, etc.).

*Third*, employers look at the total cost of employing a worker relative to his
productivity but are agnostic as to how that cost is distributed among (a) cash
wages, (b) benefits (vacation, health care, etc.) and (c) working conditions
(safety, air conditioning, etc.).

Accordingly, in a free market the mix of cash compensation, benefits and
working conditions that an employer offers his workers tends to reflect
workers’ choices because employers will have to offer the best mix of these
factors to keep the best workers satisfied. Often times the poorest workers are
first interested in cash, which they can use to buy food, clothing and shelter
for their families, and they are willing to forgo benefits and better working
conditions to maximize cash. As their productivity increases and thus so too
their ability to command higher compensation, beyond some level of subsistence
cash they may start to demand better working conditions instead of more cash.
At still higher levels they may demand more vacation time or health benefits
instead of more cash or better working conditions.

The key point is that the individuals at the state are in no position to second
guess the mix of compensation components that workers desire. Those statists
who try to force improvements in wages, benefits and/or working conditions on
employers in these regions are simply imposing their compensation component
preference rankings instead of allowing employers to respond to their workers’
actual preferences.  footnote:[If the statist is so sure of his arguments that
it’s economically possible to improve workers’ conditions beyond what is being
offered by firms actually operating in a market, why doesn’t the statist either
start his own business in that market or offer to buy out the factory in
question and then offer those working conditions (or send his cash to those
workers directly)? The response that it is too difficult and complex for the
statist to do that, and that the statist isn’t really familiar with running a
business or with the particular industry or region in question, is the key
economic argument against the statist’s demand that others do what he wishes!
It’s easy to be an armchair entrepreneur and command others to do what you want
with their capital. As described, there is a private sector solution to the
problem perceived by the statist, but to the statist it’s just much more
convenient to coercively force the factory owner to do what the statist wants.]

*Fourth*, what’s odd about the statist’s criticism of the sweatshop factory
owner is that the statist is not also taking aim that those who do not choose
to open factories in this region. Those who choose not to open a factory are
doing nothing for the poorest in that region; they are not offering them higher
wages than they could earn elsewhere, better working conditions than they
presently endure or the opportunity to develop their skills through gainful
employment. In contrast, the sweatshop factory owner is the only one who is
offering to use his capital to improve these individuals’ lives. If there is a
“moral imperative” to improve the plight of these workers, why don’t statists
target people who are doing nothing to contribute to this imperative, instead
of picking on the one party who is doing something positive?

Instead of making this entrepreneur’s activities more difficult through state
intervention, we should be applauding and encouraging his actions which, though
born out of self-interest, are also providing the poorest with an opportunity
to reach the first rung on the ladder towards improved living standards.
footnote:[If statists really cared about the plight of the poorest in these
regions, they should argue for states to force entrepreneurs to open factories.
This might sound ridiculous, but it is only because the statist’s attack on
those who do open factories is ridiculous in the broader context.
Alternatively, and as noted earlier in this paper, if statists want to improve
the living standards of the poorest, why don’t they campaign instead for
economy-wide low price ceilings on all goods, so the low income of the poorest
can buy more? That would be a way ostensibly to improve the lot of the poor
without targeting the one party ‒ the sweatshop factory owner ‒ who is actually
helping these people.]


=== Unseen Costs

Statists often observe reality at time t~0~ when there was no state
intervention, and then at time t~1~ after the state has intervened, and conclude
that, if the latter reality is better than the former, then the state’s
intervention was beneficial. However, this conclusion ignores economics,
morality and history.

_Economics_. Each time the state intervenes there is a cost, but this is never
compared with the benefits of what resulted. The state forcibly diverts scarce
resources from where they would have flowed naturally in order to satisfy
consumer preferences to where the individuals at the state define as the
priority. While we see the impact of this diversion of resources in the form of
where the resources end up, we never see the impact of this diversion in the
form of where they might have gone and how they might have otherwise been
deployed. Thus it is impossible to know if the benefits of that diversion
exceeded the costs.

For instance, if the state imposes significant compliance costs on drug
developers, requiring them to jump through the process hoops the state has
designed before the drug developers can market their products, we can never
know if the scarce resources that were diverted into such compliance activities
could have been used to develop other breakthrough drugs, saving lives and
alleviating suffering.  footnote:[The uglier truth is that, before these state
regulations were written, the incumbents would have aggressively lobbied the
state to ensure the regulations were written to favor them over potential new
competitors. So we also can never know if the resources diverted to this
lobbying could have been used by the incumbent drug companies to develop
breakthrough drugs, and also whether those entrepreneurs who cannot enter the
market because of the regulations might have developed breakthrough drugs.]

By imposing its centralized view on resource usage on every firm, the state
artificially reduces the resources that can be used by the market in trial &
error to develop more and better products to satisfy actual consumer
preferences. If we judge state intervention just by visibly positive outcomes
without considering its hidden but very real costs, we are making uneconomic
decisions; we are assuming there are no trade-offs, which is contrary to the
reality of a world where resources are scarce. By this (unrealistic) rationale,
state intervention can never be the wrong decision.

How do we know that the free market can do better? In the free market
entrepreneurs from different industries and at different firms bid against each
other for scarce resources. This tends to drive their prices up, but there is a
limit as an entrepreneur is not going to purchase a resource at a price above
which he can sell his final product to consumers. Consumers are willing to pay
more for products that satisfy their more important needs than those that
satisfy their less important needs. Thus as consumers express their relative
preferences through the prices they are willing to pay for different products,
this guides entrepreneurs as to how much to bid for scarce resources. By
definition those entrepreneurs satisfying consumers’ most important needs will
be able to bid more for scarce resources than those who are not. In this way we
know that resources are moving to where they can bring the most value, which is
another way of saying that we know that the cost/benefit trade-off is being
appropriately considered.

To illustrate this point, assume that input X is used by entrepreneurs
supplying product A and those supplying product B. If consumers value product A
more highly, and thus are willing to pay more for product A than for product B,
then in bidding for input X entrepreneurs who manufacture product A will be
able to outbid those who manufacture product B, and more of input X will flow
to these entrepreneurs. Through this process resources will flow to their most
important uses as “voted” by consumers with their own dollars. Contrast this
with state intervention, which would forcibly direct input X to the use deemed
most important by individuals at the state, even though they are not the end
consumers. Which process is more apt to appropriately weigh trade-offs and
maximize satisfaction of consumers’ wants?

Often statists will point to a product developed with the state’s backing and
note the absence of a private sector alternative, and then claim that this
product would not have been developed by the private sector, so that there must
have been a significant benefit from the state’s intervention. However, this is
quite disingenuous on several counts.

*First*, it’s possible that there is no actual consumer demand for the product
so the claim might indeed be correct (but that wouldn’t be a good thing!).

*Second*, we can never know if the claim is true but, given the incentives in
the private sector and the lessons from economic history, the chances are high
that if there were real demand then the private sector would have developed a
relevant product to address that demand.


*Third*, when an entrepreneur in the private sector tries to develop a product
that competes with an effort backed by the state, the private sector product is
normally crowded out by the state. Since the state can forcibly divert
resources to its project, whereas the entrepreneur has to bid for the resources
and can only obtain them if others voluntarily yield them, the state has a huge
advantage in terms of the resources it can throw at a project. Further, since
the state is not concerned with profitability ‒ it cannot go out of business as
it can always forcibly raise taxes to fund its losses, thereby shifting this
unseen cost onto taxpayers ‒ the state can price its products well below the
private sector’s prices. In addition, the state can of course use its
regulatory muscle to further handicap or outright prohibit the private sector
alternative.  footnote:[A good example of crowding out is the development of
the Internet. While the packet switching technology that underlies the Internet
was developed by two individuals in the private sector, the concept of a global
network was developed concurrently by a U.S. government-backed effort and
several alternative private sector efforts. For various reasons these private
sector efforts ‒ whose networks were more advanced than that being developed
for the U.S. government ‒ fell away in the face of the U.S. government’s
funding and other actions (and those of some European governments which sought
to protect their state-run telephone companies). Thus we ended up with the
Internet we have not because it was the best solution (technologically it
wasn’t), but because the private sector efforts were crowded out, leaving the
U.S. government’s project as the “last man standing.” Money has suffered a
similar fate: originally sound money was developed by the free market, but then
the state needed to control the money supply for its own ends and thus
legislated away private money.]

_Morality_. While some individuals in the economy might appreciate that the state
acted to produce the outcome that occurred, by definition the state would have
forced other individuals in the economy to pay for an outcome that they might
not have wanted (either at all, or in priority to other outcomes for which they
might have preferred to use their income that was taxed away).

As raised elsewhere in this paper numerous times, statists have no good
response to the moral question, namely, if all men are born equal so that no
man has the right to rule another without his consent, by what right can those
at the state seize an individual’s income to use in ways that individual does
not want?

_History_. Almost every example statists rely on to “prove” the benefits of state
intervention is belied by the trends that preceded the intervention.

For instance, statists will cite examples of where, following the state’s
imposition of health & safety regulations, workplace accidents declined; what
they will fail to observe is that workplace accidents were declining anyway for
a long time before the introduction of the regulations, and usually at a rate
faster than after the regulations were implemented. In fact, the history of
sweatshops globally shows that legislation dealing with minimum wages,
benefits, workplace conditions, etc. mostly followed voluntary industry
developments caused by the economic dynamics previously discussed, rather than
preceding these developments and causing them to occur. Tellingly, where this
type of legislation sought to get out in front of economics – meaning it
attempted to prematurely force adoption of uneconomic workplace improvements –
the various parties (factory owners and employees) simply ignored the
legislation and operated in non-compliance. Human action will always trump
legislation which seeks to repeal the laws of economics.

Similarly, statists will cite the implementation of state-provided health
insurance as a positive factor in increasing the percentage of the population
that has health insurance, ignoring the fact that this percentage had been
growing more rapidly before the new state scheme was introduced.

Using economic history as a guide and considering the relevant incentives, if
there is real demand for something – be it safer working conditions or health
insurance – entrepreneurs will develop a product to meet that demand in the
most efficient manner possible. On the other hand, all that state intervention
has ever done is increase the cost of supplying products, leading to lower
supply, and impose centralized resource direction on the economy, leading to
misdirection relative to actual consumer preferences.
