== Myth #12: We Need The State To Deal With Anti-Competitive Behavior

Another twist on the idea of “market failure” is that statists claim we need
the state to curb so-called “anti- competitive” behavior by entrepreneurs. The
legislation which has been passed in the U.S. to combat this behavior is known
as “anti-trust” legislation. The argument runs that entrepreneurs of large
firms will try to bankrupt their competitors by undercutting their prices at
loss-making levels (so-called “predatory pricing”) so that they can attain a
monopoly, and then afterwards will cut production and jack prices up to a very
high level (engaging in “monopoly behavior”). Apparently only the state can act
to thwart this societal menace. Well, this argument is wrong in many respects.
footnote:[One amusing note about the area of anti-trust legislation: some
experts have noted that if a company puts its prices up it could be
investigated for monopoly behavior; if it lowers its prices it could be
investigated for predatory pricing; and if it keeps its prices constant it
could be investigated for price fixing (colluding with competitors to charge
the same prices).]


*First*, this phenomenon has never happened. This whole area is an intellectual
economist’s theory but there is not one single example of this occurring in
history prior to the anti-trust legislation being passed. In fact, prior to
passage of the legislation the industries that have often been cited as the
monopolistic villains justifying such legislation were actually increasing
production and lowering prices faster than what was happening in the overall
economy.  footnote:[See the historical work done in this area done by Thomas
DiLorenzo which he wrote about in "The Origins of Antitrust: An Interest-Group
Perspective," _International Review of Law and Economics_, Fall 1985 and “The
Truth About Sherman,” _Austrian Economics Newsletter_ , Summer 1991.]

*Second*, it makes no economic sense for an entrepreneur to engage in predatory
pricing. Why would he seek to make losses on his large market share when
consumers would just stock up at the unusually low prices and thus shift their
demand from the future to the present, so that when the entrepreneur later
jacks up his prices consumers would not have the same purchasing needs?

In addition, once he has bankrupted his competitors and jacks up his prices the
entrepreneur would create the impetus for new competitors to enter the market
and offer consumers a better value proposition. In fact, the new competitors
would be able to purchase the bankrupt former competitors’ assets at bargain
prices and thus be even more effective competition for the incumbent.

*Third*, the whole notion of anti-trust legislation is actually anti-consumer.
The purpose of economic activity is to organize scarce resources to maximally
satisfy consumer wants. Consumers benefit significantly from lower prices and,
if firms want to engage in pricing wars, all the better for consumers.

When anti-trust legislation tries to prevent lower pricing by the most
efficient firms, this hurts consumers and, in effect, protects inefficient
firms from more efficient competition. We know this because no “predatory
pricing” complaints ever come from consumers; they always come from the
inefficient firms in an industry which are trying to enlist the state’s help to
take the more efficient firms down a rung or two. However, in protecting firms
that are inefficient ‒ in that they are doing a poor job of organizing scarce
resources to satisfy consumer demand ‒ the state only helps to trap resources
with these less effective entrepreneurs when these resources could be better
used by the more effective entrepreneurs.

Statists often retort that if inefficient firms go out of business then jobs
will be lost, but this is essentially an argument that it is more important to
protect jobs than to satisfy consumer wants. We can see how absurd this idea is
through a thought experiment. Imagine a world where all material consumer wants
are satisfied by a deity, so that no one needs to work (although people could
still choose to do so); in this world, everyone can devote their lives to
leisure activities if they wish. Now consider a world where everyone has a job,
but the job is to break large rocks into small stones; thus while everyone has
a job, no one’s actual wants are satisfied. In which world would you rather
live? I repeat, the purpose of all economic activity is to satisfy consumer
wants, not to provide jobs.

To the statist argument that the state needs to strike a balance between
consumer wants and jobs, one can respond in two ways. First, who at the state
is so omniscient to be able to strike this exquisite balance, knowing the wants
of all relevant consumers and the economics of all relevant firms? Second, on
what moral basis does anyone at the state have the right to forcibly interfere
in the peaceful trades between entrepreneurs and consumers?

Anti-trust legislation is just another example of crony capitalism, where the
weaker firms lobby the state (making the “jobs” argument) to rent its coercive
powers to help them compete.

*Fourth*, enduring monopolies are only a feature of a statist system; a
monopoly cannot be sustained in a truly free market.

In the free market consumers only purchase products voluntarily, and
entrepreneurs are free to enter an industry as new competitors at any time.
Even if at any one point in time there is only one producer in an industry, if
he is not supplying the right types of products at the right prices consumers
will abstain from purchasing. This will then create an opportunity for other
entrepreneurs to enter the industry to serve the unsatisfied consumer demand.

Just because other entrepreneurs have not entered the industry at any
particular point in time doesn’t mean the incumbent is doing anything wrong. In
fact, just the opposite: if his products are in demand then he should be lauded
as the only entrepreneur who is currently satisfying consumer demand! Think of
all the individuals in society who are not taking the risk to try to satisfy
this demand. They are the problem, not the incumbent.

Statists claim that there are some industries where the capital investment is
so large that there can only be one producer, the so-called “natural monopoly.”
Yet in every single industry where this is claimed to be the case history shows
that there have been multiple producers absent state interference. What the
statist really means by a “natural monopoly” is that he believes this product
should be produced and priced in a particular way, and he cannot conceive of
how multiple entrepreneurs and capital providers, through trial and error,
might be able to figure out how to produce it in a competitive environment at
prices that consumers would be willing to pay. It represents the arrogant
substitution of the statist’s intellectual limitations for the combined
intellects of market entrepreneurs.

Only the state can create a sustainable monopoly through granting an exclusive
license to operate in a particular territory. This is what happens in those
industries in which the state has determined a “natural monopoly” is
appropriate. The entrepreneur who obtains this license – usually the most
effective lobbyer rather than the most effective organizer of resources – has
the state’s power backing his monopoly status, meaning the state makes it
illegal for any other entrepreneur to compete. There is nothing “natural” about
that.  footnote:[For a very good analysis of so-called “natural monopolies,”
see Thomas DiLorenzo’s article, “The Myth of Natural Monopoly,” _The Review of
Austrian Economics_ 9 (2), 1996.]

*Fifth*, the idea of the state enforcing anti-trust legislation against
perceived monopolies is a cruel joke. It is a perverse self-contradiction that
the state ‒ which is itself a coercive monopoly ‒ acts to prevent private
sector monopolies from arising. Yet it exempts itself and its friends (the
“natural monopolists”).

