== Acquiescence To The State

=== Host/Parasite Analogy

The individuals at the state live off the productive capacity of the rest of
the population. It is the rest of the population that produces the real wealth
in society, namely, goods and services which satisfy human wants. When these
products are created and traded they generate the base on which state personnel
can forcibly levy taxes to fund their personal incomes and professional
activities. This is why, to libertarians, the state is analogous to a parasite
living within the body of civil society as the host.

Biologically a parasite cannot exist without a host, for the host is the source
of the parasite’s sustenance.  Accordingly, unless a parasite is highly mobile,
it does not want to completely destroy its host as then the parasite would
perish too. Moreover, the host is always more powerful than the parasite, pound
for pound, so in some sense the parasite depends for its existence not only on
the host’s survival (even flourishing) but also the host’s passive
acquiescence.

Thus state personnel have to be careful not to milk society so extensively that
they drain it of some base level of productive capacity. In those states that
have historically gone too far civil society exists in dire poverty, e.g.,
Cuba, North Korea, the Soviet Union, Venezuela and Zimbabwe, and this can only
end in total system collapse (as happened eventually in the Soviet Union).

More importantly, however, the individuals at the state are numerically always
a small fraction of the overall population. If the population as the host were
to rise up in a coordinated fashion to rid itself of the state parasite, state
personnel would be powerless to stop this. This has occurred historically
through successful revolutions, the most famous of which are the French and
American Revolutions of the late 18 th century.

Accordingly, to try to prevent such revolutionary action the modern state uses
three different means to ensure the population’s acquiescence.

=== Fear

Individuals at the state can act with great physical brutality against anyone
engaging in revolutionary action or those merely suspected of thinking
revolutionary thoughts. This is designed to instill fear in the minds of
citizens, to suppress acting on any revolutionary inclinations they might
harbor. This is a key feature of most totalitarian states and can be described
as “fear-based acquiescence.”

However, in modern democracies where there is no ongoing, widespread physical
brutality, the mere awesome power of the state and periodic displays of its
power by its military, police and other executive bodies can be sufficient to
induce a “Stockholm syndrome” among the population. This syndrome is a
psychological phenomenon in which hostages express empathy with, and have
positive feelings toward, their captors, sometimes to the point of defending
and identifying with them. These feelings are generally considered irrational
in light of the danger or risk endured by the victims, who essentially mistake
any lack of abuse from their captors for kindness. So, for instance, even
though state personnel could at any time decide to forcibly confiscate up to
100% of an individual’s income, the fact that they “only” choose to confiscate,
say, 35%, is regarded as a beneficent act that should not be questioned by the
population and should even be applauded for its restraint.

=== Participation

State personnel can also divide and conquer. By renting out its coercive powers
to special interest groups the state can, in effect, invite a broader
percentage of civil society to live as parasites too. This involves the state
handing out subsidies, tax privileges, monopoly licenses, welfare or other
transfer payments, etc. to many different sub-groups in society, who thereby
live off those who are not so well organized to demand these benefits or oppose
these programs.  footnote:[As explained earlier, this is known as “crony
capitalism” or “political entrepreneurship.”]

This practice ensures that there are many individuals who become dependent on
the state for their own well-being so that they are unlikely to rise up and
reject it. “Don’t bite the hand that feeds you” is the adage that comes to
mind. This is a feature of every state in existence today and can be described
as “participation-based acquiescence.”

=== Education

In addition, the political class can seize control of the minds of the
population and pump them full of fallacies about why we need the state. In this
way such subversive ideas as rejecting the parasite never even arise or develop
very far. The state does this primarily by controlling education.
footnote:[Other means include the ridiculously childish pomp and ceremony that
citizens are subjected to from a very young age when it comes to state
institutions and personnel: honoring the national flag; emotionally singing the
national anthem; treating politicians and the military with a reverence they
have done nothing to deserve; in the U.S., reciting the Pledge of Allegiance at
school, etc.]

The state sets or influences educational curricula through many means:
licensing of teaching professionals, accreditation of educational institutions,
funding the development of learning materials, funding the budgets of
educational institutions, and subsidizing key intellectuals to produce “thought
leadership” that just happens to favor the state.  footnote:[To reward its
intellectual supporters, the state funds research grants, retains intellectuals
as consultants, funds educational institutions that employ intellectuals, and
offers intellectuals prestigious positions at the state itself.]

Further, the state either compels the population to sit and listen to its
educational content (as is the case with compulsory K-12 school attendance), or
bribes the population to sit and listen (as is the case with heavily subsidized
“college for everyone” programs).

As a result, the state can expect very little host resistance. When one looks
at the history of state-provided and state-financed education around the world
it is quite clear that the original purpose was to mold each child into a state
worshipper, euphemistically called a “good citizen.” This is not supposition;
when state education was first conceived, its creators were not shy about
making this point explicitly.  footnote:[Note too that in the early 19^th^
century before state education was imposed in England, the state actually tried
to discourage independent thought by taxing paper, newspapers and pamphlets to
make it too expensive for ordinary citizens to access unapproved information.
These were essentially “taxes on knowledge.”]

This indoctrination is a feature of every state in existence today and its
effect can be described as “fallacy-based acquiescence.”

The impact of this indoctrination is that the statist can be likened to the
proverbial “frog in boiling water.” While to the libertarian each new action of
the state is a moral outrage because the libertarian’s benchmark is fixed,
namely, the absence of coercion, to the statist each new action of the state is
acceptable or, at worst, tolerable because the benchmark is dynamic, namely,
the status quo immediately before the new action. The statist has been taught
to accept the status quo and thus each incremental state action seems quite
bearable, whereas the libertarian does not accept the status quo and thus views
the totality of all state actions as a gargantuan abomination.

This is not to imply that “good citizens” are stupid. To claim that someone
believes in a fallacy is not a statement about that person’s IQ, which is
biological, but rather about that person’s knowledge, which has to be actively
sought. One can have a high IQ but not know anything, or anything correct,
about a particular subject and thus have erroneous views with respect to that
subject. Thus while to a libertarian it seems unreasonable for a person to
support the state given the depth and breadth of the moral, economic and
historical cases against the state, one must take account of the fact that few
statists have devoted any time to learning about libertarianism but most have
spent much of their lives drinking from the fountain of statism.  footnote:[In
my case I had 19 years of formal schooling in statism and another 20+ years of
imbibing statism by osmosis; a mere three years of intensive self-education
about libertarianism and Austrian economics completely changed my views.]

It should be noted that a key component of generating this fallacy-based
acquiescence is creating and furthering the illusion that voting makes one an
active participant in and influencer of the state. The more that people believe
that the broader the suffrage the more “We’re all in it together,” the more the
state can get away with, because it can always retort that its decisions
reflect the “general will” of the population or that “The people have spoken.”
In this sense it is no coincidence that the growth of the state has been
greatest in modern times in parallel with the growth of democracy and broader
voting rights among populations.

[centered]#* * * * *#

Fear-based acquiescence and participation-based acquiescence are mostly immune
to rational debate; one can understand the issues with the state but still
support it for one of these two reasons. However, fallacy-based acquiescence
can and ought to be addressed by remedial action. The issue for libertarians,
though, is that the underlying fallacies as to why we need the state are rarely
challenged, much less addressed, in regular discourse among the population.
Accordingly, below I will address some of the larger fallacies about the need
for the state.

Before I do so, however, I am willing to concede that there may be statists who
are quite cognizant of all of the failings of the state and who might even
doubt the need for a state in its present form, but who nevertheless support
today’s state simply because they believe there is no better option. I see this
as a problem of a lack of imagination and intellectual curiosity to search for
a better solution, and an inadequate education.
