== Myth #23: If It’s So Good, Why Hasn’t It Ever Been Tried?

Statists believe that there are no examples of libertarianism in history or
currently. However, there are plenty of examples of societies or sub-sections
of society interacting on a truly voluntary basis. Statists read but they do
not comprehend; they see but they do not observe.

=== History

There are many historical examples of societies that have existed without the
coercive control of a large, centralized state.

The most basic point to note is that the concept of the modern nation-state
really only gained formal recognition in the 17th century with the Treaties
of Westphalia. Before then, societies were organized in numerous different
forms, some stateless (e.g., clans, tribes, villages, feudal societies,
etc.), and others with a “low state” form, such as the ancient Greek and
Renaissance Italian “city-states.”

Many monarchies first existed in parallel with private society, with the
boundaries reasonably well-defined until the royalty decided it needed to
forcibly take over various functions to finance its wars.

The development of the “law merchant” in the Middle Ages and the Renaissance
is a very good example of individuals voluntarily developing their own legal
system and customs. The law merchant was based on what was generally
perceived to be fair and to work effectively to facilitate peaceful trade
within a highly mobile population across different regions. Within this
community the threat of being ostracized by one’s trading partners was the
most important reason to accept adverse judgments rendered by the private
courts.

In terms of other stateless legal systems, Medieval Iceland and Ireland
operated with purely voluntary conflict resolution regimes, and in the U.S.
the development of the West initially operated quite efficiently and
peacefully before the federal and state governments got involved (it turns
out that the “wild, wild West” was not so wild after all). footnote:[See 
Terry Anderson’s and Peter Hill’s book, _The Not So Wild, Wild
West_. In addition, Peter Leeson’s book, _Anarchy Unbound_ , and Edward
Stringham’s book, _Private Governance_, detail a number of very interesting
and sometimes counterintuitive historical examples of self-governance
without a state. To be clear, this is not an endorsement of existing states,
which of course would not be part of a libertarian society. Rather, this
discussion simply notes that the way states interact among themselves mimics
how individuals would interact in a stateless society.]

And of course, as noted earlier in this paper, contemporary Somalia, while no
stateless paradise, saw a measurable improvement in living standards when it
was stateless in the 1990s and 2000s relative to when it had a central state.

More generally, and as noted previously, every single function that is
carried out by the modern nation-state ‒ including defense, policing, courts
and law, roads, education, etc. ‒ was at one time carried out by private
parties on a non-coercive basis until the state took it over for its own
purpose. Most importantly, many of these functions are still carried out
privately today in different parts of the world.

=== The International Community

The most obvious and significant current example of libertarianism is the
international community: vis-à-vis one another, the various nation-states
exist together on a purely voluntary basis. There is no “world state”
coercively telling each state what to do. Many aspects of what a libertarian
society would look like domestically are in operation today internationally.
footnote:[ To be clear, this is not an endorsement of existing states, which of
course would not be part of a libertarian society. Rather, this discussion
simply notes that the way states interact among themselves mimics how
individuals would interact in a stateless society.]

Taking the world’s population as a single society, there are competing
defense forces, police forces, courts, bodies of law, currencies, approaches
to regulation, etc. There is no group of central planners dictating who must
produce what, at what price goods must be sold, etc.

The NAP is respected among states and the politicians at each state in the
sense that no one asserts the right to coerce another. The individuals at
each state interact with individuals at other states on a completely
voluntary basis.

In some sense the homesteading principle is also respected, in that states
have delineated boundaries of property they control which they claim as their
own, and these boundaries are, for the most part, accepted by other states.
Similarly, when a state peacefully declares borders around ocean-based
economic zones and portions of outer space for their satellites, this
homesteading is generally respected too.

If one state trespasses onto the claimed property of another state, the right
of self-defense is well recognized.

The most acceptable form of interaction within the international community is
not through coercion but, rather, via voluntary agreements (treaties) and
voluntary associations (such as the United Nations, World Trade Organization,
NATO, etc.). Nations are free to join and financially support these
associations if they agree to their mandate and operations, but are also free
to leave them. Yes, there are wars and other conflicts (just as there is
within a state), but these constitute the minority of the millions of
interactions that happen daily among states.

As discussed earlier in this paper, it’s noteworthy that the individuals at
the state are content to live in a libertarian existence relative to their
contemporaries at other states, but they are not prepared to live this way
among their own citizens, whom they prefer to rule by force.

=== Local Communities

At the smaller unit level today we have private residential communities, Walt
Disney World, shopping malls, corporate campuses, hotels, kibbutzes, etc.
They each have their own civic goods (i.e., roads, parks, waste disposal,
security, etc.) and regulations and customs, and they operate efficiently and
fairly without state-style coercion. footnote:[For an excellent theoretical
discussion of these concepts, as well as some in-depth case studies, see Fred
Foldvary’s book, _Public Goods and Private Communities_.]

In fact, every voluntary association is a case study of libertarianism:
people come together (and may leave) voluntarily, make their own rules of
interaction, financially support the objectives on a voluntary basis (and can
similarly withdraw such support), and for the most part make it work
peacefully. There is no one cracking the whip and there are no implied or
actual threats of incarceration at gunpoint for failure to carry out or
finance these groups’ stated objectives.

=== But Even If These Examples Didn’t Exist...

As relevant and illuminating as these examples are, even if these examples
did not exist it would not weaken the case for libertarianism. Just because
something hasn’t happened yet doesn’t mean it can’t be an improvement on what
we have now.

Notwithstanding this logic, statists often argue that if there hasn’t yet
been an enduring stateless society then that must prove that such an
organizational form is not technically feasible or superior. But by this
logic the present form of any idea is always optimal and can never be
improved upon. Framed that way I’m sure not even the most ardent statist
would agree. Indeed, statists are always looking to improve upon the
operation of the state (generally to make it more powerful) so their own
actions belie this logic. And, in any event, a quick survey of human history
will show that societal organization is not static but continuously evolving.

Imagine if before the first modern democracy a monarchist had pointed out
that the idea of democracy cannot be valid or better than monarchy because it
hasn’t existed in modern times. Should that have ended the argument about the
worth or feasibility of democracy?

Or, to pick a real example, consider the abolitionists in the 19^th^ century
trying to make their case against slavery, which at that time was a global
phenomenon that had always been part of the world order. Are we to believe
that the abolitionists had no valid case to make because there had never been
a world without slavery?
