==  Myth #21: Libertarians Don’t Care About The Poor!

Statists pejoratively ask of libertarians “How would the poor survive in a
libertarian society?” The implication is that it is only through the state that
the poor can be clothed, fed, employed, etc. There is a lot to unpack here.

=== Free Markets Rescue The Poor

The statist shows a remarkable lack of appreciation of economic history.
Poverty has been the default, the natural state of man, for all of history. It
was only the advent of (nearly) free markets as first embodied in the
Industrial Revolution in Great Britain in the 18^th^ and 19^th^ centuries (but
which then ultimately took hold in the U.S. and other countries) that lifted
the common man out of his dire straits. When the state’s influence was at its
minimum – meaning there was sound, commodity-based money (generally gold and
silver) and the ability to freely exchange private property and freely
associate without interference from the state – man was able to dramatically
increase his living standards. He did this both by specializing in his labor
and deferring some consumption to provide pools of savings to be invested in
developing new technologies and processes, thereby increasing worker
productivity.

Importantly, almost every consumer-oriented business that has been successful
has achieved this success through constant innovation to bring down the price
of goods to make them accessible to the masses; it is much harder to achieve
success on a grand scale by selling only to the rich. Thus the poor in the U.S.
are able to afford things like wide varieties of food, clothing and shelter,
color televisions, air conditioning, refrigerators, flushing toilets, cars and
air travel, not to mention the ubiquitous mobile device (even in the most
poverty-stricken neighborhoods). As noted earlier in this paper, the poorest
members of free-market-oriented societies live better now than royalty lived a
couple of hundred years ago.

We can also see this effect in the U.S., even using government statistics. The
so-called “poverty rate” declined dramatically over the course of the 20^th^
century in the midst of a relatively free market regime, until the massive
expansion of the state in the late 1960s and early 1970s as part of the launch
of President Johnson’s “War on Poverty,” at which point the poverty rate
flattened out and has declined much less since, despite trillions of dollars
having been spent by the state in this faux war.  footnote:[Statists really
can’t explain this phenomenon, not that they even bother to try. As libertarian
historian Tom Woods likes to note, had the inverse been true, i.e., had the
welfare state been in operation for all of the 20^th^ century and then been
terminated in the late 1960s, with the same poverty rate flattening trend as
noted above, statists would be crowing about the obvious benefits from state
interference.]

Looked at another way, where would you prefer to be poor: in freer markets such
as the U.S. or in less free markets such as Cuba, North Korea and Venezuela? If
more freedom is better for the poor, why is total freedom not the best?

The so-called “War on Poverty” should really be named the “War on Common
Sense.” Statism is nothing more than central planning, which surely has been
repudiated by the implosion of the Soviet Union and the desperate states of
Cuba, North Korea and Venezuela, to name a few examples. The only difference
economically between those regimes and the statist U.S. is the amount of
central planning: in those countries every industry was or is completely
centrally planned; in the U.S., every industry is partly centrally planned.
footnote:[And the worst industries in the U.S. are the most centrally planned:
education, financial services, health care/insurance and the military.]

If central planning as a concept does not work, why tolerate any of it?
Statists believe that there is a “correct” amount of central planning and that
only they know this amount, but they will never tell you what this amount is
definitively. Generally it is defined as whatever amount they are proposing at
any one point in time. This just strains credulity.

=== There Are Plenty Of Non-State Resources To Help The Poor

What about the statist’s perennial favorite, namely, that leaving everything
“to the market” won’t help those who “fall between the cracks”? There are
several ways to respond to this.

One way is to note that “the market” is not some impersonal machine but,
rather, millions of individuals interacting voluntarily on a daily basis.
Likewise, “the state” is not an impersonal machine but also comprises
(unfortunately!) millions of individuals. When the statist claims that the
state is superior to the market in preventing some people from “falling between
the cracks,” he is implying that only those at the state have the awareness,
compassion and ability to help these people. On what basis can we conclude that
the millions of people not working for the state are not concerned to help
their neighbors in need and that this concern is held exclusively by the
millions of people at the state?  footnote:[Perhaps the Tooth Fairy Theories?]

Moreover, even if this were true, in a libertarian world these millions of
people now working for the state would still be around ‒ just not as part of a
state ‒ and thus they could still express and act on their concerns and the
poorest could still benefit from their magnanimity.

Another response is that (as noted earlier in this paper) civil society
comprises many parts: the individual, families, neighborhoods, religious
groups, charities, mutual aid societies, self-help organizations, other
associations, businesses, trade groups and the state. In a libertarian world
the only one of these that would be missing is the state. Is it not possible
that for the few who might “fall between the cracks” there might be some part
of what remains of civil society, absent the state, that could help these
people? One of the shortcomings statists suffer from is the “tyranny of the
present.” That is, they assume that a libertarian world would look exactly like
the present world minus the state’s welfare programs. To the contrary, many
aspects of society would be very different. For instance, it is highly likely
that, at a minimum, institutions of civil society that once existed, but which
have been crowded out over time by the expanding welfare operations of the
state, would have room to flourish, perhaps growing again to the prominence
they once had in helping the neediest before the state’s role exploded in the
1960s.  footnote:[See, for example, the history of mutual aid societies in the
U.S. as detailed in the book by David Beito, From Mutual Aid to the Welfare
State.]

In fact, if the statists in civil society who elect the state into being do so
primarily to help the neediest, presumably they would still care about the
neediest in the absence of the state. Are statists claiming that they
themselves would become less interested in helping the neediest if there were
no state?

Boiling it all down, both a libertarian society and a statist society would
comprise all the same individuals and all the same social institutions bar one
(the state). Thus the only difference between a libertarian society and a
statist society is the ability to coerce others. The statist is effectively
saying that he cannot envision marshalling sufficient resources through his own
actions and persuasion to help the neediest, and thus must rely on force.

The statist must hold a very dim view of his fellow citizens; one wonders why
he would even want to live among them. Nevertheless, this does not justify the
immorality of one man coercing another.

=== There Would Be Fewer Poor

Another example of “tyranny of the present” thinking is the statist’s
assumption that, if the state ceased to exist, we’d still have the same number
of poor as we do now. Yet in a libertarian world with a truly free market we
would expect that there would be fewer destitute people.

This is because, as discussed earlier in this paper regarding the free market,
without a state there would be: (a) more and better paying jobs, since, absent
taxes and regulations, the cost of employing workers would be lower and there
would be more capital available per worker to increase each worker’s
productivity, and also workers would be free to make their own risk/reward
trade-offs when accepting employment; (b) more opportunities for entrepreneurs
to pursue, freed from the costs and restrictions placed on them by taxes and
regulations; and (c) more goods in the market, at lower prices, as the costs of
production and the range of permissible products are freed from the impediments
imposed by taxes and regulations.

In addition, as explained by Austrian economics, the state central bank’s
central planning of the money supply and interest rates, and control of the
banking system, have three major adverse consequences for the least well-off,
who are the most sensitive to these matters. These consequences would not occur
in a truly free market.

*First*, economy-wide “boom-bust” business cycles are caused by the artificial
manipulation of interest rates by the state’s central bank, either directly or
through the financial support it provides to the banking system. *Second*, when
new money is created and injected into the economy by the state or its
controlled banking system, this impoverishes the least well-off relative to
those with the closest connections to the state. This is because the new money
is not injected uniformly but first goes to the “connected few,” who therefore
get to spend it before the inevitable effective rise in prices that occurs over
time due to the creation of new money without any corresponding increase in
real goods, and it is the least well-off who get the new money last, well after
prices have risen. *Third*, unlike in the days before central banking, due to the
state’s artificial suppression of interest rates and the price inflation caused
by expansion of the money supply, it is now impossible for the least well-off
to build a “nest egg” for retirement through the low risk method of saving
money in a bank, the value of which previously grew faster than the modest
price inflation, if any. Instead, in saving for retirement now everyone is
pushed by low interest rates and significant price inflation to take on much
more risk, such as speculating in the securities markets, real estate or other
high risk endeavors.

More broadly, societal prosperity is directly linked to the amount of “stuff”
produced to satisfy consumers’ wants.  The amount of “stuff” produced is, in
turn, directly linked to the number of man hours devoted to appropriate
productive activities. When there is a state, a significant number of man hours
are devoted to unproductive activities that have nothing to do with satisfying
consumers’ wants. These man hours include: the time spent by individuals who
work for the state in either creating or enforcing regulations; the time spent
by individuals lobbying the state to rent its coercive powers; the time spent
by individuals who have successfully rented and are thus benefiting from the
state’s coercive powers, i.e., crony capitalists; and the time spent by
individuals in complying with the state’s regulatory whims. Then there are the
man hours devoted by individuals trying to avoid the state’s whims.

Imagine all of the additional prosperity we would have if all of the
aforementioned people, time, effort and resources were instead engaged in
productive activities.

=== Freedom Of Movement

Another aspect of the state that adversely impacts poverty is state regulation
of immigration.

Much of the world’s poor would have much better lives – better job prospects,
more goods and services available to purchase, and at lower prices – if they
were free to move to places with more liberty than where they live today.
States create and enforce artificial national borders and establish
category-based immigration restrictions (based on geography, ethnicity, family
ties, etc.). All of these restrictions prevent the poorest individuals from
moving to places where they could better flourish.

In a libertarian world these centrally imposed restrictions would not exist.
All property would be privately owned, so whether someone from another region
could move here would be based on the individual decisions of transport
providers and local private property owners. Businesses would be free to invite
and host immigrants from other regions, as would relatives, ethnic
associations, charities, etc. These decisions would be made on an individual
basis using privately established criteria, and it is likely that more of the
world’s poor would be able to more easily move to where the opportunities lie.

The statist who advocates both for the poor and for state-based immigration
barriers is essentially saying that his concern for the poor only extends to
those located inside an artificially created geographic area. However, why
should the plight of someone inside this area be more important than that of
someone outside this area? It certainly makes sense that people feel more
compassion for those in their immediate neighborhood, as they live with and see
these people all the time. But by what logic should a statist in New York feel
more strongly about a poor person in Seattle than a poor person in Toronto? He
knows neither personally, and the poor person in Toronto is actually
geographically closer to New York than the poor person in Seattle. It is as if
the U.S./Canadian border possesses some magical anti-compassion feature.

Buying into the notion of the state means that the individuals at the state get
to define for you which poor people in the world you are allowed to be
concerned with and to assist economically.

=== The Morality Of It All

The argument that we need the state to help the neediest is a utilitarian
argument. Such an argument is, in effect, saying that the statist believes that
if he identifies some people in need he is justified in coercively taking
resources away from others he identifies as not being in need. Coercion is
justified because the statist believes the ends are worthy. The statist’s
argument does not deny that there is coercion, nor that the statist’s
definition of “in need” is entirely subjective and is being imposed on others
without their consent.

This paper has presented libertarianism as a philosophy that is moral because
it advocates a universally applicable behavioral code which rejects the
validity of the initiation of force against anyone, and has presented statism
as immoral because it relies on the initiation of force by some against others.
The statist’s utilitarian argument doesn’t change this conclusion.

If the utilitarian argument is to prevail over the moral argument, why not just
cease treating robbery as a crime and allow the neediest to freely rob the
well-off directly? Why bother using the state as a middle man to engage in this
robbery, with all of its overhead costs and the complicating personal
incentives of those who work at the state? That seems to be a much less
efficient means to achieve the statist’s ends.

The moral way to view the neediest would be that we should individually want to
help them, but only voluntarily.  That’s very different from saying we should
use coercion to do so. As discussed earlier in this paper, there are many
non-coercive alternatives for aiding the poor.
