== Myth #22: Libertarians Are Pro-Prostitution And Pro-Narcotics!

The statist believes that if he regards an activity as undesirable then the
state should prohibit it. Accordingly, statists also believe that if
libertarians are against the state prohibiting an activity, then libertarians
must be for the activity itself, either personally or as a statement of values
that “society” ought to hold.

To pick on prostitution as an example, the myth runs that, since the
libertarian does not believe the state should forcibly throw people into cages
for voluntarily purchasing and selling sex, the libertarian therefore likes to
use prostitutes, wants to be a prostitute or believes society should endorse
prostitution.

=== This myth suffers from two fallacies.

*First* , as discussed at length in this paper, libertarianism is simply about
the appropriateness of the initiation of force in personal dealings. Being
against the use of force says nothing about how one evaluates the merit of the
personal dealings in question. Staying with the prostitution example, it is not
inconsistent for the libertarian to believe that, if two people want to engage
in consensual sex involving payment, they should be free to do so without the
threat of imprisonment, while at the same time not wanting to personally engage
in this type of activity nor wanting his loved ones to do so.

The libertarian believes that the question of whether a voluntarily undertaken
activity which doesn’t breach the NAP is good or bad should be answered for
each person through personal ethics, religion, cultural norms, etc., but not
through centralized legislation backed up by force. Yet the statist’s first
port of call whenever he wants to “suggest” a set of values for society is to
use the coercive powers of the state. The state is the bluntest possible
instrument to use in this situation, not only because it relies on force but
also because whatever solution it resolves on will be a “one-size-fits-all”
solution.

*Second* , in suggesting that we need the state to enforce (purported) societal
values, the statist is conflating society with the state.  footnote:[I’ve
discussed earlier in this paper how it is logically impossible to talk about
the values of “society,” since only individuals can hold values, and it strains
credulity to suggest that we could discern a common set of values on most
topics among millions of unique individuals.]

However, society is not the same as the state; society is much more extensive.
As noted earlier in this paper, society comprises many different voluntary
institutions as well as the state (e.g., families, neighborhoods, religious
groups, charities, mutual aid societies, businesses, etc.). To the libertarian,
one of the key roles of these non-state institutions, as has always been the
case historically, is to create and promote local norms, values and ethics to
help people lead better lives (however defined).

Thus for the statist to claim that, without the state’s use of force, things
like prostitution and narcotics would run rampant in a stateless society is to
shortchange the role and impact of these non-state institutions. Both history
and logic suggest that these institutions can be very effective in developing
local customs to discourage undesirable activities, promoting healthier
practices, or allowing for a more open, humane and effective way of dealing
with those who engage in these activities than the brutality of imprisonment.

Again, it’s critical to be clear about what libertarianism is and is not. It is
not a statement of personal values. It is simply a philosophy about when the
use of force is justified.
