== Myth #19: Somalia Disproves The Case For Libertarianism!

Years ago Somalia operated under a repressive statist regime, and then in 1991
this regime was thrown out and the country operated without a central state at
least up until 2006. Somalia is still desperately poor and dangerous, as it was
when it had a central state. Statists love to point to Somalia and say “Is that
how a libertarian society looks?!” However, this is an intentionally
disingenuous rhetorical question.

=== Comparisons Should Be Apples-To-Apples

When comparing libertarianism to statism, it’s not reasonable to compare this
across different cultures. Each culture has a different set of norms,
propensities towards violence, respect for others, capital stock, etc. The
libertarian is not suggesting that libertarianism will cleanse a rough culture
of its inherent characteristics; he is saying that, for a given culture, a
libertarian society will be more peaceful, just and prosperous than the statist
version. In other words, it is unreasonable to compare Somalia without a state
to the U.S. with a state; the latter may still be a better place to live
because of its preferable inherent characteristics. The more reasonable way to
approach this is to look at Somalia without a state compared with Somalia with
a state.

As it happens, there is some research that has been conducted on this point.
The paper summarizing that research suggests that living standards improved
once the state was eliminated.  footnote:[“Somalia after state collapse: Chaos
or improvement?” by Benjamin Powell, Ryan Ford and Alex Nowrasteh, _Journal of
Economic Behavior & Organization_ 67 (2008). Peter Leeson also has some
substantial commentary on Somalia, to similar effect, in his book, _Anarchy
Unbound_.] Per the conclusion in that paper, “[T]his paper’s main contribution
to the literature has been to compare Somalia’s living standards to those of 41
other sub-Saharan African countries both before and after the collapse of the
national government. We find that Somalia’s living standards have generally
improved and that they compare relatively favorably with many existing African
states. Importantly, we find that Somali living standards have often improved,
not just in absolute terms, but also relative to other African countries since
the collapse of the Somali central government.”

=== The Dangers Of Centralization

In a culture where violence is prevalent, the worst outcome is to have one
group in central control of the state, visiting its violence on the population
as a whole with no limiting factor, particularly where the state has first
disarmed the population through gun control legislation. In these situations
the cost of such violence to those at the state is minimal.

This has been a big part of the problem in some of the most despotic parts of
Africa, including Somalia. In these situations it would be better to have (a)
no central authority, but rather a range of competing warlords each of whom
acts as a countervailing force to the others, and/or (b) a fully armed
population. Then the cost to any would-be violent overlord would be
significant.

=== Culture Is Key To Outcomes

Statists irrationally fear that a place like the U.S. would become Somalia if
we didn’t have a state. However, a culture which is mostly non-violent and
generally respectful of individuals’ rights is likely to remain so in the
absence of a state, simply because those cultural norms are inherent in each
individual. In other words, a place such as the U.S. is not likely to devolve
into Somalia if we moved to a stateless society, because that is not how people
operate in the U.S. today when they have degrees of freedom.

To elaborate, in the U.S. today the vast majority of people peacefully accept
temporary rule from the political party which obtains a majority in any
election, even if they don’t agree with that party’s policies and legislation.
Statists who voted for the opposition generally don’t go around killing people
who voted for, or who are part of, the winning political party; they wait until
the next election to try to elect their preferred party. If that is the culture
we have now, it doesn’t make sense to worry that if the U.S. were to become a
stateless society ‒ where each group could voluntarily choose its own policies
all the time, instead of waiting for the next election ‒ we would descend into
depraved inter-group violence.

To put it a different way, if we’re not politically violent when living under
the opposition, we’re not likely to become politically violent when we don’t
have to live under any opposition.
