== Myth #20: Libertarians Are Shills For The Powerful!

Statists typically assume that the libertarian’s advocacy of the free market
means the libertarian is for the interests of big business and against the
“little guy.” However, contrary to what statists believe, libertarianism is the
only philosophy that is for the “little guy.”

Statism is characterized by special interests renting the state’s coercive
powers to benefit themselves (crony capitalism). Whether it is big
pharmaceutical companies, big agricultural companies, big oil companies,
defense companies, alternative energy companies, labor unions, Wall Street, the
environmental lobby, etc., the groups that make out best under statism are
those that lobby most intensively for state assistance in their operations
through tax privileges, subsidies, favorable regulations, tariffs, money supply
expansion, etc. This has happened throughout all of history whenever there has
been a state; it is not unique to any time period or region.

However, the one group that does not and cannot lobby as effectively as the
above interests is the group of individuals often each described as the “little
guy” or the “average Joe.” As noted earlier in this paper, the interests of
this group are too diffuse to organize, and the benefits to these individuals
from lobbying on any particular issue are outweighed by the costs of doing so,
even though the benefits from lobbying on all issues together would be
enormous.

As an entrepreneur, the “little guy” is left to try to make a living navigating
through the horrendous and costly maze of state-implemented regulations which
the special interests noted above have little trouble complying with and often
help write to make it harder for the “little guy” to compete. The “little guy”
takes whatever portion of

his income the state allows him to keep after the myriad of taxes levied ‒
which the special interests noted above can avoid through structuring, or
minimize by hiring expensive tax advisors ‒ and tries to support his family or
reinvest in his business or career.

As a consumer, the needs of the “average Joe” are left to be satisfied by
products that are more expensive and less available than they would be absent
the state’s interference (as discussed earlier in this paper). Unlike special
interests which rent the state’s coercive powers, his life is simply subjugated
to these powers.

Similarly, as a potential employee, the “average Joe” faces higher cost and
lower quality education and fewer sustainable employment opportunities than
would be the case if the state did not interfere in the free market.

In advocating for the free market, libertarians are simply asking that
everyone, big and small, play by the same rules, namely, whomever best pleases
the voluntarily purchasing customer will succeed. Libertarians should therefore
be understood to be pro-market ‒ which really means pro-consumer ‒ and not
pro-business.  Libertarians believe that the sole purpose of economic activity
is to organize scarce resources to best satisfy consumer preferences, and not
to safeguard any particular businesses or interest groups nor to privilege
those who want to rely on coercion.

As libertarian historian Tom Woods has noted, statists don’t appreciate the
irony that often the most vigorous opponents of the free market are so-called
“capitalists.” In the free market, businesses would face intense competition
every single day; however, if they can get the state on their side, this makes
things much easier for them. Thus we have the paradox that businesses – big
businesses in particular – may be against the free market while libertarians
are very much for the free market.

That hardly means libertarians are shills for the powerful.
