== Myth #15: It’s Every Man For Himself!

This is a favorite among statists. They envision the libertarian as a rugged
individualist, perhaps a survivalist, who wants to “live off the grid,” on his
own island, barely interacting with others. This only shows how little statists
understand libertarianism, society and basic economics.

=== There’s More To Society Than The State

In between the individual and the state there are many voluntary forms of
association. There are families, neighborhoods, businesses, marketplaces,
religious groups, common interest associations (e.g., athletic groups, artistic
groups, musical groups, etc.), charities, mutual aid societies, etc. All of
these groups allow humans to voluntarily interact with each other to serve
their needs. Since they are voluntarily formed groups, interactions only occur
because the respective parties believe they will each benefit.  footnote:[This
is not to say that these groups don’t have rules which “bind” members. They do.
However, unlike with the state, each member is free to join the group and to
leave the group if he no longer wants to be bound; without his explicit consent
a person cannot be obliged to pay anything to such a group; and a person can be
a member of multiple groups at once.]

All of these forms of association, and thus human interaction, would continue
to exist in a libertarian world; only the state would cease to exist. Statists
wrongly perceive the libertarian as being for only one thing, namely, himself.
In fact, the libertarian is not for any one thing, rather, he is against only
one thing, namely, the initiation or threat of force, whether by an individual
aggressor or the state.

=== Recognize People As Individuals

Statists misinterpret the libertarian focus on “individual rights.” This does
not mean that libertarians are against groups. To the libertarian it simply
means that rights are defined at the individual level – only individuals can
have rights, be wronged and do wrong – and that each individual has the same
right not to be coerced by any other.


The libertarian is concerned with equality of entitlement to this negative
individual right, not with the triumph of the individual over broader societal
groups.

In contrast, the statist is category-focused. He puts each individual into one
or more categories (e.g., “blacks,” “women,” “workers,” “the wealthy,”
“immigrants,” etc.), regards each individual in a category as being identical
to any other when it comes to advocating state policies, and believes rights
are “group rights.” footnote:[The most abhorrent aspect of the statist’s
classification of humans into categories relates to national aggression: if
state X (either through its military or one of its citizens) attacks state Y,
or offends the sensibilities or refuses to comply with the demands of state Y,
when state Y responds it does not differentiate between the guilty and innocent
individuals in state X. All are “fair game” for retribution, threats,
sanctions, etc., since all belong in the same category of “the enemy, state
X.”]

Libertarians, on the other hand, regard each individual as unique and
irreplaceable. Thus the libertarian is the champion of each individual as his
own sovereign being and not just as some member of a category.

=== Not Isolationist

The libertarian is a staunch advocate for free trade between individuals, which
contradicts the notion that libertarians are isolationist.

As discussed earlier in this paper, no man can produce for himself all that he
needs and any man would be foolish to try to do so, since every man can profit
from specializing in what he does relatively better and trading with other men
who do other things relatively better. This concept ‒ the division of labor ‒
has been one of the greatest boons to global wealth creation over the past few
centuries and is partially responsible for moving man out of a subsistence
existence to where he is today.

The libertarian recognizes this, and his “individual rights” principles do not
in any way reduce his appetite for specialization and trade. All libertarianism
demands is that trade be voluntary, not coerced.

=== Only Individuals Can Act

The statist assumes that his preferred form of forced collectivism is more just
than the so-called “individualism” that he sees within libertarianism, without
really thinking too hard about what forced collectivism means.  footnote:[Note
that the libertarian has no quarrel with “collectivism” if it is voluntary,
such as all forms of voluntary groups. It is forced collectivism (the state)
that is objectionable.]

A group cannot think or act; only individuals can think and act. Thus, even
within collectivism, some individual has to make and implement a final
decision. That individual, as a human being, will bring to that decision and
its implementation whatever personal biases, incompetence and ideology he
possesses.

The libertarian’s point is not that the statist necessarily has deeper personal
biases, greater incompetence or a more passionate ideology than the
libertarian. Rather, the libertarian’s point is that, under statism, the ruling
individual’s personal biases, incompetence and ideology will, through his
enactment or enforcement of legislation or execution of foreign policy, be
coercively imposed on everyone whether they want to have any interaction with
this person or not, whereas in a libertarian society no individual’s personal
biases, incompetence or ideology will be imposed on anyone except for those who
voluntarily choose to interact with that individual (assuming, of course, that
such individual is not violating the NAP).

In other words, statism is really just one person’s individualism imposed on
others.

