== Myth #18: There Goes The Environment!

Statists assume that the environment will go to hell if we don’t have the wise
custodians at the state looking out for Mother Earth. Their incorrect
assumption is that, in the absence of centralized coercive regulations, there
will be no regulation at all of human activities.

The shortcomings of state regulation of the environment were discussed earlier
in this paper. I’ll provide below some ideas of how environmental regulation
might work in a libertarian society.

=== Rely On Private Property Rights

What the statist line of thinking misses is that environmental problems are
nothing more than property disputes: A’s activities cause damage to B’s body or
property for which B can take action against A to stop the activities (through
an injunction) or be compensated for his losses (through an award of money
damages). This is no different from any other property dispute in society.

Thus in a libertarian society these issues would indeed be resolved as property
disputes. For instance, if A’s activities emit pollutants which cause a loss of
enjoyment by B of his property or damage to his body, then, subject to one
exception, A would have initiated aggression against B’s property and would be
liable.

The exception relates to homesteading. If A were engaging in these activities
on his own land next to unowned land, and subsequently B homesteaded the
unowned land, then A would be said to have homesteaded the right to continue
these activities before B homesteaded the unowned land, and thus B would
acquire a property right in this land subject to A’s right to continue with his
prior level of activity. In other words, B could not complain about A’s
activities if he moved in and these activities were already going on. However,
if A increases the volume of his activities or changes their nature then A
could be liable to B as A would not have homesteaded the right to these
increased or different activities.

Conversely, if B homesteaded the land before A commenced these activities then
B would be deemed to have homesteaded the right to a pollutant-free enjoyment
of his property, and A’s subsequent initiation of these polluting activities
would render him liable to B.

Any subsequent purchasers of either A’s or B’s land would purchase these plots
of land with whatever homesteaded rights the seller (A or B) had.

In all cases either party would be free to approach the other to try to
negotiate a different set of rights. Unlike what happens under statist regimes
‒ whereby regulations are made without taking into account the preferences of
the respective property owners (instead, the preferences of those at the state
and their lobbying interests are imposed coercively) ‒ such a private
negotiation would enable expression of the relative value preferences of the
parties for continuing to pollute, or for clean air, as the case may be.

For instance, if B had the right to stop A from polluting, A could do one of
several things: (i) pay for technology and processes to reduce or eliminate the
pollution; (ii) pay B sufficiently for B to install protective features on his
property to reduce or eliminate his losses; or (iii) buy B’s property outright.
Whether A chooses to do any of these things would reflect how valuable he
regarded his polluting activities, and whether B agreed to (ii) or (iii), and
for how much, would reflect how valuable he regarded remaining in place free of
pollution.  footnote:[Obviously no individual at the state can know what A’s
and B’s value preferences are, and it would be highly coincidental if
centralized regulation just happened to accurately reflect these preferences.
Also, state regulatory regimes would not recognize the sequencing of
homesteading, and thus would generally assume that B has an absolute right to
live on his land free of pollution when in fact A may have been there first
engaging in his polluting activities.] 


If an environmental group took a different view from B regarding what is
acceptable on his property, and thus regardless of B’s views wanted to reduce
A’s polluting emissions further, that group would be free to do one of several
things: (x) try to buy A out of his land and shut down his factory; (y) pay for
A to reduce his emissions to the level that the group feels is acceptable; or
(z) buy B’s property and fight A as the new adjacent property owner.  How much
the environmental group would be prepared to pay for these options would
reflect how valuable they regarded the reduction of emissions.  footnote:[This
is very different from today’s statist regime where the environmental group
would rent the state’s coercive powers, at little cost to that group, to impose
its preferences on A and B through regulation; such an outcome would not
reflect in any way the respective value preferences of the two property
owners.]


=== Private vs. “Public” Property

One of the main environmental issues in statist regimes is that a lot of land
and waterways are publicly owned.  footnote:[As noted earlier in this paper, to
the libertarian the state cannot legitimately “own” any property since it uses
funds or labor coercively obtained to claim such ownership. I use the word
“own” here to mean the assertion of control.] This has three ramifications.

*First*, no one maintains property as well as the actual owner who has his own
capital invested; look at the state of public housing and public parks compared
with private housing and private parks, respectively.

*Second*, when the state owns property, at best it tries to balance the
interests of different groups, and generally ends up satisfying none or few of
them; if one of these groups owned the property itself it could protect its
interests more vigorously.

*Third*, what often happens is that the most aggressive lobbying group ends up
effectively controlling the property through getting state regulations written
in its favor, and thus it coercively “buys” the property at a huge discount (if
it pays anything at all) compared with what it would have had to pay in the
free market.

Contrast this to the libertarian world in which all property would be privately
owned (unless unowned). Thus, for example, rivers would be privately owned. As
noted earlier in this paper, the owner of a river would have invested effort
and capital into homesteading the river or buying it from a prior legitimate
owner, and therefore would have the best incentive to keep it pollutant-free
either for his own use or because he wants to supply clean water to his
customers (e.g., local residents or businesses). The standard of cleanliness of
the river would be much higher when privately owned than when controlled by the
state, where no one has the same level of vested interest as a private owner.

If the river owner contracted with local customers to supply them with clean
water, if he failed to deliver such water he would lose customers and could be
sued. He would therefore have a big incentive to take remedial or preventive
action against polluting factories or other actors which are upstream. The
downstream users wouldn’t have to interface with the factories to determine who
was responsible; their grievance would be against the river owner.
footnote:[When discussing the notion of private ownership of resources like
rivers, the statist worries about what would happen if a private river owner
decided to cease supplying water to his customers. That would be commercial
lunacy and therefore highly unlikely (we don’t see private suppliers of other
critical items, such as energy, food or shelter, hoarding their inventories).
Of course he might insist on different pricing regimes which would ensure that
those who valued the water the most would pay appropriately. However, there
would always be an opportunity for competitors to supply water to these end
users. For instance, today in the U.S. there are companies that deliver bottled
water to businesses and households which are already connected to public water
supplies. Other competitors may install rainwater tanks or come up with other
ideas we cannot conceive of from our armchairs. Besides, this cessation of
supply happens today under statist regimes: if the environmental lobby is
particularly successful, water can be coercively diverted away from end users
in favor of endangered species; if the farming lobby is particularly
successful, water can be coercively diverted away from residential users in
favor of farms.]

Air pollution would be dealt with in a similar manner. All of the roads would
be privately owned, so if someone living adjacent to the road (who has
homesteaded a right to clean air) suffers from air pollution, he wouldn’t have
to worry about which cars caused this pollution; instead, as noted earlier in
this paper, his cause of action would be against the road owner. The road owner
would thus have the incentive to manage the traffic on his road to ensure that
impermissible levels of pollution were not emitted; for instance, he might
require inspections of vehicles before granting them permits to drive on his
roads.

=== The Roles Of Insurers And Pollution Consultants

Note that it is likely that the river owner, the road owner and the factory
owner would have liability insurance, and their insurers would require or
financially motivate these businesses to take appropriate actions to ensure
that they minimize the risk of environmental lawsuits. These insurers would
bring current “best practices” from their portfolio of similar clients, so in
this way those methods that were most effective would spread among different
regions but be tailored to the specific circumstances in each case and be
updated in real time as circumstances change.

Contrast this to the centralized regulations imposed by the individuals at the
state today, which are “one size fits all,” often lag market or technological
developments, and are written based on input from lobbying interests as opposed
to what is most effective.

The insurers would not necessarily be the experts in matters such as measuring
pollution, determining causation, assessing pollution control technology, and
compliance and monitoring. In a society in which such services would be in
demand from insurers, businesses and litigants, it is likely that expert firms
would arise. These “pollution consultants” would sell their services to
insurers, polluters, and plaintiffs and defendants involved in or contemplating
litigation. Unlike today’s state regulators, who purport to serve as these
consultants but are really coercive monopolists lacking proper financial
incentives, in a libertarian society the pollution consultants would have to
compete for the dollars of their customers. Those that develop a good
reputation will garner more business and those that provide shoddy services
will lose business.
