== Myth #14: Libertarians Are Utopian!

Statists like to claim that libertarians are utopian and their system is
unworkable. It’s worth exploring these concepts a little further.

=== The Kids Get It!

Even statists reliably teach their young children two basic rules for when they
interact with other children, which neatly sum up libertarianism: “Don’t hit
the other kids and don’t take their stuff.”

Yet when the statist’s child is old enough to learn about politics, the statist
turns his philosophy around 180⁰ and tells his child that, provided you can get
a majority of people to tell you it’s fine to do so (i.e., get elected), you
are free to effectively hit or threaten to hit others and to take their stuff.

Thus, by their own characterization, statists start out as “utopian” teachers
to their children.

=== Exactly Who Is Utopian?

A commonly accepted definition of “utopia” is a place of ideal although
unattainable perfection, especially in laws, government and social conditions.

Consider, however, what the statist believes: (a) that individuals at the state
who have the awesome monopoly on coercion in a region will only act selflessly
and will impose limits on themselves footnote:[In other words, that the Tooth
Fairy Theories are credible explanations of humanity.  ; (b) that, as a result,
“limited government” is possible, even though in the history of the state all
that has ever happened is that the state has grown enormously; (c) that there
are some individuals who are so omniscient as to be able to discern a “common
good” for millions of other people and to efficiently manage the flow of
society’s resources to attain that end; (d) accordingly, with respect to
organizing an economy, relying on a coercively imposed, central planning
monopoly is more likely to maximize individual consumers’ satisfaction than
decentralized competition; and (e) that use of centrally directed force as the
first tool to resolve societal conflicts is likely to lead to a more peaceful
society.]

On the other hand, libertarians accept human foibles for what they are and
believe these foibles are inherent in everyone, without exception, and thus
look to mitigate the impact of these foibles by objecting to the centralization
of coercive power in any individuals. The libertarian recognizes that there is
no “common good” among millions of different people (or, if there is, no human
can discern it) but that each individual has his own preferences, and that
since no man can produce all of his needs, to satisfy his preferences he must
trade with others to obtain what he cannot produce himself. In a truly
voluntary society the norm would be that, to obtain something you want, you
first have to produce something someone else wants and then engage in an
exchange, so there would be mutual gain (this is not fantasy: although we live
in a statist world millions of these exchanges actually occur daily). Thus
everyone who is compliant would be looking to peacefully “please” others as the
route to their own happiness, as opposed to being able to forcefully impose
their needs on others. Those who are not compliant and who initiate aggression
can still be restrained or excluded by force.

Now, exactly [underline]#who# is utopian?

The statist never really compares the state as it [underline]#actually# works against the
few glimpses of the free market we can find in the real world, presumably
because the evidence is so dauntingly adverse to his position (what serves
consumers better, our state-controlled military, health care/insurance,
financial or education systems, or the iPhone or bagel supply systems?).
Instead, the statist imagines the state working perfectly (where the
individuals at the state are angels) and compares this to the imperfection of
the free market (where the individuals are humans). This is not utopian
thinking?

The libertarian, rather than expecting utopia, simply believes that the NAP is
the most just governance principle because it outlaws (although by no means
eradicates) the initiation of force and thus violent conflict. In contrast, the
statist believes that the most just way to run society is to institutionalize
violent conflict by empowering those individuals at the state to initiate or
threaten force.

=== Only “Negative” Rights (Duties) Are Workable

Moral philosophy deals principally with the search for just principles of
interaction among human beings. Two minimum requirements for a just system are
that the principles (a) are universal and (b) promote human survival.  The
first requirement simply recognizes that all men are born equal and thus must
be entitled to the same treatment at the hands of their fellow men. In other
words, no man has any natural entitlement to special treatment (for better or
worse). The second requirement recognizes that the first is not sufficient if
we are trying to sustain humanity and human interaction (if we are not, then it
makes no sense to try to reason out a moral philosophy!). For instance, a
philosophy that advocates all men commit suicide would be universal but hardly
achieves much in the way of sustaining humanity.

So how do libertarianism and statism measure up as moral philosophies?

Libertarianism’s central principle is non-aggression, which is a “negative”
right.  footnote:[In philosophy a duty is the correlative of a right. Thus if A
has the “duty” not to initiate force against B, B has the “right” not to be
aggressed against by A. Accordingly, one can talk of the NAP as either a
negative “right” or “duty.” The commonly used terminology which captures the
general concept is “negative rights,” which I have therefore used here.] Thus
it is one behavioral standard that, as a technical matter, can be universally
applied, meaning that it is technically possible for every man to live by this
standard concurrently with every other man. This is because the NAP simply
outlines what one cannot do to his fellow man, namely, initiate interference
with his body or property. There cannot be any conflict among men as regards
their negative rights. Everyone can live with and profit from the
non-initiation of force at the same time (however, as noted earlier, but it
bears repeating, the NAP is a minimum, as opposed to a comprehensive,
behavioral code). Thus the libertarian philosophy provides a workable universal
standard and, as noted above, it also inherently discourages (outlaws) violent
conflict and hence promotes human survival.

In contrast to libertarianism, the statist’s philosophy has many “positive”
rights embedded in it, meaning that it prescribes what one man can take from
another’s property or require of another’s body (through regulations and taxes
backed up by the threat of force).  footnote:[As a technical matter
libertarianism also recognizes positive duties, but *only* if they are
voluntarily assumed as opposed to involuntarily (forcibly) imposed by
legislation, which is the hallmark of statism’s positive duties. In
libertarianism one can voluntarily assume a positive duty either by entering
into a contract or by actively putting someone in a precarious position. As an
example of the latter (per libertarian attorney Stephan Kinsella), if you push
someone into a lake you assume the positive duty to rescue them, whereas if you
merely walk by and see someone in the lake struggling you cannot be positively
required to rescue them under the threat of force, even though it might be the
right thing to do as a fellow human. As another example, the parents of a
newborn, by bringing the helpless child into the world, assume a positive duty
to arrange for the due care of the child until he is independently capable of
looking after himself.] Through the use of positive rights backed by the
initiation of force statism cannot provide a workable universal standard that
promotes human survival. *First* , one man’s positive rights necessarily conflict
with another man’s negative and positive rights. The person who is forced by
another to give up something or do something with his body has his negative
rights violated ‒ the rights to have his property and body left alone ‒ so the
statist must argue that some men don’t have these negative rights (but why, and
how are these men to be identified?). In addition, given scarcity, positive
rights cannot be universally applied to or enjoyed by every man concurrently,
as not everyone can enjoy the right to the same physical object at the same
time. In fact, only one man can use any physical object at a time, so who gets
to choose who prevails? *Second* , if nevertheless the statist wants to try to
argue that his is a universal principle, he would have to argue that every man
has the right to use force to take what he wants. Does that really make sense
as a behavioral standard to promote human survival?

Thus whereas the NAP is both technically feasible on a universal basis and
designed to discourage conflict, statism’s use of force principle is either not
universal (if it implies that only some men are naturally entitled to initiate
force) or is an “all against all” principle that can only lead to ultimate
societal degradation. Accordingly, I would argue that it is statism, as opposed
to libertarianism, that is not a workable moral philosophy.

[centered]#* * * * *#

To the extent that the statist is aware of the NAP he often misunderstands its
implication. One major criticism levied by statists is that believing in the
NAP is nice, but it’s just like saying “Do the right thing,” namely, it’s apt
to regularly fail since some people will still act aggressively. However, the
purpose of the NAP is *not* to eradicate aggression (although the more people who
subscribe to the NAP the less aggression there would be) but, rather, to
*allocate liability* based on this principle. Libertarians fully recognize that
there will always be aggression and disputes, but suggest that the NAP be the
guiding principle in resolving these disputes.
