== Myth #16: Libertarianism = Chaos!

Statists assume that the absence of government means an absence of governance,
and thus that libertarianism implies societal chaos. Nothing could be further
from the truth.

=== The Market Can Provide Law & Order

Libertarianism assumes that there would be conflicts that would need to be
resolved, requiring adjudication tribunals using developed bodies of law
similar to how the courts we have today function. Libertarianism also assumes
that there would be aggression both from individuals and, if they exist,
non-libertarian societies (i.e., states), thus requiring protective services
similar to today’s police and military forces.

The principal way in which libertarianism differs from statism in the areas of
law and security is that libertarianism implies that the police, courts and
military would, like all other services, be provided by competitive suppliers
which can only earn revenues from customers who have freely entered into
contracts with them. Accordingly, these service providers would have to provide
ongoing value and innovation to keep their customers; contrast this with
statism where these types of services are generally provided by a state
monopoly, which therefore means ever higher compulsory prices in the form of
increased taxation and ever lower service levels.

Libertarianism also assumes that bodies of law will be developed locally from
the ground up through adjudication of actual disputes, as was the case
historically before states forcibly assumed legislative power (as detailed
earlier in this paper). Contrast this with the arbitrary, “top down” statist
legislation of today that applies to all citizens prospectively, even those not
involved in any dispute.  footnote:[Note that top down, “one-size-fits-all”
legislation requires more heavy-handed enforcement than adjudication principles
developed from the bottom up from actual disputes. This is because, in the case
of the former, there is no communal “buy in” because citizens have not been
involved in arguing for and against the rules, and these rules may not reflect
local customs but rather the arbitrary whims of distant legislators.]

The statist’s argument in this area is essentially the “public goods” argument,
namely, that if we don’t have a state monopoly providing law and order services
then these services won’t be provided at all or sufficiently. Earlier in this
paper I detailed the responses against the “public goods” argument from the
historical, moral and economic perspectives.

However, an additional reason this argument fails is because it doesn’t
acknowledge that history shows quite convincingly that, if there is demand for
a product, individuals have always risen to the occasion and developed the
product without the state’s involvement (sometimes as entrepreneurs, other
times as end users). Simply because the statist sitting in his living room
can’t envision how this would unfold doesn’t mean it won’t get done; it just
means the statist is clearly not going to be the person who develops the
solution! No one ever sat down and centrally mapped out how money or language
might develop. There was a need for these two concepts and so individuals
engaged in trial and error until they found the optimal solutions (at least
until money was forcibly taken over and debased by the state for its own ends).
The statist cannot explain logically why the default should always be a
coercive monopoly provider simply because he cannot conceive of how something
might develop differently.

It is beyond the scope of this paper to go into detail about how courts, law,
police and military services might be provided in a libertarian society. No one
can say for sure, just as no one could have predicted in advance how things
such as today’s communications technologies or variety of breakfast cereals
would develop. Indeed, if it were possible to specify exactly how things would
get done in the future that would be the best argument for statism, as then
central planning would be the answer!

There is, however, a very rich body of intellectual work that exists in this
area to provide some guiding thoughts, based both on historical and current
examples and compelling logic. Drawing on this material, below I will provide a
glimpse of what a libertarian law & order system might look like. I will treat
national defense in a separate section later.

=== Self-Defense

The first thing to note relates to self-protection. As discussed earlier in
this paper, one of the first things states do is disarm their citizens through
gun control legislation. The alleged “deal” imposed coercively is that citizens
give up their right to arm themselves in return for the state’s protection from
violent crime. Yet when the state’s police cannot realistically be at the scene
of every (or perhaps any) violent crime while it is actually occurring, of what
value is this “deal”?

In a libertarian world there would be no restrictions on firearm ownership ‒
although of course there would be liability for misusing firearms to initiate
aggression against others ‒ which would significantly increase each citizen’s
self-defense options.  footnote:[Note that in a libertarian society all
property would be privately owned and it would be entirely consistent with
libertarianism for a private property owner to prohibit possession of firearms
on his property.]

=== Policing

Beyond enhanced self-protection, in a libertarian world instead of being forced
to pay taxes to the state to provide a “one-size-fits-all” police force,
individuals would choose among different “protection service” providers and
voluntarily pay them for their services. These service providers would compete
on price and service and would offer a menu of different options. Unlike the
state’s police, those providers that fail to address actual customer demand
would go out of business and those that meet demand would make profits
footnote:[This is not fanciful; the industry already exists in the U.S. today.
In fact, there are more private security personnel than state police.]

There may be firms that specialize in residential premises protection and
others that specialize in commercial premises protection. Some may emphasize
“feet on the street” preventive community policing, others may prefer the
technology-based approach to surveillance, and still others may provide
undercover policing. Some may arm their personnel with firearms, others merely
with less lethal means. Some may focus on hiring certain ethnic types to
provide ethnic-group-oriented services in the appropriate neighborhoods.

Unlike the state’s police, security providers would have no special immunity
for their actions. Those providers that act with excessive violence when
performing their services would lose customers who do not support this type of
policing and, as word gets around, they may not be able to attract new
customers. They may also face lawsuits from those against whom they act with
excessive violence; if they lose these lawsuits, payment of the judgments would
increase their operating costs. Such companies may then try to pass on these
higher costs to their customers in the form of higher prices or reduced
services, and this would cause them to lose customers to competitors which have
lower operating costs because they are less violent and thus can offer better
pricing and/or service options.

=== Criminal Justice

Crime would no longer be something for which the state takes action; it would
exclusively be a matter between the victim and the aggressor, and victims would
be able to take action against aggressors without being stymied by state
intervention.

The definition of “crime” would be limited to initiating aggression against
another person’s body or legitimate property, i.e., there would be no
“victimless” crimes arbitrarily created by state regulation. Thus the law would
once again become comprehensible to everyone, and policing by security
providers would be more focused, only concerned with protecting against or
investigating actual violent acts against person or property.

Instead of the state’s “our way or the highway” approach to punishment ‒ which
tends to be focused on deterrence and rehabilitation (although the state’s
system is woeful at achieving even these objectives) ‒ different punishment
systems would arise in different communities based on what is acceptable in
those communities. It is likely that these systems may all be based on
restitution and compensation, but some may also provide for retribution.

Victims who, for moral or practical reasons, didn’t want to exact the maximum
acceptable punishment on their aggressors could agree with the aggressors on
lesser punishments on a customized basis. A victim who exacted more than an
acceptable punishment on an aggressor would himself be liable to be sued by the
aggressor for unfounded violence, which would therefore place limits on how
aggressively victims act.

=== Adjudication Of Disputes

Disputes would be adjudicated by private mediation and arbitration providers.
footnote:[This actually happens today; private mediation and arbitration is a
large and growing industry due to dissatisfaction with state court systems]
Different providers would offer different types of dispute resolution
procedures, with some specializing in different subject matters and others
specializing by geography, religion, culture or other factors.

Those “judges” who develop a reputation for fairness and subject matter
competence will garner more business, and those who develop a reputation for
undue bias and/or incompetence will lose business.

Different groups – such as Catholics, orthodox Jews, Quakers, those against
capital punishment, etc. – might prefer their own forums to use their own
customs to adjudicate intra-group disputes. For inter-group disputes the
parties would have to agree on an independent adjudicator, and this would tend
to cause different systems’ approaches to converge over time as successful
adjudicators render judgments acceptable to both groups.
footnote:[Historically this is how all legal systems developed, based on local
customs and community acceptance of gradual changes in norms to deal with new
situations that arose.]

=== Enforcement

If a victim couldn’t or didn’t want to pursue an aggressor himself he may be
able to retain an enforcement company (or sell this company his right to punish
the aggressor which, depending on the relevant societal norms, may include the
right to use force footnote:[The transfer of enforcement rights is generally a
feature of insurance today. Policyholders agree to let their insurance
companies pursue the other party in return for quick payment from their
insurer.] Perhaps this company would be entitled to a fee based on the speed of
solving the crime and/or the amount of compensation it recovers for the victim
from the aggressor. Therefore, unlike today’s police, such a company would be
aligned with the victim’s interests and highly motivated to solve the crime,
pursue the aggressor and exact the punishment. Yet, unlike today’s police, this
enforcement company would have no special immunity, so that if it employed
excessive violence in its activities it could face lawsuits from the original
aggressor, and thus potentially higher operating costs, as well as develop a
bad reputation, all of which could spell trouble for its business model.

If an aggressor developed a bad reputation by (a) being a repeat offender, (b)
not submitting to dispute resolution procedures, or (c) not complying with
judgments against him, then, depending on societal norms, he would risk being
subject to force and/or being ostracized by his personal and/or business
community, and could be excluded from local trade or employment or, since all
property would be privately owned, by the owners of local roads, stores,
schools, etc.

Companies may arise which specialize in tracking such aggressors, creating
easily accessible “reputation reports” like today’s credit reports; these
reports would be used by the community to deny such aggressors access to all
sorts of private property, employment or trade. Thus, rather than forcibly
remove these aggressors to the brutal confines of today’s state prisons, the
community’s punishment might be widespread exclusion.

=== Detention

For those aggressors who are sufficiently ostracized and thus have nowhere else
to go, there may arise detention companies that offer room, board and
employment, provided these aggressors agree to certain behavior restrictions
and supervision. If aggressors owe debts to their victims (or the victims’
enforcement companies) but cannot pay, these detention companies may purchase
these debts and then the aggressors would have the opportunity to work off
their debts in the employ of the detention companies (or their nominees) while
being confined as agreed.

The detention companies may offer to the aggressors to certify to the
reputation tracking companies that, once the aggressors have worked off their
debts and/or maintained certain behavior standards, they are deemed
“rehabilitated” and can be taken off the list of those to be shunned by
society.

Unlike today’s state prisons, the detention companies might compete with each
other to attract aggressors, since they could make a profit on the aggressors’
labor, and thus there would be some efforts to provide acceptable living
conditions for aggressors. If these detention companies breach their agreements
with aggressors, or employ undue aggression against them, they could in turn be
sued by the aggressors. In this type of environment aggressors are much more
likely to be rehabilitated and gain/maintain valuable job skills than in
today’s “rape factories” and “violence training camps” that masquerade as state
prisons.

=== The Role Of Insurers

As a final thought, it’s likely that individuals and businesses wouldn’t
necessarily have to contract with all of these different companies to obtain
these services. Instead, life, health, property and liability insurers may
offer these services to their customers bundled into their insurance policies.
footnote:[Another alternative is that landlords could build these services into
their leases with tenants, and property developers into their maintenance
agreements with residents.] The insurers would then take on the responsibility
of finding the best providers of each service and contracting with and
monitoring them. Their policyholders would be contractually bound by the
policing, adjudication, enforcement and detention systems bundled into their
policies. Thus an insurer could easily resolve disputes between two of its own
policyholders, who would have agreed in advance to be bound by the systems the
insurer put in place.

Insurers would also be motivated to establish in advance among themselves
dispute resolution procedures to use when policyholders of two different
insurance companies have a dispute. This is because (a) they know that there
will be multiple such situations over time in which sometimes their
policyholders will be the victims and other times the aggressors, so they have
to act fairly at all times if they expect reciprocity from other insurers, and
(b) it is always less costly to resolve disputes peacefully than through
violence, and the insurers would be the entities liable to make payouts.
footnote:[This is exactly what happens today among insurers. For instance, when
there is an automobile accident the two insurers don’t go to war; they resolve
things peacefully based on procedures established in advance.]

Insurers would also be motivated to contractually try to alter the behavior of
their policyholders to reduce the incidence of disputes and the quantum of
losses. This happens today when insurers offer discounts on premiums for
defensive living (e.g., for installing a burglar alarm, taking a “safe driving”
course, etc.), and use deductibles to ensure the customers have some “skin in
the game” before the insurance kicks in.
