== Myth #24: Libertarianism Is A Futile Endeavor!

Statists often criticize libertarianism on the basis that it is unrealistic and
that libertarians are too idealistic. We are told that such a society has never
existed and will never exist, so why bother believing in it and pursuing it as
an organizing principle?

There are a number of ways to respond to this, both in terms of principle and
in practice.

=== Principles

*First*, by the above metrics statists are idealistic too. For instance, they
would desire a world without murder yet none has ever existed or will exist,
but statists still try to educate others as to why murder is wrong and try to
reduce it where possible.  footnote:[Here I mean “murder” as statists define
it, which excludes killings by or on behalf of the state.]

If “idealistic” means advocating for something different from the current state
of affairs, then who isn’t idealistic?

*Second*, political philosophy and the organization of society have been
evolving for thousands of years. Who is to say that we’re at the end point of
history in this regard?

When the Roman Empire was at its zenith, ruling the known world, it might have
been difficult to conceive that an alternative would one day emerge. Likewise
when monarchy was the prevailing system in western Europe. In the 18^th^ and
19^th^ centuries when slavery was a global institution in the so-called
“civilized” countries, it might have been very difficult to conceive that one
day most of the world would recognize its abhorrence. For those living under
eastern European communism in the 20^th^ century, it might have been very
difficult to conceive that one day they would be living free of that yoke.

Political organizational forms change over time, and it seems that as time goes
on the changes happen more rapidly, perhaps because new technologies allow new
ideas to spread more rapidly. So who is to say that it is impossible that
growing numbers of people could reject the idea of the state and form stateless
mini-societies?

*Third*, if you believe that a particular principle for organizing society is
just ‒ in this case, the NAP ‒ then even if you cannot hope to immediately
attain 100% of your ultimate goal ‒ in this case, a stateless society ‒ how can
you work to move society towards that goal until you first set that goal? In
other words, you first need to know your destination before you can set out on
your journey. You don’t need to magically appear instantly at your end
destination to achieve success (although that would be nice!); you can set your
destination and then continually take incremental steps towards it.

Libertarians believe in the moral superiority of a stateless society and, by
setting this as the destination, it becomes very clear which policies in
today’s society to oppose and which to support. It means having a guiding
principle, as opposed to just going by “gut” or blindly following a political
party or personality.

=== Practical Steps

Even in today’s overwhelmingly statist world it is not true that libertarians
are undertaking a futile endeavor.  There are a number of meaningful things
libertarians can do and are doing today, as set out below.

*_Pursue and Promote Alternative Education_*. As discussed earlier in this paper,
the state can only exist with the acquiescence of the majority of the
population, because the individuals in the private sector vastly outnumber the
individuals at the state (as large as that number is). Thus educating people
about the true nature of and problems with the state, and the fact that there
is a real alternative to the state, must surely be a first step in turning that
acquiescence into skepticism, if not outright opposition.

Historically the state has had a huge advantage in influencing the content
taught in schools and at college given the all-pervasive, purposeful control of
education by the state and the intellectuals who support it. However, with the
advent of the Internet and powerful mobile devices, alternative content is now
easily within the reach of those who want to learn about different political
philosophies, whether at home or on the go, and there is a growing array of
homeschooling and self-study resources available at one’s fingertips. Thus
there is good reason to be optimistic in this regard.^193

As the societal conflicts caused by statism grow more extensive and more
intense, and as more national crises cause people to question whether the
current system is the best we can hope for, many people ‒ particularly the
young ‒ are looking for new ideas. The libertarian should not only keep
improving his own understanding of libertarian principles but, even more
importantly, should provide those who are looking for an alternative with
guidance on how to find the rich body of libertarian educational resources that
exist.

*_Refrain From Participating in Elections_*. Of all the arguments for the state,
the statist’s favorite is that elections indicate the consent of the population
to the state and its policies. The state gleefully uses voter turnout figures
to claim that there is a post-election mandate for this or that, and that “The
people have spoken.”

Thus the libertarian should refrain from voting and try to convince others to
do the same, to do his part to reduce voter turnout. Leaving aside the fact
that, based on probability, voting is a waste of a citizen’s time –
statistically, the chance of a single vote determining the outcome of an
election, and then of that outcome leading to implementation of the voter’s
desired legislative or executive policy, is infinitesimal – to the statist the
fewer the votes cast the weaker the mandate coming out of an election. If a
weaker mandate means less state activity, that is generally a good thing for
the cause of liberty.

Another way to think about elections is that, in the grand scheme of things,
they don’t change anything material; all that happens is that a different team
is put at the helm of the destructive vessel that is the state.  footnote:[A
relevant comment often attributed to Mark Twain is that "If voting made a
difference, they wouldn't let us do it." For instance, in a typical national
election season Party A argues for a 40% tax rate and Party B for a 35% tax
rate, but there is no chance anyone will conclude that taxes per se are
illegitimate; Party A argues the state should bomb or invade state X and Party
B argues for aggression against state Y, but there is no chance anyone will
conclude that all state aggression is illegitimate; Party A blames group J for
society’s woes and Party B blames group K, but there is no chance anyone will
conclude that the state itself is the cause.] What really changes society is
public opinion: the abolition, women’s suffrage, civil rights and gay rights
movements all preceded state legislative or judicial action. Thus instead of
investing the time to work on a candidate’s campaign or to research candidates
or vote, the libertarian might consider a better use of his time to be working
to change public opinion through whatever means he prefers.  footnote:[These
comments only apply to broad elections in which there is not a specific
question on the ballot subject to a binding “Yes/No” referendum. However, were
there to be a specific question up for vote in a binding referendum, such as
“Should we eliminate the property tax?” or “Should we approve the public school
budget?”, leaving aside the statistical argument it could make sense for the
libertarian to vote since there would be a definitive opportunity to reduce
state coercion.]

*_Ridicule “Public Service.”_* Statist’s laud “public service” – meaning working
for the state in either a civilian or military role ‒ as a very honorable
activity.

The libertarian should do what he can to persuade family, friends and
colleagues to avoid joining the state’s apparatus, by illustrating how working
at the state is actually something to disdain as immoral rather than something
to revere. In this way the libertarian can not only do his part to reduce the
size of the state but also to keep more people in the productive and moral
private sector, which is ultimately better for societal prosperity.


*_Promote Nullification_*. Nullification simply means rejecting the legitimacy
of a piece of legislation and therefore refusing to comply with it. Peaceful
nullification can be pursued in two main ways in the U.S.: by state governments
and by jurors. I’ll deal with each of these in turn.

*First*, state governments can nullify federal legislation which they believe
is unconstitutional based both on historical precedent and the structure of the
Constitution.  footnote:[For a detailed analysis and history of the use of
nullification in the U.S., see Tom Wood’s book, _Nullification_.] In general
this means passing state-level legislation to the effect that no state
government personnel or resources will be permitted to assist the federal
government in enforcing the relevant federal legislation within the state. This
can be a very effective means of constraining the power of the federal
government, which often relies to a large extent on the cooperation of state
governments.

This has gained currency in recent times as evidenced by various initiatives at
the state level to restrict or negate such federal government programs as
spying on citizens by the National Security Agency, gun control, Obamacare, the
“War on Drugs” and the Common Core education curriculum_._ While the
libertarian has no greater affinity for state governments than for the federal
government, the libertarian should support and encourage one arm of the state
(broadly defined) taking on another arm if the net effect is to reduce the
overall activities of the state.  footnote:[Thus it would not make sense to
support an initiative at the state level which simply substitutes state
government activities for the federal government’s activities, or which adds
more intervention than it reduces.]

While state nullification is an effective way to oppose the federal government,
it doesn’t have any impact on the unjust activities of state governments. As a
practical matter it is of course entirely open for local governments to try to
use the same strategy against state governments. However, as a matter of
constitutional structure local governments do not really have this option.
footnote:[By “constitutional structure” I mean that there is a solid basis for
state nullification because the several states, as principals, established the
federal government as their agent and granted to it limited powers through the
Constitution. By definition those same states can therefore refuse to recognize
the federal government’s exercise of power if they believe it falls outside
what they granted to it in the Constitution. However, with respect to local
governments, they too are creatures established by state governments and thus
cannot nullify state government action; a principal can nullify his agent’s
actions but not vice versa.]

*Second*, jurors can vote to acquit a defendant they believe is guilty of a
“crime” where they believe the “crime” itself is based on unjust legislation,
in the sense that the legislation is not legitimate pursuant to the NAP.

For instance, even if the facts supported the case that the defendant had not
paid his taxes, if a juror believes taxes are an immoral act of robbery by the
state then he could vote to acquit that defendant and no court could question
his decision. The juror would not only be judging the facts but also the
legislation.  footnote:[However, it would not be a libertarian act to acquit a
defendant of murder if the evidence supported his guilt, since murder is a
breach of the NAP and thus legislation outlawing murder is arguably not
contrary to the NAP (although punishment by the state, instead of by the
victim, would be contrary to libertarian philosophy).]

This can be a powerful act of defiance against not just federal government but
also state and local government legislation. It is one of the few times in
which private citizens can have a meaningful, peaceful, oppositional impact. It
could even impact the prospective decisions of law enforcement personnel, who
may decide in the face of continual jury nullification of certain victimless
“crimes” to cease trying to enforce or prosecute them (which may lead
legislators to repeal such legislation).

Indeed there is a history of impactful jury nullification in the U.S.: in the
mid-19^th^ century, juries in northern states refused to convict under the
federal Fugitive Slave Act, as an act of opposition to slavery; and in the
early 20^th^ century, juries refused to convict under the Prohibition
legislation.

Today there is a growing libertarian movement to make jurors more aware of the
concept of jury nullification despite the state’s attempts to obfuscate this
principle.

More generally, nullification can be pursued more effectively as a societal
strategy once enough people are educated in libertarian principles. Then each
act of nullification will reinforce each other act and the groundswell of
active opposition will become quite obvious to statists. It then becomes harder
to argue there is acquiescence to the state.

*_Support Non-State Alternative Products._* There are situations in which the
state has not yet fully prohibited citizens from using non-state alternatives
to products that are provided, privileged and/or regulated by the state.
Libertarians should try to use these alternative products where possible and
encourage others to do the same.

Examples of this include using: private mediation and arbitration services
instead of the state’s courts; private schools, home schooling and online
courses instead of state-provided schools; private residential communities with
their own roads, security, services, etc. instead of public towns and villages;
private mail services such as FedEx instead of the state’s mail service; new
transportation services such as Uber and new accommodation services such as
AirBnB instead of state-regulated taxi services and hotels, respectively; and
alternative currencies such as Bitcoin, gold or silver instead of state-printed
money.

Some of these are more expensive options, since through taxes one is forced to
pay for the state alternative even if one chooses additionally to pay for the
non-state alternative. However, to the extent the libertarian can afford to
choose these options, it will enhance the private sector’s ability to compete
with the state and withdraw some legitimacy from the state’s claims that it
must be a provider or regulator of these products.

Using these options could be regarded as a “partial secession” from the
authority of the state.

*_Advocate for Secession._* Full-blown secession on the political level is the
act of one political entity declaring its independence from another political
entity. When an entity formerly governed by another secedes, politically it
moves from being a subservient entity to an entity with equivalent status,
i.e., a peer. In this way the power of coercion is removed from that
relationship and the two entities now must deal with each other in a state of
political anarchy, i.e., on a purely voluntary basis. This can be one of the
most dramatic yet peaceful ways for people in a given region to avoid the power
of a state.  footnote:[The violent form would be armed revolution.]

Indeed there is an elegance to secession as a solution to escaping an overlord
entity. While land is fixed, jurisdictional boundaries are not. Secession
doesn’t involve moving the land, the citizen or the overlord, but rather simply
the boundaries of the prior overlord’s rule.

Secession also initiates a logic train that can lead to the dismemberment of
political authority. If one region secedes from a larger entity, that larger
entity could not reasonably object when a second region seeks to secede, and a
third region, etc. Similarly, if a region B secedes from a larger entity A,
then region B could not reasonably object when a smaller region C seeks to
secede from region B; if that happened, nor could region C reasonably object
when a still smaller region D seeks to secede from region C; and if that also
happened, nor could region D reasonably object when a household seeks to
secede.

Accordingly, states have always vigorously fought secession attempts at any
level because they understand where the logic train may lead.

Within the U.S. secession has excellent historical and constitutional
underpinnings.  footnote:[A very good source on this topic is a book edited by
David Gordon, _Secession, State & Liberty_.]

As a matter of history, in 1776 the original 13 American colonies seceded from
Great Britain, and in 1781 these independent states formed a union under the
Articles of Confederation. However, in 1788 a subset of these states seceded
from this union to establish a new union under the United States Constitution
(subsequently all existing states joined this new union). Then, in 1861 a
subset of these states seceded from the United States of America to form the
Confederate States of America under a separate constitution.  footnote:[In
addition to these actual acts of secession, at various times in the 19^th^
century some of the northern states in the U.S., principally the New England
states, seriously contemplated seceding over various matters such as the
federal government’s assumption of the debts of the states, slavery, the
Louisiana Purchase, and the War of 1812 against the British.]

There were also secession events at the state level: Kentucky seceded from
Virginia, Tennessee from North Carolina and Maine from Massachusetts.
footnote:[It is also worth noting that secession has not just been a feature of
U.S. history but has occurred numerous times in European history too: Norway
seceded from Sweden; Belgium seceded from The Netherlands; the Soviet Union
broke apar into 15 separate states; Yugoslavia broke apart into seven separate
states; and Czechoslovakia broke apart into two separate states.]

Turning to the constitutional perspective, it was the colonies – organized as
states – that set up the federal government under the Constitution as their
agent to carry out specific tasks. Just as with any principal/agent
relationship, the principal (the states) can always fire the agent (the federal
government) and withdraw from the relationship. Statists often claim that the
American “Civil War” settled once and for all the question of whether there is
a right to secede, but that is a specious argument because the outcome was
based solely on violence. As libertarian historian Tom Woods likes to note, if
a bully on the playground mugs another child and takes his lunch, would anyone
seriously conclude that the bully’s right to that lunch is settled once and for
all? Sure, he has the lunch now, but he got it illegitimately.

However, the right to secede doesn’t rest just on historical precedent and
constitutional principles. There are strong moral and logical grounds too.

In terms of the moral grounds, if every man is regarded as born equal in the
sense that no man can rule another without his consent, then every man must be
able to secede from any political authority once he withdraws his consent,
since that authority just comprises a group of other men.

In addition, since a state always “acquires” its property through coercion –
such as through war, seizing private property owned by citizens, or claiming
unowned property using income confiscated from citizens – none of its property
is legitimately held. Likewise, its control over citizens within its declared
borders is based on coercion.  Accordingly, the individuals at the state have
no moral grounds to object if citizens want to break away from the state’s
control and assert their right to reclaim or homestead “state property.”

In terms of logic, to reject secession means to assert that a particular
political entity, such as a nation-state, is the precise, God-given size that
it needs to be and it absolutely cannot be one inch smaller! Of course this
makes no logical sense.  footnote:[Amusingly, those who reject secession ‒
which makes a state smaller ‒ don’t ever seem troubled by expansion of a state
through war, land purchases, treaties, colonization, etc.]

Secession is a very attractive concept to libertarians because it reduces the
size of states. For the libertarian, “small is beautiful” when it comes to
states (or, rather, small is the least ugly form).

The smaller the state, the less militarily powerful it is likely to be – in the
sense that there are fewer human and other resources within its territory to
commandeer – and thus the less able it will be to wage war on other states or
act provocatively around the globe. This means it is less likely that its
citizens will suffer all the terrible consequences of war. We can see this
principle in operation today, whereby there are many small, relatively
prosperous states which don’t seek to exert any global power and are left alone
by the larger states, even though it would be relatively easy for the larger
states to attack and defeat them. Examples include Andorra, Costa Rica (which
has no armed forces at all), Liechtenstein (ditto), Luxembourg, Monaco and
Singapore.  footnote:[One exception would be Israel, but that small state
receives an enormous amount of military-focused aid from the U.S.]

Moreover, the smaller the state, the more intimate are the personal
relationships between citizens and those at the state, and thus the individuals
at the state can get away with less, e.g., you can see your mayor at the local
diner and complain to him that the garbage is not getting picked up on time,
but it’s a lot harder to have this conversation with your state governor or the
president. In addition, each individual is more significant in a smaller state
than in a larger state, and thus there is less likely to be an emphasis by
elected officials on mass marketing or sloganeering and more attention paid to
individuals’ concerns.

Further, to the extent that there can be any commonality of interest among a
group of people – whether in terms of culture, language, religion or economics
– it is much more likely within a small village than within a county, state or
country, e.g., the views on immigration in a small Texan village on the Mexican
border are likely to be more homogeneous than the views of everyone in the U.S.
Thus it is more likely that a smaller state’s actions will better reflect any
common interests of its citizens than those of a larger state where the
interests are much more diverse.

In addition, smaller states are at greater risk than larger states of losing
their citizens to competing, neighboring states. The smaller the state, the
less costly it is for a citizen to move to a neighboring state in terms of
distance from his family, employment, preferred culture, preferred climate,
etc.  footnote:[Obviously this is less of a concern for a state if other states
erect immigration barriers. However, a state that is looking to persuade
individuals to move from a neighboring state is likely to reduce or eliminate
such barriers. A number of states today offer relatively easy citizenship
programs for certain attractive types of individuals (particularly those
looking to invest, or with needed skills).] Smaller states are also more
sensitive than larger states to losing their citizens. With fewer resources to
begin with, smaller states will feel the loss of any citizens and their capital
more acutely than larger states. Thus smaller states must be much more careful
than larger states about overreaching in terms of their coercive actions
against citizens. In addition to curtailing their coercive activities
domestically, smaller states are also likely to prefer open, free trade across
borders (both in terms of capital and goods), since the smaller the state, the
less self-sufficient it can be and hence the more important imported capital
and goods will be to the well-being of its population.

Accordingly, to the libertarian a world with an increasing number of smaller
and smaller states is a very positive trend. Thus libertarians should be in
favor of every secession movement, of which there is an increasing number these
days.  footnote:[Libertarians should even favor secession if the seceding state
is initially likely to be more statist than the state from which it is
seceding. The decentralization of power and weakening of both states are likely
to have more important long-run impacts than any temporary increase in statist
intensity at the seceding state.] As the idea of secession gains currency it is
entirely possible that small, libertarian communities will be able to break
away and live on a purely voluntary basis.

*_Engage in Low Level Civil Resistance._* As large as the modern state is, it
has simply passed too many regulations for it to effectively enforce them all
against everyone. Much to their chagrin – but proving that scarcity is a fact,
even for the state – the individuals at the state run up against the constraint
that they have limited time and resources, and have to allocate how they use
them to selectively enforce regulations. This creates the opportunity for
libertarians to simply ignore (and ridicule) the state’s regulations when they
are not aligned with the NAP. If this type of civil resistance grows over time,
it is possible that in certain areas the state may have to re-think whether its
regulations make sense given the obvious erosion of the public’s acquiescence
which is necessary to sustain the state.

Obviously the degree of enforcement risk one is comfortable taking is up to the
individual, but there are many lower risk ways to ignore the state’s unjust
rules: when practicable, transact using physical cash, Bitcoin, gold, etc.  to
ensure transactions remain untrackable by the state; when turning 18 years of
age, refuse to register with the Selective Service System to avoid providing
information helpful to the state if it decides to use military conscription to
fight its wars; employ and/or provide sanctuary for illegal immigrants; if
desired, consume alcohol and narcotics even if prohibited by legislation;
ignore occupational licensing regulations when running a small business; refuse
to recycle as commanded by the state; when appropriate, ignore speed limit
legislation; refuse to obtain the state’s zoning approval when making small
improvements to one’s property (such as patios, storage sheds, etc.); and
support businesses which are obviously ignoring the most ridiculous state
regulations.

It’s worth noting that a casual survey of society will show that many statists
routinely act in these ways and, what is most amusing and revealing, this
includes many individuals who work for the state itself. Often times the retort
from statists who are caught in the act is “But I wasn’t hurting anyone!”

Exactly.

Perhaps it is innate in all humans to judge rules by the standard of the NAP,
even if not everyone can articulate this as clearly as libertarians can.
