== Myth #17: We’d Be Defenseless!

The last thing a statist will ever concede on is that defense against external
aggression does not have to be provided by the state. The statist just knows
that this is the “public good” par excellence.

To the contrary, earlier in this paper I showed why the so-called “public good”
argument in favor of state-provided national defense is not compelling. There
is nothing distinctive about any good, even national defense, that can ever
justify being supplied coercively by a monopoly.

So how might this work in a libertarian society?

=== A Stateless World Would Have Less Conflict

In a stateless world there would likely be much less need for collective
defense capabilities against external aggression.

Much of today’s international conflict arises because one state acts
aggressively towards another, either attacking that state or provoking an
attack by seeking to interfere in the other state’s operations. States can do
this because the individuals at the state responsible for this aggression do
not do any of the fighting themselves and can coercively seize their citizens’
income to pay for this aggression.

In a stateless world very few men would travel to foreign territories at their
own cost to physically fight strangers to try to conquer their territory, or
stay there to try to influence their society.  footnote:[This raises the
question of the volunteer soldier, who does agree to travel overseas to kill
others at personal risk to himself.  This is likely a function of the statist
education system, which indoctrinates citizens from a very young age to believe
that killing foreigners in the name of the state is honorable when directed by
the individuals at the state, even in the absence of a genuine “defense of the
homeland” concern (either that or the volunteer soldier is simply a sociopath).
In a stateless society there would be no state to revere and no
state-controlled education, so such indoctrination wouldn’t exist (sociopaths
would still exist, but few citizens would voluntarily pay for them to go on
killing sprees overseas, unlike now where we are forced to pay for these gross
adventures through taxation).] Likewise, few men would be able to afford or
want to spend the billions of dollars spent today to hire other men to travel
overseas to seize territory or influence another society.

Another source of conflict today is individuals at the state oppressing
subsections of their own population based on race, religion, ethnicity, etc.
And sometimes internal oppression by state A also leads to inter-state war, as
another state, state B, attacks state A to try to stop this internal
oppression. Again, the individuals leading state A can engage in this
oppression at minimal personal cost because they have others doing the fighting
and coercively funding these activities (so too with the individuals leading
state B in attacking state A).

Imagine if these men had to engage in the oppression themselves either
physically or financially; there would be a lot less of it.

This type of oppression is partly facilitated by the state disarming its
citizens through gun control legislation. The most oppressive regimes in
history have always moved quite early on to prohibit the private ownership of
firearms, often justified as necessary to reduce violent crime. Quite
coincidentally, however, if only the state is armed the group targeted for
oppression is defenseless.

In a libertarian world, where there would be no restrictions on firearm
ownership, it would be much harder for one group to oppress another, since the
target group could be fully armed too.

This would also be a reason to expect less inter-societal conflict. If a man
wanted to hire a group of aggressors to travel overseas and seize territory,
they would face an armed population fighting to defend their own families and
property, which history has shown is the most difficult force to defeat, e.g. ,
in ancient times the Greek cities holding off the Persian Empire, the Viet Cong
vs. the U.S. in the 1960s, and the Afghanis vs. the Soviet Union in the late
1970s.

The other reason for conflict in today’s world is that it is relatively easy to
control vast amounts of territory simply by being the victor in a state versus
state war. Since states, through their infrastructure, control all of their
territory internally, once an aggressor state defeats another state and assumes
control of the defeated state’s infrastructure, it automatically comes to
control the defeated state’s territory and population. In other words, if power
is centralized, as it is in a state, then one only has to seize control of the
locus of power, not of the entire state territory itself.

In a stateless world, however, there would be no central power or
infrastructure to seize control of. In a sense the aggressor would have to
defeat every single household to control each household’s territory. That is
almost an impossible task that would surely stretch an aggressor’s resources
intolerably, particularly given that, after seizing each house, the aggressor
would also have to hold it indefinitely. History has shown that the most
difficult part of battle is seizing and holding more and more ground,
stretching supply lines.

The final point to make relates to the importance of free trade. States often
erect prohibitions or restrictions on individuals in one state trading with
individuals in another state through the imposition of sanctions, tariffs,
quotas, exchange controls, regulatory distortions, etc. These trade barriers
make war less costly; if individuals in state A already cannot fully and freely
trade with individuals in state B then the cost of state A going to war with
state B is lower, since there is no (or less) commercial trade that would
suffer.

In a stateless world, however, there would be no trade barriers. Everyone would
be free to trade with everyone else. This effectively increases the cost to any
society of starting a conflict with another society, since such a conflict
would risk damaging or destroying actual or potential customers and/or
suppliers. Put another way, the more free trade that exists the less likely is
war, since it makes no sense to degrade key parts of one’s own economic
ecosystem.

=== Libertarian Defense In A World With States

That is all well and good if there were no states at all, but what if a
libertarian society existed in a world in which there were some states in
existence?

The first point to note is that a few of the above concepts would still be
valid: there would be no aggressive activity by the libertarian society
directed towards states so there would be less provocation sparking conflict;
an aggressor state would face an armed population; and there would be no
central power to seize to declare victory.  In addition, the libertarian
society would be eager to trade with individuals in the existing states and, to
the extent such trade existed, it would increase the cost to those states of
attacking the libertarian society since this society would comprise actual or
potential customers of and/or suppliers to individuals in these states.

However, there is also reason to believe that individuals in a libertarian
society would still demand some defensive protection against external aggressor
states. Where there is demand, production is sure to follow.

Of course the general demand for defensive capabilities would be quite
different in a libertarian society. Since each individual would directly have
to pay out of pocket for these services, as a consumer he would be a lot more
discriminating. There would likely be little to no demand for offensive
capabilities to project force around the world and interfere in other
societies. Demand would likely be for purely defensive and rescue capabilities.
Indeed some consumers may decide that, since their society is no threat to
others, the chances of an invasion are low enough to suggest it would not be
worth purchasing any protection at all.

Instead of a centralized, coercive monopoly provider of protection, different
competitive providers would arise to supply products tailored to consumers’
actual needs, since they must be able to persuade consumers to voluntarily part
with their money.  footnote:[Under statism if you do not like what you are
paying for national defense, or do not agree with the defensive or offensive
policies of the state, your only remedy is to try to move countries (not easy).
In a libertarian society you wouldn’t have to change location: you could stay
and just change provider.]

Perhaps consumers in coastal societies would want to pay for some water-borne
defense services, but those in the middle of a large land mass might not. Those
in difficult to reach mountainous regions might decide to forego purchasing
much in the way of defense services, figuring that the terrain is sufficient
protection against invasion.  Those living in high profile cities which could
be more likely targets might want to pay up for more protection, and those
living in rural areas might want less.  footnote:[This would properly price
consumers’ decisions about where to live. In today’s regime, residents of rural
areas are subsidizing the defensive protection of residents living in high
profile cities, such as New York, since everyone pays for national defense
based on the same income tax scale. If, for instance, New Yorkers had to pay
based on risk profile, fewer people would choose to live there and/or they
would demand that the U.S. reduce its provocative activities around the globe
to reduce the city’s risk profile.] Those who live in high risk target areas
might want to purchase missile defense protection, and if this is too expensive
then they can either move or try to persuade others of their fears and have
them pay for such protection too. Those who travel overseas a lot might want to
purchase highly mobile and skilled bodyguard and/or hostage rescue services,
while those who don’t travel much wouldn’t have any interest in spending their
money on these types of forces.

Just as in any other industry, competition among providers would tend to bring
(or at least hold) down prices and increase innovation and quality. A provider
of defense services that engaged in the type of aggressive activities
undertaken around the globe by the U.S. government today, and which is
constantly involved in violent conflict with states, would find its costs
increasing dramatically, and thus it would have to increase its prices (or cut
its services) to remain profitable. If its customers were not willing to pay
these higher prices, or they disagreed with the service provider’s actions they
would look to competing, less aggressive and thus lower cost providers of
defense services. Likewise, a defense services provider that didn’t deliver
adequate protection would gain a bad reputation and would lose customers to
competitors.

Accordingly, the voluntary nature of customer payments and the presence of
competition would constrain the aggressive activities of defense service
providers and motivate better performance. This is in contrast with today’s
national defense where the payments are compulsory and there is no competition,
and thus there are few constraints on national aggression and few motivations
to be effective.

What if a private protective services provider failed in its duties? Lives are
at stake. Yet this is no different from today with the state. What if the state
failed? In the U.S., see Pearl Harbor, the first attack on the World Trade
Center, 9/11, the Boston Marathon, etc. The difference is that in a libertarian
society such a private provider would go out of business, whereas today the
state just continues to be the monopoly provider (and in fact grows with each
failure to protect!).

=== Collective Defense

It is also likely that individual consumers and businesses would not have to
select each provider for each type of service, nor contract with them or
monitor their activities.

For instance, developers of residential communities and owners of industrial
parks, office buildings, hotels, malls, roads, etc. may purchase and monitor
defense protection for their properties to the benefit of their
residents/tenants/customers. Such owners could build the cost of this
protection into the fees they charge for use of their properties. Indeed, even
these owners may not have to purchase defense protection individually: they
could form associations or federations across a broader region to purchase such
protection as a group.

More likely, it might turn out that it would be much more efficient for life,
health and property insurers to undertake these activities for their
policyholders. Since these are the insurers that would have to pay out if
someone were killed or injured, or their property were damaged by an external
aggressor, these insurers would be motivated to purchase the most efficient
form of protective services for their policyholders to minimize the chances of
having to pay out on claims. Also, since insurers are in the business of
assessing and pricing risk, they would charge different premiums for different
locations based on that location’s risk. This would ensure that those who
choose to live in higher risk locations would pay higher premiums.

Insurers that aggregate millions of policyholders would have the financial
clout to purchase large scale defense protection. Indeed one way to look at
national defense today is that when citizens are forced to pay taxes to fund
this activity they are really paying for compulsory protection insurance from a
monopoly provider; in a libertarian society there would instead be multiple
insurance providers from which to choose, each of which would have multiple
defense services providers from which to choose.

In the insurance world there is also the concept of reinsurance, whereby
insurers themselves take out insurance for a portion of their potential payouts
on claims. The reinsurers aggregate multiple insurers into their client
portfolios, and thus they would be indirectly aggregating the interests of many
millions of underlying policyholders. Accordingly, if there were some
protection services which were too expensive even for some insurers on an
individual basis, the reinsurers would likely be able to afford these types of
services to offer to their insurance company clients.

=== What About The REALLY Expensive Stuff?

How would a libertarian society pay for certain defense products that today are
very expensive to provide, e.g., a defensive nuclear arsenal, a submarine fleet
to guard the coastline, an air force, etc.? There are several responses to
this.

*First*, part of the reason these products are so expensive today is that the
buyer is the state and the seller universe is restricted by state licensing
rules.

The state doesn’t have the same discipline as private buyers to demand that
sellers keep their prices down, because the individuals at the state, who are
not paying with their own dollars, have no financial incentives to do so, and
may even be motivated to overpay if the defense vendors are cronies who can
provide other benefits to the relevant state personnel. In a libertarian
society the buyers would all be private, expending their own dollars, and thus
they would be much more demanding of sellers; sellers would have to compete,
including on price, to accommodate buyers’ preferences.

In addition, the state only permits certain vendors to operate, using excuses
such as “security clearance” to restrict the number of sellers. In a
libertarian society there would be no restriction on the number of sellers,
which would tend to put downward pressure on pricing through the impact of
greater competition.

*Second*, it’s not clear that these types of products would actually be in
demand in a stateless society. It’s not a valid question to ask how in a
libertarian society we could afford the national defense the state provides
today because, as discussed above, in a libertarian society the defense
protection demanded might be very different.

*Third*, as noted above, the operation of insurance and reinsurance may enable
the efficient pooling of expenditure on behalf of millions of policyholders,
which could be directed towards expensive defense products in demand.

*Fourth*, there may be other ways to enable the purchase of the most expensive
defense products. Defense product vendors or the capital markets may provide
financing options to buyers so that payments can be made over time instead of
upfront. Large businesses (or associations of smaller businesses) may figure
that it’s worth voluntarily contributing to the defense bill because if
potential customers were killed or their property destroyed that would be bad
for business. People may make voluntary contributions over and above their
contractual payments just because they believe it is the right thing to do
(like tipping a cab driver or restaurant even though you may never use them
again). Wealthy philanthropists may feel inclined to establish charitable
foundations to contribute. And there may be other options that develop which we
cannot envision right now.
