== What Is Libertarianism?

For mankind to survive and flourish man must use his body to work the earth’s
physical resources to transform these resources into products that satisfy
humans’ needs. However, people and physical resources are scarce relative to
needs and thus conflicts necessarily arise as to the control of these human
bodies and physical resources. In fact it is more basic than that: the only
reason conflicts arise in society is in disputes over who has the right to
control physical property (human bodies or physical objects). This is because
one person’s control of physical property necessarily excludes another’s. For
instance, either I can stand in this physical space or someone else can, but we
both can’t; either I can decide what to put in my body or someone else can
decide for me, but we both can’t; either I can control this widget or someone
else can, but we both can’t.

Given that these disputes will arise and need to be resolved somehow by
society, political philosophy is essentially the search for a set of principles
to determine who has the better right to the physical property in question.
These principles are known as “property rights.” Different political
philosophies appear to have different property right regimes.
footnote:[Consistent with this analysis, libertarians don’t recognize property
rights in intangibles such as information or ideas because there cannot be a
conflict over their use; my use of an idea doesn’t preclude your use. Statists
claim that if A uses B’s original idea then A has deprived B of the “value” he
has created with that idea. However, B cannot have a right to any particular
“value” since this only comes from customers voluntarily paying B for his
products, and B cannot have a right to his potential customers’ wallets! What
if B’s products were simply shoddy and no one bought them? What if A didn’t use
B’s idea but nevertheless competed successfully against B and lured away B’s
former customers? B has no right to his customers’ money and therefore no right
to any particular “value” for his ideas, products or business.]

To the socialist, conceptually “the people” (as one mass) own all physical
property. However, when it comes to actually making decisions about what can be
done with this property, a much smaller group gets to make these decisions ‒
the ruling elite ‒ and thus in fact the ruling elite exercises all the powers
normally attached to ownership. The rest of the people are forcibly prohibited
from challenging the ruling elite’s decisions.

To the theocrat, conceptually the deity owns all physical property. However,
when it comes to actually making decisions about what can be done with this
property, a much smaller group gets to interpret the deity’s desires ‒ the
priesthood ‒ and thus in fact the priesthood exercises all the powers normally
attached to ownership. The rest of the people are forcibly prohibited from
challenging the priesthood’s decisions.

To the democrat, conceptually individuals can own their own bodies and other
physical property. However, when it comes to actually making decisions about
what can be done with bodies and other physical property, a much smaller group
gets to make these decisions – the elected class and their appointed agents,
through legislation – and thus in fact the elected class exercises all the
powers normally attached to ownership. The rest of the people are forcibly
prohibited from challenging the elected class's decisions.  footnote:[Note that
today’s democracies are technically economically fascist. Under economic
fascism, private ownership is recognized but the state uses such a heavy
regulatory hand that in essence the state controls the use of all factors of
production, even if it does not technically claim ownership over them (this
differs from socialism only in that, under socialism, the state actually claims
ownership of all factors of production).]

If the description of democracy sounds like a duplication of the descriptions
of how socialism and theocracy work, that’s because they are! In a democracy
the political class ‒ meaning the combined executive, legislature, judiciary
and bureaucracy ‒ can tell a person what he can or must do with his body (i.e.,
to where he may travel, what he can put in his body, what work or leisure
activities he can do with his body, with whom he must work or otherwise
associate, what he can say, what he can read, who he has to kill, etc.), and
what he can do with his property ( i.e. , what he can keep from what he earns,
what he can buy and at what price, how he can use what he is allowed to keep or
buy, to whom he can sell it and at what price, etc.). The only difference
between socialism, theocracy and democracy in terms of political philosophy is
how the rulers are chosen. In socialism and modern theocracies it has most
often been through explicit violence; in the case of democracy it has been
through a subset of the population voting. The voting process in a democracy
doesn’t change the fact that no one who objects to the rulers’ decisions may
opt-out and do with his body and property as he pleases.

The libertarian property rights regime, however, is quite different from every
other political philosophy. It is this: no person may initiate aggression or
the threat thereof against another’s body or legitimate property (known as the
“non-aggression principle” or “NAP”).

Consistent with the NAP, legitimate title to non-human property can be acquired
only in one of three ways: by a person physically working previously unowned
property so as to objectively evidence direct control (“homesteading”); through
a voluntary transfer agreement entered into by one person with another who
legitimately owns the property (“contracting”); or by one person seizing the
legitimately owned property of another who has initiated a violent act against
the first person (“restitution”).  footnote:[I am assuming it is not necessary
to discuss why a person should be the sole decision-maker with respect to his
body, but there is significant libertarian work on even this point
(“self-ownership”).] In none of these ways does any person initiate aggression
or the threat thereof to acquire the property: in the case of homesteading, no
one yet owns the property so there is no one from whom to take it with
aggression; in the case of contracting, the current owner is voluntarily
agreeing to transfer ownership; and in the case of restitution, the current
owner, through his initial commission of a violent act, is estopped from
objecting to the seizure on the grounds that he who initiates aggression cannot
then complain about aggression being directed back at him by the victim.

While the contracting and restitution principles probably don’t require much
more explanation, the homesteading principle might.  footnote:[This is not to
suggest that there are no nuances with respect to contracting and restitution.
Matters such as what is a valid contract and what evidence can be adduced as
proof, and what is proportional restitution, would all need to be worked out by
a libertarian justice system, just as is the case in a statist “justice”
system.]

The first thing to note about the homesteading principle is that it is based on
the idea that everyone has the best claim to his own body.

If a person has the best claim to his own body then he must surely have the
best claim to anything his body physically produces legitimately (leaving aside
any voluntary agreement that he enters into to the contrary). Thus if a person
works previously unowned property then he must have the best claim to the
produce of that work. It would be very hard to argue that someone else has a
better claim to this produce, for this would imply that this other person
somehow has a superior right to the efforts of the first person’s body. If
every man has a superior right to the efforts of every other man’s body there
is the problem of circularity – A controls B’s body and yet B controls A’s body
– and it would mean that no man could ever act without everyone else’s consent,
which would be impossible to obtain. Mankind could not survive.

The second thing to note about the homesteading principle is that it
invalidates the notion that individuals at the state can claim previously
unowned property as “public property.”

A mere verbal claim of ownership is insufficient; the person claiming to have
homesteaded property must have applied effort to the property and made it
obvious to others that he has done so, e.g., by constructing a fence around
virgin land or by putting apples picked in the wild into a basket, etc. A mere
verbal claim fails to meet the previously mentioned objective of establishing a
property rights regime which minimizes conflict. If all that were required is a
verbal claim, then everyone could allege they made the first verbal claim and
they could allege their claim related to all unowned property on the face of
the earth. That would increase conflict, not minimize it.

In addition, when homesteading property the person must not have used
illegitimate means or illegitimately acquired property, for then all the things
that he does through such means or with such property would be tainted with
this illegitimacy. Thus if the state were to use forced labor (e.g., prisoners,
conscripted draftees, etc.) to apply effort to and delineate borders around
some unowned property, or to use taxes to purchase the requisite labor services
and bordering materials, this would not qualify as homesteading because the
labor and/or taxes were coercively obtained.

The third thing to understand about homesteading is to consider the
practicalities of what it would mean to reject this principle. If the first
person to work some unowned property is not regarded as the permanent owner
(assuming he doesn’t voluntarily transfer it to someone else or have it seized
in a restitution procedure), who should be? There are only three other
possibilities.

*First*, everyone in the world owns such property in common and thus everyone’s
consent would be required before anything can be done with it. However, in this
case how could any decisions ever be made about what to do with this property?
It would effectively be rendered useless. Mankind would cease to exist if no
decisions could be made about how to use property.

*Second*, the property remains unowned despite the act of homesteading, i.e., no
one can ever own property. If this were the case, the effect would be that
either all property would be rendered useless or there would be perpetual
conflict over property that could never be peacefully resolved.

*Third*, some other person who later acts on the property is to be regarded as
the owner (a “latecomer”). However, if this were the case, ownership would only
ever be temporary. A person who owns some property at any point in time would
have to live with the perpetual fear that a latecomer might come along and
seize the property (and it would be a vexing question to answer as to how a
latecomer could legitimately “seize” the property from the current owner). This
would reduce the current owner’s incentives to apply more resources to the
property (i.e., to invest in improving it) as he would be liable to lose
control over it at any time, and it would truly be survival of the strongest.
Imagine the state of an apartment which has no permanent landlord and is liable
to be taken over by a new tenant at any time. Mankind certainly wouldn’t
flourish anywhere near its maximum potential if everyone viewed property in
this way.  footnote:[Indeed this is how the modern state operates. Citizens can
only keep and use their property until such time as the more powerful state
personnel take away all or some of the benefits of ownership, which they do
through taxation, eminent domain seizure and regulation. Similarly, citizens
can only do with their bodies those things which state personnel don’t restrict
through regulation.]

There is not much more to libertarianism than the above principles, but the
libertarian insists that they be applied consistently to every single human
being, on the grounds that all men are born equal.

Thus, based on the NAP, the libertarian rejects the notions that: (a) someone
can force another person to do with his body as the first person requires,
which is what the individuals at the state do when they regulate people’s
actions and when they use conscription to send them into battle; (b) someone
can take or control another person’s existing property without his contractual
agreement or a proper restitution procedure, which is what the individuals at
the state do when they tax or seize property from individuals or regulate its
usage; and (c) the individuals at the state can legitimately claim ownership of
previously unowned land, water, air and natural resources lying beneath the
surface, since these are claims made over unowned property using other
resources which were illegitimately acquired.  footnote:[The corollary to these
principles is that the state cannot even legitimately own property that the
current owner voluntarily agrees to sell to the state, since the state is using
illegitimately acquired resources (tax funds) to purchase this property.]

To anticipate a statist objection, when the libertarian states that people
should be able to use their body and property as they see fit this does not
mean that they can use them to initiate murder, rape, kidnap or assault, or
theft or destruction of another’s property. Those actions would themselves be a
breach of the NAP and thus would be illegitimate in a libertarian society.
However, the corollary to this is that those at the state can also not initiate
these actions, which therefore rules out taxation, regulation, conscription,
involuntary incarceration, etc.

To anticipate another statist objection, the NAP only proscribes the initiation
of aggressive actions but does not proscribe responding with such actions in
appropriate circumstances. Thus A may legitimately use force against B in
self-defense provided B initiated the violence, and C may legitimately take D’s
property as restitution or retribution for D having initiated aggression
against C or his property footnote:[Obviously lots of questions arise as to
when someone “initiates” violence and what punishment and compensation theories
are valid (deterrence, rehabilitation, restitution, retribution, etc.).
However, these are questions any system has to work out over time and are not
unique to libertarianism, although there is significant scholarly libertarian
work on these issues.] The libertarian objection to traditional actions of
those individuals at the state is that, through taxation and regulation, they
initiate the taking of the property and/or the incarceration of others when
these others have not themselves breached the NAP.

Libertarianism then is simply a philosophy about when actual or threatened
violence is acceptable. However, libertarians recognize actual or threatened
violence in all aspects of society rather than giving a “pass” to those at the
state, i.e., libertarianism is a universal standard, not a selective one. But,
beyond this, libertarianism does not prescribe any particular behavioral norms
for mankind. Those norms are left to be defined by one’s culture, ethnicity,
local customs, family traditions, religion, trade, education, etc. Thus the NAP
is a minimum, not a comprehensive, behavioral standard.

Put another way, libertarianism is a philosophy which minimizes aggression
while maximizing personal freedom.  What’s not to like about that?
