== Governing By Principle, Not Arbitrarily

Why do we need an overarching principle to govern society? The answer is that,
if we don’t govern by principle, then by definition we are governing
arbitrarily.  footnote:[Note that the libertarian has no objection to any
individual living his own life using arbitrary rather than consistently
principled guidelines. It is only when such an individual tries to forcibly
impose his arbitrary guidelines on others that the objection arises.]

Statism has no universal principle that defines when coercion is justified and
how to resolve conflicts. Under statism the rules which govern society are
based solely on who is in power at any one point in time and the whims of that
ruling elite. Even under a modern democracy statists pledge fealty either to
process (electoral and legislative) or a personality, or both, but not to a
principle. How is this different from a monarchy or a dictatorship? Because
arbitrary rulings are sometimes issued by a group instead of by a single
person?

Since state-imposed legislation is such a central part of statism, one should
put to a statist the following question: By what standard should legislation be
judged as good law, in the sense of being just? The statist is likely to give a
blank stare in response, or may respond that provided it is duly passed by a
duly elected legislature, and not overturned by a court, the legislation is
good law. However, as regards the latter response, statists’ own actions
demonstrate that they don’t really believe this; many statists have
historically protested certain pieces of legislation as unjust, or ignored such
legislation, such as the Fugitive Slave Act, “Jim Crow” legislation,
legislation explicitly or implicitly prohibiting universal suffrage or
homosexual relations or marriage, military conscription legislation,
legislation prohibiting the consumption of alcohol or narcotics, legislation
setting vehicular speed limits, legislation prohibiting or restricting home
businesses, etc. Thus these statists are actually judging legislation by a
higher standard than mere legislative process. Yet if you press statists to
articulate that standard, they will likely be unable to do so, thereby
confirming the arbitrary nature of statism. Not so libertarians; to them, the
only just law is one that outlaws the initiation or the threat of force against
peaceful individuals.

To make this point differently, “partial” statism is internally inconsistent.
Most statists believe in the state for some tasks and not for others. Yet they
can point to no consistent, cogent, logical principle which allows one to
distinguish between the two sets of tasks. If coercive central planning is
superior in one area it should be superior in all areas; if coercive central
planning is unacceptable in one area it should be unacceptable in all areas.

Accordingly, to be logically consistent one either needs to be a libertarian or
a philosophical communist. Anything else in between is unprincipled.
foonote:[The inconsistency of statists manifests itself most obviously in the
area of U.S. foreign policy. Anti-war statists on the political left believe
the U.S. government should not dictate to foreign nations how they should
organize themselves, yet these same statists believe that the U.S.  government
should dictate to its own citizens how they must live their lives.  Pro-war
statists on the political right believe the U.S. government is not competent to
organize domestic society, but that it is highly competent to organize wars
against and the restructuring of foreign nations.]

The worst implication of the arbitrariness of statism is that it can only lead
to more conflict. If the rules of society are defined only by who is in power,
then society disintegrates into what libertarian historian Tom Woods has called
a “low intensity civil war.” Every interest group competes aggressively to
exercise or rent the state’s power, since on any issue there can only be one
winner (to use the example given previously, we all either have to drink Coke
or Pepsi). This is what causes, and has always caused, political conflict
between different groups: blacks and whites, urban and rural residents, women
and men, political left and right, domestic and foreign parties, unions and
corporations, environmentalists and industry, the wealthy and the less
well-off, police and civilians, etc.

Why should we live like this? We’re only harming ourselves.

* * * * *

To return to the original question – Why does it matter? – it matters because
we should all want the most peaceful society we can attain. To attain a more
peaceful society, you need to start with a peaceful governing principle.

