== Minimizing Conflict Within Society

Ultimately, political philosophy is about searching for the most just way to
govern society. That seems to be a worthy end. As noted earlier in this paper,
all conflicts in society are conflicts over scarce resources, whether human
bodies or physical objects. We should all be interested in defining some
acceptable, peaceful standard to govern human behavior with respect to such
conflicts.

If we want to live in a society that rejects force, minimizes conflict, and has
a principled way to try to non-violently resolve conflicts that do arise, we
ought to advocate a political philosophy that is consistent with those ends.

Statism relies on the initiation or threat of force by the individuals at the
state, and is characterized by a vigorous competition among citizens to rent
the state’s coercive powers to forcibly take things from fellow citizens. It is
therefore a political philosophy based on force and designed to create
conflict.

Only libertarianism, with its sole focus on the non-initiation of force, can
meet the above test. Libertarians define this peaceful principle and then
demand that it be the standard to which every single person be held to account
in everything he does.

In addition, as noted earlier, because libertarianism is based on a “negative
rights” principle, it can, as a technical matter, be enjoyed by everyone in
society concurrently. This makes it a highly scalable political philosophy.

In other words, not only is libertarianism the only peaceful political
philosophy, it is the only political philosophy that can be universally
applied.
