== Opposing War

Libertarians are not just in favor of this peaceful principle domestically.
Libertarians also believe that no one should initiate aggression against people
who live in different geographies just because they are engaging in activities
we don’t like (provided they are not imminently threatening us).

Yet this is what the state does, habitually.  footnote:[Recall that the main
reason the state arose historically was to facilitate the financing of the
monarch’s wars against other monarchs.]

Why do libertarians oppose initiating or provoking war?

Initiating or provoking war means: (a) sending citizens to their death overseas
and/or to kill others who pose no imminent threat, and provoking retaliation in
the homeland against citizens (blowback); (b) through taxation and “defense”
spending, forcibly diverting scarce resources ‒ which could otherwise be used
to produce goods to satisfy consumers’ actual wants ‒ to produce things the
only purpose of which is death and destruction, and then using these things to
destroy other scarce resources; and (c) reducing citizens’ liberties to speak,
travel, earn income, move assets, etc., based on the fiction that this
reduction in liberties is needed to safeguard the population from blowback.

It’s worth emphasizing two critical points about war.

*First*, when an individual in society wrongfully kills multiple victims,
statists are rightly shocked and correctly label this “mass murder.” Yet when
individuals at the state initiate lethal combat operations against people
overseas who are not imminently threatening the state’s citizens, this is mass
murder on a much larger scale, but statists are not troubled by this activity
so long as it is labeled “war.” Yet, logically, changing the label applied to
an action cannot change its moral status.

*Second*, with every state-manufactured conflict the state argues that it needs
more powers for defense. Yet the vast majority of the time this is a
disingenuous argument, because either it was the state’s prior activities which
initiated or provoked the danger, or no defense is called for because there is
no actual danger. As Randolph Bourne once wrote, “[W]ar is the health of the
state.” It is very easy for the state and its beneficiaries to expand their
power dramatically amid alleged conflict, since at these times the state can
whip up fervor through appeals to patriotism and “defending the homeland.” When
the alleged conflict is over – if the state ever admits this, which is
exceedingly rare – the state never yields, never reduces its powers back to
pre-conflict levels. This “ratchet” effect is defended by the argument that the
state needs to remain “vigilant” against the alleged enemies, or new potential
enemies.  footnote:[Americans have been told by the state that they have
been in a perpetual state of war over the 20^th^ and 21^st^ centuries, during which
time there has been an increasing erosion of liberties. This has resulted
cumulatively from the unnecessary entry by the U.S. into World Wars I and II,
its unnecessary provocation of and participation in the “Cold War” and its
resulting conflicts (in Korea and Vietnam), the “War on Drugs” (really a war on
the state’s own citizens voluntarily ingesting substances, so it can never
actually be over), and the “War on Terror” (really a war on a strategy, so
likewise it can never actually be over).  The liberty-destroying PATRIOT Act
was passed urgently following the September 11, 2001 terrorist attacks – which
were themselves likely blowback from aggressive U.S. military activities in the
Middle East – allegedly to prevent the next such attack, but the legislation
has never been repealed, even 15+ years later, apparently because of the
permanent need for “vigilance” (no doubt due to the permanent U.S. military
activities in the Middle East). Unsurprisingly, as part of the “War on Drugs”
the domestic police now aggressively use against U.S. citizens (a) the powers
grabbed under the PATRIOT Act and (b) the surplus military equipment made
available from the “War on Terror.” And so on it goes.]
