== Economics

Not surprisingly, the statist subscribes to the Keynesian school of economics.
This is not only because this is all that is taught to most students who take
economics courses, but also because it gives a very prominent role to the
state.

Keynesianism assumes that the economy is a machine, the various economic actors
(firms and consumers) are simply cogs in that machine, and the individuals at
the state sit poised at the levers to make sure the machine is humming along at
the “right” speed, making adjustments as disturbances in the economy occur.
footnote:[Although Keynesianism cannot really explain what causes economic
downturns; they are just assumed to occur naturally.]

Fundamentally, Keynesianism is based on the belief that consumer spending
creates wealth. Thus the Keynesian solution to depressed economic times is to
encourage more consumption spending, and the statist believes that those at the
state have the omniscience and natural right to determine when and how money
should be spent in the economy.

This is demonstrably wrong on so many counts that an entire paper could be
written on this topic alone. I will make two quick observations here.

*First*, this concept reverses reality. People don’t become wealthy because they
consume, rather, they consume once they become wealthy.

*Second*, the creation of societal wealth comes from two factors, both of which
must be present: (a) the division of labor into specialties, where people do
what they are comparatively best at; and (b) savings being channeled into
investments in productivity-enhancing new technologies, processes and capital
equipment.

We need to consume to live, but we need to specialize, save and invest to grow
prosperity.

Yet Keynesianism discourages savings in favor of consumption. This is because
it doesn’t recognize that the capital and freed up real resources to make the
above investments can only come from individuals deferring consumption by
saving some of their income. Savings become investment through business
operations and the capital markets, and simultaneously release real scarce
resources (natural resources, labor and capital equipment) from having to serve
consumption ends so as to be available to serve investment ends. While
Keynesians will criticize the wealthy because they don’t consume as large a
proportion of their income as the less well-off, it is this deferral of
consumption by the wealthy that makes capital available for investments to make
the least productive workers more productive, and thus enhances their ability
to earn higher real wages.

Keynesians also believe that if more money is pumped into the economy – money
newly created by or with the backing of the central bank – then this will
create economic activity and thus prosperity. However, to survive and flourish
humans cannot consume money; they can only consume real goods. To create those
real goods, what matters is the amount of real resources available and where
they end up. The amount or velocity of money in circulation cannot increase the
amount of real resources; rather, money is just a means to enable exchange of
real resources.

Indeed, if increasing the amount of money in circulation were the means to
attain prosperity, why would there be any poor countries in the world? Their
central banks could just print up endless amounts of money!

Statists also believe that the laws of economics, which explain how humans act
in their individual dealings with one another, do not necessarily apply when
the state sets economic policy. This is because Keynesianism sees “the economy”
as a creature distinct from the individuals composing it, one which has its own
properties and can act separately (as commanded by its masters at the state).
The reality, of course, is that “the economy” is nothing more than the
aggregation of all individuals transacting with one another. We can appreciate
this through a thought experiment. Imagine taking each person out of “the
economy,” one at a time; when you extract that last person, would there still
be a thing called “the economy” remaining?

So, while the law of demand is well accepted by statists – that, all else being
equal, a lower quantity of a good will be demanded by an individual purchaser
at a higher price – apparently this does not apply when the state sets a higher
minimum wage than businesses are currently paying for their lowest skilled
workers. Statists claim that there will be no unemployment impact in the
economy, i.e., that businesses will not lower their demand for this productive
input (which would make labor a unique input!).

Similarly, while statists accept that it is beneficial for individual consumers
to pay lower prices for goods, when the state desires price inflation – which
is nothing more than a hidden tax used to pay for its various programs – we are
told that economy-wide price deflation is a nightmare and that, as a country,
we must subscribe to “inflation targets.”

Or, while statists accept that an individual can maximize his prosperity by not
being self-sufficient, meaning that it is highly beneficial for an individual
to freely trade with others, producing what he is best at and exchanging this
for goods others are best at producing, apparently this benefit evaporates when
the individuals on the other side of such exchanges are residents of a separate
state. Statists believe that it can make economic sense for the state to
restrict citizens’ ability to trade with foreigners, because statists take an
“our economy versus their economy” approach (never mind that national borders
are artificially drawn up by the individuals at the state in the first place).

As one last example, while statists accept that individuals should not borrow
to live beyond their means nor invest borrowed money in destructive endeavors,
apparently it makes sense for the state to borrow beyond its means of repayment
and to invest the borrowed money in destructive endeavors such as war, spying
on its citizenry and aggressive enforcement of victimless crimes.
footnote:[There are many other similar observations to make about statist
economics, but that is beyond the scope of this paper. I will briefly contrast
statist economics with free market (“Austrian”) economics later in this paper.]

image::{s-img}[{s-width}, align='center']

The statist’s views on personnel and economics articulated above are consistent
themes that permeate the way the statist thinks about the wonders of the state
and the depredations of the free market. In the remainder of this paper I will
show why these views are specious, and hence why we should never settle for the
state.
