== People 

The statist perceives the state as a group of individuals who selflessly toil
for the “common good,” and who have a mandate, through the electoral process,
to pass legislation as these individuals see fit to force changes in behavior
of those outside the state. The statist lauds “public service,” and believes
that those at the state are deserving of special privileges and respect given
their selflessness and the awesome power they wield. Indeed many of the most
powerful figures at the state, particularly the national leader, generate
cult-like followings, where statists identify passionately with them, hang on
their every word, look to them for national direction and salvation, and
believe it is not only their task to right every wrong but also that they have
the ability and wisdom to do so. Even if there are a few “rotten apples” now
and then at the state, this is not seen as an indictment of the notion of the
state, just of those individuals. When the state makes mistakes, the statist is
very forgiving, almost resigned to the fact that this is to be expected. These
mistakes don’t cause the statist to question the idea of the state, but simply
confirms to the statist that society needs to elect better representatives at
the next election.

Contrast this to the statist’s views of those in the private sector. These
people are seen as individuals who selfishly seek profits by taking unfair
advantage of consumers, and who must be brought back into line and closely
regulated by the state. Working in the private sector doesn’t garner anywhere
near the respect that working for the state does, and the statist is constantly
critical of any excesses enjoyed by those in the private sector, such as the
accumulation of significant wealth. Any “rotten apples” in the private sector
only confirm to the statist the wretchedness of the private sector and the need
for regulation by the state. In fact, no matter how closely regulated by the
state a business may be, if there is a problem that surfaces, the statist
assumes it is solely to do with the nature of the private sector itself, and
that the only answer is more state regulation. When a business makes a mistake,
statists are unforgiving; as consumers, they may immediately take their
business elsewhere, often bankrupting such businesses.

The contrast between how the statist views those at the state and those in the
private sector is somewhat odd. I can only fathom three reasons for this.

Perhaps statists believe in extra-terrestrials, in the sense that the beings at
the state belong to a different species from the mere humans who constitute the
private sector. These extra-terrestrial beings do not have any of the foibles
of private sector humans, and thus are perfectly suited to work at the state
and naturally gravitate in that direction (I’ll call this the “ET Theory”).

However, that explanation wouldn’t suffice as regards those beings who move
from the private sector to the state.  Thus perhaps statists believe in a
special type of machine known as the “Moral-ator.” When a person moves from the
private sector to the state, perhaps he passes through the Moral-ator, which
strips him of his private sector foibles and converts him into a selfless
public servant (I’ll call this the “Moral-ator Theory”).  footnote:[It’s not
clear how the statist thinks about those who move in the reverse direction,
from the state to the private sector.  Perhaps the Moral-ator works in reverse
too, attaching private sector foibles to former state personnel.]

Finally, perhaps there are some humans who are completely selfless individuals.
Perhaps the voters, who apparently are incompetent to manage their own lives
without detailed oversight from the beings at the state, nevertheless in a
single act of brilliance each election are able to find these special
individuals from the broader population and elect them, and only them, into
office (I’ll call this the “Voter Episodic Brilliance Theory” or “VEB Theory”
for short).  footnote:[Statists tend to identify passionately with one
political party.  Given how readily statists overlook or minimize the foibles
of candidates from their own party, and how quickly they excoriate candidates
from the “other” party for their every foible, no matter how small, statists
could only subscribe to the VEB Theory when their party’s candidates are
elected. Which only makes this theory less credible.]

I will hereinafter call all three of these theories together, the “Tooth Fairy
Theories.”
